### ISSUE TITLE
🐛 [Bug]: 进入设计器后，在没点击画布里面任意物料的情况下，即整个画布没有选中（没有选中就是指画布的外边框没有出现虚线时，或者没有选中任意物料），这时候新增变量或者脚本或者操作布局的改动，改动后点击变量的保存，或者脚本新增后点击右上角的工具栏保存，会提示保存成功，但实际没有保存成功。

### ISSUE THREAD

**Issue by cnbin** [opentiny/tiny-engine#104]
### Environment

谷歌浏览器

### Version

17

### Version

3.10.1

### Link to minimal reproduction

...

### Step to reproduce

希望当页面管理选择某一个页面后，即代表当前的操作时针对这个页面.vue进行操作。即使没有选中画布的情况下，点击左侧的变量或者JS按钮进行操作时，连续添加变量或者编辑JS脚本，也能正常保存编辑后的数据。而不是每次操作前都要点一下画布（选择body或者任意物流）才行，这样用户体验很差，用起来也很麻烦。点击设计器右上角的保存按钮时，会自动让鼠标在画布中的已选中物料失去焦点，因此往往在页面出现添加变量后，点击保存，后续再继续添加变量时，就实际上没保存起来。

### What is expected

希望当页面管理选择某一个页面后，即代表当前的操作时针对这个页面.vue进行操作。即使没有选中画布的情况下，点击左侧的变量或者JS按钮进行操作时，连续添加变量或者编辑JS脚本，也能正常保存编辑后的数据。而不是每次操作前都要点一下画布（选择body或者任意物流）才行，这样用户体验很差，用起来也很麻烦。点击设计器右上角的保存按钮时，会自动让鼠标在画布中的已选中物料失去焦点，因此往往在页面出现添加变量后，点击保存，后续再继续添加变量时，就实际上没保存起来。

**Comment by wenmine** [comment]
@cnbin ok。这个问题我们已经收录下来了，待排查解决。感谢您的反馈
