### ISSUE TITLE
图元编排，流程编排，物料定制（编排）

### ISSUE THREAD

**Issue by chenshuichao** [opentiny/tiny-engine#11]
官网说图元编排，流程编排，物料定制（编排），但是，咱们的工程运行起来，没有看到相应的能力啊，是相关源代码未开放，还有继续整理相关代码吗？

**Comment by wenmine** [comment]
@chenshuichao hi，目前开源的是核心能力低码引擎，图元编排，流程编排，物料定制内容是我们基于引擎的优秀实践，之后会在官网开放体验demo，但是具体平台源码我们是不开源的~若感兴趣的话，可以利用我们的引擎能力定制符合你们自身要求的定制化低代码平台

**Comment by chenshuichao** [comment]
好吧😄，就是和阿里一样呗。
