### ISSUE TITLE
🐛 [Bug]: 表格组件 开启 toolbar slot或者default slot 表格没有可以拖拽的区域

### ISSUE THREAD

**Issue by Thea1211** [opentiny/tiny-engine#111]
### Environment

chrome

### Version

v16.14.0

### Version

no

### Link to minimal reproduction

https://github.com/opentiny/tiny-engine.git

### Step to reproduce

![test](https://github.com/opentiny/tiny-engine/assets/24974566/71056224-01b4-4c65-b814-da363e21d6c6)

**Comment by chilingling** [comment]
感谢反馈

**Comment by ghost** [comment]
@Thea1211 请提供下bundle.json中tinyGrid组件的配置。正确的配置后插槽展示应该如下图所示，配置位置在schema.slots
`{
  "component: "TinyGrid",
  "schema": {
    "slots": {
      "toolbar": {}
    }
  }
}`
![image](https://github.com/opentiny/tiny-engine/assets/142570291/c2d34f22-e227-4ba0-bc25-e61c5d5700f1)

**Comment by Thea1211** [comment]
okk 之前放在了 scheme的properties下面的

**Comment by Thea1211** [comment]
如果希望这个slot可以传参 json要怎么写的 
![image](https://github.com/opentiny/tiny-engine/assets/24974566/46529471-b6b2-445b-b50b-9b80a4ad03c3)
le类似表格的column的header和default slot 外层toolbar是这样 
![image](https://github.com/opentiny/tiny-engine/assets/24974566/a3ea39c1-82c4-4f6d-aa90-5724766b001f)
