### ISSUE TITLE
🐛 [Bug]: 在区块插件面板和右键menu 都无法新建区块

### ISSUE THREAD

**Issue by Thea1211** [opentiny/tiny-engine#113]
### Environment

chrome

### Version

v16.14.0

### Version

no

### Link to minimal reproduction

https://github.com/opentiny/tiny-engine

### Step to reproduce

![tete](https://github.com/opentiny/tiny-engine/assets/24974566/fbd6e4bd-0a2c-4229-8092-e601edfc6c77)

**Comment by chilingling** [comment]
区块功能依赖后端相关的能力，后端当前未开源，后续会开放，请期待~

**Comment by Thea1211** [comment]
> 区块功能依赖后端相关的能力，后端当前未开源，后续会开放，请期待~

数据源发送请求的功能也是吗 现在也是不能用的 现在获取数据源的话 是不是需要在出码的代码里面写接口请求的

**Comment by chilingling** [comment]
> > 区块功能依赖后端相关的能力，后端当前未开源，后续会开放，请期待~
> 
> 数据源发送请求的功能也是吗 现在也是不能用的 现在获取数据源的话 是不是需要在出码的代码里面写接口请求的

我们在应用层级的出码也是有数据源的出码，不需要用户自行编写，但是这块当前没法体验，麻烦也等等，后面会开放相关代码让大家体验的
