### ISSUE TITLE
🐛 [Bug]: 设计态，在对话框内无法切换tab

### ISSUE THREAD

**Issue by stwflyfox** [opentiny/tiny-engine#115]
### Environment

chrome

### Version

latest

### Version

latest

### Link to minimal reproduction

设计态，在对话框dialogBox内无法切换tab页签

### Step to reproduce

![a744a281d590d19022575a5da8aad81](https://github.com/opentiny/tiny-engine/assets/3983204/df1edc79-c49f-41fe-ad59-0d4e89736d5f)

**Comment by chilingling** [comment]
感谢反馈 @stwflyfox

**Comment by stwflyfox** [comment]
最新版本还是没有修复这个bug?

**Comment by lichunn** [comment]
你好，目前针对这个问题我们已经制定好方案，限制对话框在画布的点击操作并对对话框的属性面板进行优化，近期会排期修复
