### ISSUE TITLE
🐛 [Bug]:  lowcodewrap 多余的参数

### ISSUE THREAD

**Issue by qian-chen97** [opentiny/tiny-engine#116]
### Environment

windwos11

### Version

16

### Version

最新

### Link to minimal reproduction

-

### Step to reproduce

![ec8e83dfafbc366fcfdb09b20ecded8](https://github.com/opentiny/tiny-engine/assets/46392918/4e5efe8b-13b4-4420-892f-1ea23a76863f)
![4c15dfa44b09a7a8f198bdd95dfdfae](https://github.com/opentiny/tiny-engine/assets/46392918/f5b1cb5e-a327-4f52-a34c-133f404f0c51)

**Comment by wenmine** [comment]
@yaoyun8 帮忙看一下

**Comment by ghost** [comment]
@ArtisanQ 1. lowcodeWrap第三个为多余参数，待修改；2. stores为全局状态，在调用wrap({ stores })后，可以在warp返回的函数中使用this.stores
