### ISSUE TITLE
🐛 [Bug]: tinyGrid与collection绑定后报错

### ISSUE THREAD

**Issue by coolphk** [opentiny/tiny-engine#118]
### Environment

chrome

### Version

latest

### Version

latest

### Link to minimal reproduction

![image](https://github.com/opentiny/tiny-engine/assets/16846896/62fe7c50-0606-4b4e-8aea-ae92b1bc57f8)
![image](https://github.com/opentiny/tiny-engine/assets/16846896/c3920a0a-0cdf-446b-befb-e6c064bdc7b9)

### Step to reproduce

先用Collection绑定一个数据源，然后再用tinyGrid与collection绑定。然后保存预览，会出现报错。

### What is expected

希望可以正常绑定。

**Comment by chilingling** [comment]
@coolphk  图片裂了，麻烦重新上传一下

**Comment by coolphk** [comment]
@chilingling 已经重新上传

**Comment by chilingling** [comment]
mock 数据缺失所致，已修复

**Comment by coolphk** [comment]
![image](https://github.com/opentiny/tiny-engine/assets/16846896/2909c1e6-033a-4c9b-a479-eaa8449e3083)
这个错误在设计时也会出现，tinyGrid拖入后就会报错

**Comment by wenmine** [comment]
经沟通此问题为缓存导致，后来没有复现
