### ISSUE TITLE
bug: 走马灯删除所有选项卡后添加出现界面异常

### ISSUE THREAD

**Issue by gliheng** [opentiny/tiny-engine#12]
重现方法：

1. 新建文档
2. 加入走马灯
3. 属性面板删除所有选项卡
4. 再点添加

这个地方取的是第一个子组件的名字，这种情况下是空的。
https://github.com/opentiny/tiny-engine/blob/9e5f9a386b1b92af76b33ccef62da874f2ba809a/src/common/component/MetaContainer.vue#L51

**Comment by wenmine** [comment]
@gliheng 好的收到，感谢反馈~~
