### ISSUE TITLE
🐛 [Bug]: 画布设置在pc端宽度设置为1440px时，会自动切换为大屏下且宽度被设置成了1920px

### ISSUE THREAD

**Issue by lizhijie429** [opentiny/tiny-engine#120]
### Environment

chrome

### Version

latest

### Version

latest

### Link to minimal reproduction

![~HS6ZMD)1)G_GV F$%M $XM](https://github.com/opentiny/tiny-engine/assets/7768535/47996c36-18dc-4309-844b-2498b5c818ec)

### Step to reproduce

顶部工具栏画布设置选择pc端宽度设置为1440px后，回车确认会自动切换为大屏下且宽度被设置成了1920px

### What is expected

希望画布实际宽度及输入框显示的是我输入的值。

### What is actually happening

No response

### Any additional comments (optional)

No response

**Comment by wenmine** [comment]
@lizhijie429 感谢反馈，我们看一下
