### ISSUE TITLE
✨ [Feature]: 本地启动项目时，如果更改本地开发启动的base路径为/design，页面控制台会报错，可以帮忙解决一下吗

### ISSUE THREAD

**Issue by youchen133** [opentiny/tiny-engine#121]
### What problem does this feature solve

<img width="1973" alt="image" src="https://github.com/opentiny/tiny-engine/assets/27907927/d0e73d5a-942b-4c41-a3de-292d68566f83">

design-core文件目录下的vite.config.js

const config = {
  base: '/design',
  publicDir: path.resolve(__dirname, './public'),
  resolve: {
    extensions: ['.js', '.jsx', '.vue'],
    alias: {}
  }
### What does the proposed API look like

可否帮忙看一下，解决一下这个控制台报错

**Comment by wenmine** [comment]
@youchen133 感谢反馈，已经记录，会尽快安排解决

**Comment by kedenLi** [comment]
能提供更多的信息吗？我这边复现不了，或者在微信群里和我们沟通一下

**Comment by kedenLi** [comment]
@youchen133

**Comment by chilingling** [comment]
从报错信息来看，这个是 monaco worker 相关的报错，暂时没发现影响到的功能模块，后续会定位消除掉

**Comment by youchen133** [comment]
> 能提供更多的信息吗？我这边复现不了，或者在微信群里和我们沟通一下

修改design-core下的打包配置文件vite.config.js，将base改成/design，本地启动项目页面控制台就有报错

**Comment by wenmine** [comment]
> 从报错信息来看，这个是 monaco worker 相关的报错，暂时没发现影响到的功能模块，后续会定位消除掉

这个是此issue的答案
