### ISSUE TITLE
🐛 [Bug]: 设计器新增数据源后，在线点击发送请求能够调通接口，绑定到表格后，预览时报错，点击右上角出码后本地运行也调不了接口

### ISSUE THREAD

**Issue by cnbin** [opentiny/tiny-engine#124]
### Environment

谷歌浏览器

### Version

17

### Version

3.1.10

### Link to minimal reproduction

设计器新增数据源后，在线点击发送请求能够调通接口，将数据源绑定到表格的fetchData属性后，预览时报错，点击右上角出码后本地运行也调不了接口。预览提示fetchData3.api.apply is not a function

### Step to reproduce

设计器新增数据源后，在线点击发送请求能够调通接口，将数据源绑定到表格的fetchData属性后，预览时报错，点击右上角出码后本地运行也调不了接口。预览提示fetchData3.api.apply is not a function

### What is expected

希望能否正常使用数据源

**Comment by wenmine** [comment]
@cnbin 感谢反馈，已收录，会尽快安排修复

**Comment by ghost** [comment]
@cnbin 
拉取最新代码后看一下。
本地新增的数据源，需要保证预览时appinfo.json中数据一致。因为mockServer未对应用数据进行处理，目前只能手动修改json文件使数据一致。

**Comment by cnbin** [comment]
好的，谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yaoyun8 ***@***.***&gt;
发送时间: 2024年1月11日 16:29
收件人: opentiny/tiny-engine ***@***.***&gt;
抄送: cnbin ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [opentiny/tiny-engine] �� [Bug]: 设计器新增数据源后，在线点击发送请求能够调通接口，绑定到表格后，预览时报错，点击右上角出码后本地运行也调不了接口 (Issue #124)





 
@cnbin
 拉取最新代码后看一下。
 本地新增的数据源，需要保证预览时appinfo.json中数据一致。因为mockServer未对应用数据进行处理，目前只能手动修改json文件使数据一致。
