### ISSUE TITLE
🐛 [Bug]: 加入了三方组件 是es文件 在build canvas插件的时候 报错

### ISSUE THREAD

**Issue by Thea1211** [opentiny/tiny-engine#127]
### Environment

chrome

### Version

v16.14.0

### Version

no

### Link to minimal reproduction

![11](https://github.com/opentiny/tiny-engine/assets/24974566/ca2482f7-b3f2-4f5a-b8b8-6649e929de00)

### Step to reproduce

应该是vite配置里面的 define 
 define: {
    'process.env': {}
  }, 这个配置的目的是什么

**Comment by wenmine** [comment]
@yaoyun8 这个也一起看看...

**Comment by ghost** [comment]
@Thea1211 麻烦提供下详细修改。
'process.env': {}的配置是@opentiny/vue组件库需要的vite配置，如果不需要该组件库，可以从代码中去除

**Comment by Thea1211** [comment]
在三方组件配置加define: {
    'process.env.NODE_ENV': JSON.stringify('production')
  }, 就没问题了 tiny-engine这个打包部署之后可以用吗 是不是还需要后端的

**Comment by ghost** [comment]
@Thea1211 这个要看业务需求，有实践只需要schema的，就不依赖后端；如果是包含应用数据的修改、预览这些，就需要后端支持。我们的后端开源工作也在抓紧进行中。

**Comment by Thea1211** [comment]
怎么看有人可以连数据发送请求的
还有一个问题就是 
如果希望这个slot可以传参 json要怎么写的
![image](https://github.com/opentiny/tiny-engine/assets/24974566/051cfcaf-15b5-429f-bb53-69c41242502e)
类似表格的column的header和default slot 
表格外层toolbar slot是这样
![image](https://github.com/opentiny/tiny-engine/assets/24974566/fb60f90b-bc36-466f-bde5-77b14e1e93c5)

**Comment by ghost** [comment]
@Thea1211 举个例子，如下图所示
插槽指定参数名，绑定变量时输入变量名组成的表达式
![image](https://github.com/opentiny/tiny-engine/assets/142570291/5a9a0a0e-9412-442e-8e41-432a1e8bb342)
![image](https://github.com/opentiny/tiny-engine/assets/142570291/3ed928d5-9905-4f93-a1ac-a49b46645ba3)

bundle.json中组件的插槽定义如下：
![image](https://github.com/opentiny/tiny-engine/assets/142570291/be431947-474b-4320-bd8d-1e82c2e12c82)

**Comment by Thea1211** [comment]
好的 非常感谢
