### ISSUE TITLE
请问什么时候会开放对应的文档？

### ISSUE THREAD

**Issue by knight-peter** [opentiny/tiny-engine#13]
目前没有对应文档，所有实践都只能摸索。

**Comment by wenmine** [comment]
@knight-peter 你好~请问具体想要了解哪些方面的文档？可以看看当前我们官网提供的资料是否符合你的期望 https://opentiny.design/tiny-engine#/home

**Comment by chenshuichao** [comment]
@wenmine ，学院课程都挺好的，是不是还没有写完就发布出来了？好几门课程就只有一个提纲。

**Comment by chenshuichao** [comment]
我觉得，如果学院课程能够做得完善，详细，图文并茂，实战结合。

**Comment by wenmine** [comment]
@chenshuichao 学院课程内容目前还在整理中，会陆续开放新的内容~

**Comment by wenmine** [comment]
@knight-peter @chenshuichao hi，我们更新了 [用户手册](https://opentiny.design/tiny-engine#/help-center/course/engine) 在官网，希望能够帮助到你们~
