### ISSUE TITLE
🐛 [Bug]: 右侧配置面板，给物料设置内外边距时，只有点中中间的数字才能弹出margin框进行设置，建议改成选中该区域就能够弹出来

### ISSUE THREAD

**Issue by cnbin** [opentiny/tiny-engine#134]
### Environment

chrome

### Version

17

### Version

3.1.10

### Link to minimal reproduction

右侧配置面板，给物料设置内外边距时，只有点中中间的数字才能弹出margin框进行设置，建议改成选中该区域就能够弹出来右侧配置面板，给物料设置内外边距时，只有点中中间的数字才能弹出margin框进行设置，建议改成选中该区域就能够弹出来

### Step to reproduce

右侧配置面板，给物料设置内外边距时，只有点中中间的数字才能弹出margin框进行设置，建议改成选中该区域就能够弹出来

### What is expected

建议改成选中该区域就能够弹出来设置边距的面板，提高配置效率

**Comment by wenmine** [comment]
@cnbin 感谢反馈，近期内修复
