### ISSUE TITLE
🐛 [Bug]: 左侧面板编写JS脚本后，进行保存，设计器会自动格式化，但一个函数里面结尾的花括号，当大于1个时，花括号被自动挤到同一行，每次进入设计器后都要手动右键进行Prettier一下，不然难以阅读。

### ISSUE THREAD

**Issue by cnbin** [opentiny/tiny-engine#135]
### Environment

ch

### Version

17

### Version

3.1.10

### Link to minimal reproduction

 左侧面板点击弹出代码编辑器进行编写JS脚本后，点击保存，设计器会自动格式化，但一个函数里面结尾的花括号，当大于1个时，花括号被自动挤到同一行，每次进入设计器后都要手动右键进行Prettier一下，不然难以阅读。

### Step to reproduce

 左侧面板点击弹出代码编辑器进行编写JS脚本后，点击保存，设计器会自动格式化，但一个函数里面结尾的花括号，当大于1个时，花括号被自动挤到同一行，每次进入设计器后都要手动右键进行Prettier一下，不然难以阅读。

### What is expected

建议优化下编辑器，在点击保存后，下次打开脚本框，不要把结尾的花括号}}}都挤到同一行，能够保存右键prettier后的代码风格。

**Comment by wenmine** [comment]
@hexqi 帮忙看看

**Comment by hexqi** [comment]
> @hexqi 帮忙看看

看起来是格式化问题

**Comment by cnbin** [comment]
![11](https://github.com/opentiny/tiny-engine/assets/8576832/46a2e0f4-9a64-429e-b0bf-e2d05a02eb43)
如以上图片这种情况。

**Comment by cnbin** [comment]
前面可能我描述有误，不是函数结尾，是里面某个参数或者返回对象的情况出现格式乱了。

**Comment by hexqi** [comment]
> 前面可能我描述有误，不是函数结尾，是里面某个参数或者返回对象的情况出现格式乱了。

OK, 问题可以复现。会尽快修复。
