### ISSUE TITLE
✨ [Feature]: 现在画布和预览渲染物料时，读的是cdn方式加载tiny默认主题样式，能否提供一份tiny欧若拉的主题css的cdn，以便加载显示

### ISSUE THREAD

**Issue by cnbin** [opentiny/tiny-engine#136]
### What problem does this feature solve

因为默认主题偏紫色，欧若拉主题比较贴切我们现有产品的主题色，用tinyEngine开发的应用效果会更好些，为了在画布中和预览能更真实展示物料，希望能提供一份cdn加载tiny欧若拉主题的css文件地址。目前预览默认是加载这个主题文件https://unpkg.com/@opentiny/vue-theme@3/index.css

### What does the proposed API look like

因为默认主题偏紫色，欧若拉主题（天蓝色）比较贴切我们现有产品的主题色，用tinyEngine开发的应用效果会更好些，为了在画布中和预览能更真实展示物料，希望能提供一份cdn加载tiny欧若拉主题的css文件地址。目前预览默认是加载这个主题文件https://unpkg.com/@opentiny/vue-theme@3/index.css

**Comment by ghost** [comment]
@cnbin 欧若拉主题的css文件在制作中了，发布后会通知到你

**Comment by ghost** [comment]
@cnbin 已发布
https://npm.onmicrosoft.cn/@opentiny/vue-theme@3.12.1/aurora-theme/index.css

**Comment by cnbin** [comment]
好的，十分感谢。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yaoyun8 ***@***.***&gt;
发送时间: 2023年12月29日 16:27
收件人: opentiny/tiny-engine ***@***.***&gt;
抄送: cnbin ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [opentiny/tiny-engine] ✨ [Feature]: 现在画布和预览渲染物料时，读的是cdn方式加载tiny默认主题样式，能否提供一份tiny欧若拉的主题css的cdn，以便加载显示 (Issue #136)





 
@cnbin 已发布
 ***@***.******@***.***/aurora-theme/index.css
