### ISSUE TITLE
✨ [Feature]: 添加变量时，能否增加多一个变量描述的输入框，现在开发人员添加多个变量后，交给其他开发人员或设计人员协同开发时，有时很难快速知道这个变量代表的意思。

### ISSUE THREAD

**Issue by cnbin** [opentiny/tiny-engine#137]
### What problem does this feature solve

添加变量时，能否增加多一个变量描述的输入框，现在开发人员添加多个变量后，交给其他开发人员或设计人员协同开发同一个应用时，有时很难快速知道这个变量代表的意思，不利于协同开发。

### What does the proposed API look like

希望添加变量时，能够多一个添加变量的描述，可以提供给用户去加上变量备注，以便多人协同开发，提高效率。

**Comment by chilingling** [comment]
增强类型功能，欢迎 PR
