### ISSUE TITLE
🐛 [Bug]: element的icon引入 预览的时候 报错 The requested module '@element-plus/icons-vue' does not provide an export named 'Avatar'

### ISSUE THREAD

**Issue by Thea1211** [opentiny/tiny-engine#141]
### Environment

chrome

### Version

v16.14.0

### Version

latest

### Link to minimal reproduction

https://github.com/opentiny/tiny-engine

### Step to reproduce

![image](https://github.com/opentiny/tiny-engine/assets/24974566/e5ed2e16-7135-4a63-858e-c2309f84c53c)
elbutton加了icon属性 设计和代码到处放到preview的模板 都可以正常显示
代码：
![image](https://github.com/opentiny/tiny-engine/assets/24974566/5ebd9be2-4c61-4497-88d5-24035eeaf6fd)

 但是预览的时候报错
![image](https://github.com/opentiny/tiny-engine/assets/24974566/bbb41ff2-16bc-43b8-9d31-7fc269f71560)

**Comment by wenmine** [comment]
@yaoyun8 帮忙看看~

**Comment by ghost** [comment]
@Thea1211 预览的依赖定义在packages\design-core\src\preview\src\preview\importMap.js，先查看下是否有这个依赖，然后查看这个cdn地址上的文件导出的内容。可以把cdn地址贴一下

**Comment by Thea1211** [comment]
'@element-plus/icons-vue': 'https://unpkg.com/@element-plus/icons-vue',
![image](https://github.com/opentiny/tiny-engine/assets/24974566/fdcecf22-a61e-4f21-948b-2560cd76db55)
加载这里面的

**Comment by ghost** [comment]
这个文件是个iife，[importmap](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/script/type/importmap)需要是esm格式。

**Comment by ghost** [comment]
如果unpkg或jsDelivr找不到esm格式的cdn，可以尝试在https://esm.sh/#docs

**Comment by Thea1211** [comment]
可以了 感谢
