### ISSUE TITLE
🐛 [Bug]: 画板拖入了按钮组件，并绑定了点击事件，第一次预览的时候点击按钮可以触发，刷新预览页面以后就不再触发了

### ISSUE THREAD

**Issue by youchen133** [opentiny/tiny-engine#143]
### Environment

mac

### Version

16

### Version

latest

### Link to minimal reproduction

启动直接复现

### Step to reproduce

<img width="1799" alt="image" src="https://github.com/opentiny/tiny-engine/assets/27907927/2a837633-a21b-4ca7-b0e1-07fa3b760393">
<img width="2020" alt="image" src="https://github.com/opentiny/tiny-engine/assets/27907927/1c960b61-df6b-4148-ad1f-82bd393c1ca2">
<img width="1833" alt="image" src="https://github.com/opentiny/tiny-engine/assets/27907927/c8c075b7-7447-4e64-8200-6cf200e0e9a1">
刷新当前预览页面，点击按钮不再打印日志

**Comment by gene9831** [comment]
@youchen133 你好，请问你是使用的mac系统的哪一款浏览器。根据你的步骤描述，我在windows系统上使用Chrome浏览器并没有复现出此问题

**Comment by youchen133** [comment]
> @youchen133 你好，请问你是使用的mac系统的哪一款浏览器。根据你的步骤描述，我在windows系统上使用Chrome浏览器并没有复现出此问题

我的是mac系统14.1  chrome浏览器

**Comment by youchen133** [comment]
https://github.com/opentiny/tiny-engine/assets/27907927/6faa6d5f-fcb6-4ddd-a7e9-42d53662c838

**Comment by chilingling** [comment]
> Kapture.2023-12-14.at.10.14.28.mp4

从你视频来看，是有触发的，
注意看：刷新页面前后，点击按钮，信息的条数都是有增加的（控制台左侧的信息条数列表）
你可以尝试切换到 iframe 层级，就可以看到点击回调打印的信息了
![image](https://github.com/opentiny/tiny-engine/assets/26962197/385421a1-662d-41bf-a8ec-faad996357c2)
![image](https://github.com/opentiny/tiny-engine/assets/26962197/44882abf-8717-46eb-9abd-3bba0c8d7f78)

**Comment by youchen133** [comment]
> 尝试切换到 iframe 层级，就可以看到点击回调打印的信息

感谢大佬，已看到打印日志
