### ISSUE TITLE
🐛 [Bug]: 在低代码平台组件的属性的ref里定义个名称，在其他组件的方法中调用this.$（名称），打印后获取到这个组件实例，但是给实例的其中某一属性赋值报错'set' on proxy: trap returned falsish for property 'text'

### ISSUE THREAD

**Issue by xmh0604** [opentiny/tiny-engine#144]
### Environment

谷歌浏览器 windows 11

### Version

16.20.2

### Version

最新的

### Link to minimal reproduction

![步骤1](https://github.com/opentiny/tiny-engine/assets/76865979/eb23c160-49d6-4671-9067-b5564f915dca)
![步骤2](https://github.com/opentiny/tiny-engine/assets/76865979/e46b6223-2a8a-4369-bad5-7ac90b9833d8)
![步骤3](https://github.com/opentiny/tiny-engine/assets/76865979/e21a57ba-75d8-4c5c-8e2f-d4cb71f1ad16)
1.在页面中的button组件属性的ref中命名“buttonTL”
2.在页面中的另外一个button组件的方法中，打印this.$("buttonTL")，预览页面点击按钮，获取到组件实例，但是直接给组件实例赋值buttonTL.text = "文案修改";就报错了 ：TypeError: 'set' on proxy: trap returned falsish for property 'text'
    at Object.onClickNew6 (<anonymous>:184:21)
    at Proxy.<anonymous> (<anonymous>:74:30)
    at _createElementVNode.onClick._cache.<computed>._cache.<computed> (<anonymous>:271:87)
 

### Step to reproduce

![步骤1](https://github.com/opentiny/tiny-engine/assets/76865979/eb23c160-49d6-4671-9067-b5564f915dca)
![步骤2](https://github.com/opentiny/tiny-engine/assets/76865979/e46b6223-2a8a-4369-bad5-7ac90b9833d8)
![步骤3](https://github.com/opentiny/tiny-engine/assets/76865979/e21a57ba-75d8-4c5c-8e2f-d4cb71f1ad16)
1.在页面中的button组件属性的ref中命名“buttonTL”
2.在页面中的另外一个button组件的方法中，打印this.$("buttonTL")，预览页面点击按钮，获取到组件实例，但是直接给组件实例赋值buttonTL.text = "文案修改";就报错了 ：TypeError: 'set' on proxy: trap returned falsish for property 'text'
    at Object.onClickNew6 (<anonymous>:184:21)
    at Proxy.<anonymous> (<anonymous>:74:30)
    at _createElementVNode.onClick._cache.<computed>._cache.<computed> (<anonymous>:271:87)
 

### What is expected

  我想问一下用获取组件实例，去操作这个组件实例的办法是否行得通？如果能行，能提供的正确操作的demo吗？如果不行，有类似替代这种操作方式的办法吗？

**Comment by chilingling** [comment]
@xmh0604  我自测了下，使用 vue 官方文档的暴露属性即可在低代码平台生效

vue 官方示例：https://vuejs.org/guide/essentials/template-refs

使用的组件需要定义了 expose 暴露属性

```vue
<script setup>
import { ref } from 'vue'

const a = 1
const b = ref(2)

// Compiler macros, such as defineExpose, don't need to be imported
defineExpose({
  a,
  b
})
</script>
```

自测相关截图：
![image](https://github.com/opentiny/tiny-engine/assets/26962197/7adc76dd-1f4f-48c6-a648-e19a7a974d8a)
![image](https://github.com/opentiny/tiny-engine/assets/26962197/f6db0872-c5d5-4760-a015-9e95eeec7c46)

**Comment by chilingling** [comment]
问题类 issue，已答复
