### ISSUE TITLE
很关注本项目，希望尽快出详细的官方文档

### ISSUE THREAD

**Issue by 2089764** [opentiny/tiny-engine#15]
很关注本项目，希望尽快出详细的官方文档

**Comment by wenmine** [comment]
@2089764 你好~请问具体想要了解哪些方面的文档？可以看看当前我们官网提供的资料是否符合你的期望 https://opentiny.design/tiny-engine#/home

**Comment by gxiaosong** [comment]
请问该引擎适合制作微信小程序吗，目前文档少，没啥思路

**Comment by wenmine** [comment]
@gxiaosong hi，我们引擎暂时面向的更多还是移动端的H5应用和PC端，暂时还不适合制作微信小程序，也非常欢迎您对引擎进行二次开发，打造出一个适合制作小程序的低代码平台
