### ISSUE TITLE
✨ [Feature]: 现在设计器画布运行和预览都要走cdn，能否提供一种改成走本地加载的方式，因为我这边有些场景是在国密网络下的，没法连接外网，没法加载设计器。

### ISSUE THREAD

**Issue by cnbin** [opentiny/tiny-engine#152]
### What problem does this feature solve

现在画布运行和预览都要走cdn，能否提供一种改成走本地加载的方式，因为我这边有些场景是在国密网络下的，没法连接外网，没法加载设计器。

### What does the proposed API look like

在商密网、国密网下也能够运行设计器

**Comment by chilingling** [comment]
这一块涉及到一套私有化部署的方案，包括前端，后端、数据相关的全部在企业私有化部署

**Comment by cnbin** [comment]
是的，这块接下来看看能否规划提供这种技术支持，或者提供商业技术支持，可以进一步沟通和讨论合作方式。因为有些应用场景确实得私有化部署。

**Comment by kedenLi** [comment]
@cnbin 如果你有这个需求的话，你可以和我沟通一下，看一下你们的诉求。
