### ISSUE TITLE
🐛 [Bug]: modify [TinyButtonGroup]'s data code, then got messed component frontend.

### ISSUE THREAD

**Issue by kerneltravel** [opentiny/tiny-engine#157]
### Environment

edge 120.0.2210.61 windows 64bit

### Version

v16.15.0

### Version

yes

### Link to minimal reproduction

https://github.com/opentiny/tiny-engine

### Step to reproduce

to exercise by reproducing every compnent into my empty div, step by step of the original demo from https://opentiny.design/tiny-engine#/tiny-engine-editor  ,when in the '计费模式', modify the first button's text , bug occur

### Any additional comments (optional)

![image](https://github.com/opentiny/tiny-engine/assets/437879/a4739e09-20f8-46a3-840b-a51e1364bcf8)
![image](https://github.com/opentiny/tiny-engine/assets/437879/a9e807ed-cf4c-4185-8077-7f003fe89f5d)
![image](https://github.com/opentiny/tiny-engine/assets/437879/9de251fe-e787-4e86-8998-9ffce54a19b0)
![image](https://github.com/opentiny/tiny-engine/assets/437879/6ace150c-06d8-4012-a0f9-01bf0d982422)

**Comment by wenmine** [comment]
官网demo mock数据存在问题，近期内修复

**Comment by ghost** [comment]
@kerneltravel 已修复
![image](https://github.com/opentiny/tiny-engine/assets/142570291/ea479e1d-0290-4ee9-888f-bfc982f5daff)

**Comment by kerneltravel** [comment]
very good,  thanks! @yaoyun8
