### ISSUE TITLE
🐛 [Bug]: 将tinyGrid与collection绑定后，default插槽开关打开无效

### ISSUE THREAD

**Issue by coolphk** [opentiny/tiny-engine#159]
### Environment

chrome

### Version

16

### Version

latest

### Link to minimal reproduction

![f34c8954b5d0835ed8bf5c03e8f43db](https://github.com/opentiny/tiny-engine/assets/16846896/7b4ee878-911f-4458-871b-4f26cafa608c)

### Step to reproduce

将tinyGrid与collection绑定后，default插槽开关打开无效

**Comment by ghost** [comment]
@coolphk 表格列的默认插槽需要在有数据时显示，数据源的mock数据存在问题，可以先按下面方法手动修复：
将mockServer\src\services\appinfo.json中"source"字段的值拷贝到mockServer\src\mock\get\app-center\v1\apps\schema\918.json中"dataSource.list"

**Comment by ghost** [comment]
@coolphk 已修复
