### ISSUE TITLE
🐛 [Bug]: 设计器本地能正常运行，但打包后部署生产环境，没法运行，因为vite.config.js里面还有部分文件走的cdn还是unpkg.com，unpkg没法访问

### ISSUE THREAD

**Issue by cnbin** [opentiny/tiny-engine#162]
### Environment

谷歌浏览器

### Version

17

### Version

3.10.11

### Link to minimal reproduction

设计器打包后部署生产环境，没法运行，因为vite.config.js里面还有部分文件走的cdn是unpkg.com

### Step to reproduce

设计器打包后部署生产环境，没法运行，因为vite.config.js里面还有部分文件走的cdn是unpkg.com

### What is expected

设计器打包后部署生产环境能够正常运行

**Comment by chilingling** [comment]
已替换成国内兼容的 cdn 方案

**Comment by cnbin** [comment]
好的，谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: chilingling ***@***.***&gt;
发送时间: 2023年12月26日 19:54
收件人: opentiny/tiny-engine ***@***.***&gt;
抄送: cnbin ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [opentiny/tiny-engine] �� [Bug]: 设计器本地能正常运行，但打包后部署生产环境，没法运行，因为vite.config.js里面还有部分文件走的cdn还是unpkg.com，unpkg没法访问 (Issue #162)





 
已替换成国内兼容的 cdn 方案
