### ISSUE TITLE
🐛 [Bug]: 12月15日拉取最新代码后，本地运行，点击右上角下载本地代码，能正常运行，但打包后部署在生产环境，设计器打开后，点击下载本地代码，提示报错

### ISSUE THREAD

**Issue by cnbin** [opentiny/tiny-engine#164]
### Environment

谷歌浏览器

### Version

17

### Version

3.11

### Link to minimal reproduction

本地运行，点击右上角下载本地代码，能正常运行，但打包后部署在生产环境，设计器打开后，点击下载本地代码，提示报错。但之前没遇到过这种情况

### Step to reproduce

本地运行，点击右上角下载本地代码，能正常运行，但打包后部署在生产环境，设计器打开后，点击下载本地代码，提示报错。但之前没遇到过这种情况

### What is expected

生产环境，设计器打开后，能够正常点击下载本地代码。
![截屏2023-12-16 12 41 14](https://github.com/opentiny/tiny-engine/assets/8576832/76a531ba-09b0-49bf-bd66-92ab538d617f)

**Comment by chilingling** [comment]
请问能提供更详细的复现信息吗？

**Comment by cnbin** [comment]
估计这个问题还是跟打包后vite.config.js加载importmap常量里面的cdn地址有关，这块现在走的还是unpkg，我自己手动替换成https://registry.npmmirror.com后，打包后运行，能打开设计器，但是点击下载源码报错，而且右测属性面板现在选择某个组件，无法调整字体大小，边距，估计还是cdn的问题。最后的三行我是注释掉的，因为cdn换成https://registry.npmmirror.com找不到。不知道是不是跟这个有影响。prettier我是改成走esm.sh的。估计这样改还是有问题。所以请看看打包后的cdn这块改怎么改。
![CASCLingXPC_17029753976335](https://github.com/opentiny/tiny-engine/assets/8576832/5909d3c9-7aae-4fc0-8fcb-cadca4b85492)

**Comment by hexqi** [comment]
部署的生产环境是http站点吗，能否升级到https再试下呢？
下载代码功能我们使用了浏览器的文件系统API，这个功能限制了在安全上下文环境才能使用：比如localhost本地环境和https环境
![image](https://github.com/opentiny/tiny-engine/assets/18585869/151c24e2-b113-4030-a105-f6ae68003b8a)
