### ISSUE TITLE
🐛 [Bug]: 本地环境运行，新增数据源保存后，在线测试发送请求，接口调通正常， 但是点击本地下载代码后，数据源datasoure.json文件里面的数据格式显示不是json格式，乱了

### ISSUE THREAD

**Issue by cnbin** [opentiny/tiny-engine#165]
### Environment

谷歌浏览器

### Version

17

### Version

3.11

### Link to minimal reproduction

本地环境运行，在设计器上测试接口请求
![截屏2023-12-16 13 15 24](https://github.com/opentiny/tiny-engine/assets/8576832/93f20343-a80b-4418-9719-74202d3a9bf1)
出码后，dataSource.json格式变成这样子。
![截屏2023-12-16 13 17 04](https://github.com/opentiny/tiny-engine/assets/8576832/e17c7e25-d865-425d-9f32-4caac624b9e1)

### Step to reproduce

本地环境运行，新增数据源保存后，在线测试发送请求，接口调通正常， 但是点击本地下载代码后，数据源datasoure.json文件里面的数据格式显示不是json格式，乱了

### What is expected

本地环境运行，新增数据源保存后，出码之后，数据源datasoure.json文件里面的数据格式能够正常显示。

**Comment by Thea1211** [comment]
请求接口的功能开放了吗

**Comment by cnbin** [comment]
发送请求接口的功能我是在线把设计器的代码加上一句触发的。然后数据源这块目前我这边后端同事有根据接口文档自己搭建了后端，是不是数据源得等后端tiny开源后才比较好联调定位问题，使用起来？

**Comment by cnbin** [comment]
我做了调试，知道为啥datasource.json文件在本地出码后内容乱码了。这里少了JSON.parse。
![112](https://github.com/opentiny/tiny-engine/assets/8576832/8d44a465-f6a6-4ea5-afe5-746c2f75c085)

**Comment by chilingling** [comment]
@cnbin 未复现，请提供更详细的复现细节或者步骤
