### ISSUE TITLE
🐛 [Bug]: 数据源新增后出码后，放在出码基础模板工程里面，运行会提示报错，提示找不到load()方法。试了好像出码基础模板工程有点bug。

### ISSUE THREAD

**Issue by cnbin** [opentiny/tiny-engine#166]
### Environment

谷歌浏览器

### Version

17

### Version

3.11

### Link to minimal reproduction

数据源新增后出码后，运行会提示报错，找不到load()方法。
![426F5EF3-8857-4003-91F3-B076AA26EF30](https://github.com/opentiny/tiny-engine/assets/8576832/0ceb0ad7-fcee-48e8-b6cd-7d13c1453e1f)
<img width="552" alt="截屏2023-12-16 14 01 51" src="https://github.com/opentiny/tiny-engine/assets/8576832/23c77447-57af-4a32-aeb9-8b0d057c771f">

### Step to reproduce

数据源新增后出码后，运行会提示报错，找不到load()方法。这里dataSource.js的这里应该得改为[config.name]吧？因为出码是this.dataSourceMap.xxx数据源名称.load().then()
![4BA72BE9-300E-4A55-AD4C-3B44BD84B03B](https://github.com/opentiny/tiny-engine/assets/8576832/3a884836-0b69-4390-a8e3-7cdf1d5e7473)

### What is expected

新增数据源后，将源码放入出码的基础模板上运行，能够正常运行。能够正常数据源这个功能。

**Comment by chilingling** [comment]
出码工程模板已更新并修复该 bug ，欢迎重新体验 @cnbin
