### ISSUE TITLE
🐛 [Bug]: 帮忙看一下element plus时间日期组件拖入到画板以后，点击组件没有展示右侧属性配置，点击大纲才会展示

### ISSUE THREAD

**Issue by youchen133** [opentiny/tiny-engine#168]
### Environment

mac

### Version

16

### Version

latest

### Link to minimal reproduction

无

### Step to reproduce

https://github.com/opentiny/tiny-engine/assets/27907927/0d11c519-47cb-4f56-a072-2b1cc61ebad2

**Comment by ghost** [comment]
@youchen133 你好，麻烦提供一下这个组件的配置，即bundle.json里的组件配置

**Comment by youchen133** [comment]
`"components": [
        {
          "name": {
            "zh_CN": "时间选择器"
          },
          "component": "ElTimePicker",
          "icon": "time-picker",
          "description": "时间选择器",
          "screenshot": "",
          "npm": {
            "package": "element-plus",
            "exportName": "ElTimePicker",
            "version": "2.3.8",
            "script": "https://unpkg.com/element-plus@2.3.8/dist/index.full.mjs",
            "css": "https://unpkg.com/element-plus@2.3.8/dist/index.css",
            "destructuring": true
          },
          "group": "component",
          "schema": {
            "properties": [
              {
                "label": {
                  "zh_CN": "基础信息"
                },
                "description": {
                  "zh_CN": "基础信息"
                },
                "collapse": {
                  "number": 8,
                  "text": {
                    "zh_CN": "显示更多"
                  }
                },
                "content": [
                  {
                    "property": "modelValue",
                    "label": {
                      "text": {
                        "zh_CN": "绑定值"
                      }
                    },
                    "required": false,
                    "readOnly": false,
                    "disabled": false,
                    "cols": 12,
                    "widget": {
                      "component": "MetaCodeEditor",
                      "props": {
                        "language": "json"
                      }
                    },
                    "description": {
                      "zh_CN": "双向绑定值"
                    },
                    "labelPosition": "left"
                  },
                  {
                    "property": "size",
                    "label": {
                      "text": {
                        "zh_CN": "大小"
                      }
                    },
                    "cols": 12,
                    "rules": [],
                    "required": false,
                    "readOnly": false,
                    "disabled": false,
                    "widget": {
                      "component": "MetaSelect",
                      "props": {
                        "options": [
                          {
                            "label": "large",
                            "value": "large"
                          },
                          {
                            "label": "small",
                            "value": "small"
                          },
                          {
                            "label": "default",
                            "value": "default"
                          }
                        ]
                      }
                    },
                    "description": {
                      "zh_CN": "设置不同大小"
                    }
                  },
                  {
                    "property": "placeholder",
                    "label": {
                      "text": {
                        "zh_CN": "非范围选择时的占位内容"
                      }
                    },
                    "required": false,
                    "readOnly": false,
                    "disabled": false,
                    "cols": 12,
                    "widget": {
                      "component": "MetaInput",
                      "props": {}
                    },
                    "description": {
                      "zh_CN": "非范围选择时的占位内容"
                    }
                  },
                  {
                    "property": "start-placeholder",
                    "label": {
                      "text": {
                        "zh_CN": "范围选择时开始日期的占位内容"
                      }
                    },
                    "required": false,
                    "readOnly": false,
                    "disabled": false,
                    "cols": 12,
                    "widget": {
                      "component": "MetaInput",
                      "props": {}
                    },
                    "description": {
                      "zh_CN": "范围选择时开始日期的占位内容"
                    }
                  },
                  {
                    "property": "end-placeholder",
                    "label": {
                      "text": {
                        "zh_CN": "范围选择时结束日期的占位内容"
                      }
                    },
                    "required": false,
                    "readOnly": false,
                    "disabled": false,
                    "cols": 12,
                    "widget": {
                      "component": "MetaInput",
                      "props": {}
                    },
                    "description": {
                      "zh_CN": "范围选择时结束日期的占位内容"
                    }
                  },
                  {
                    "property": "format",
                    "label": {
                      "text": {
                        "zh_CN": "显示在输入框中的格式"
                      }
                    },
                    "required": false,
                    "readOnly": false,
                    "disabled": false,
                    "cols": 12,
                    "widget": {
                      "component": "MetaInput",
                      "props": {}
                    },
                    "description": {
                      "zh_CN": "显示在输入框中的格式"
                    }
                  },
                  {
                    "property": "editable",
                    "label": {
                      "text": {
                        "zh_CN": "文本框可输入"
                      }
                    },
                    "required": false,
                    "readOnly": false,
                    "disabled": false,
                    "defaultValue": true,
                    "cols": 12,
                    "widget": {
                      "component": "MetaSwitch",
                      "props": {}
                    },
                    "description": {
                      "zh_CN": "文本框可输入"
                    },
                    "labelPosition": "left"
                  },
                  {
                    "property": "clearable",
                    "label": {
                      "text": {
                        "zh_CN": "显示清除按钮"
                      }
                    },
                    "required": false,
                    "readOnly": false,
                    "disabled": false,
                    "defaultValue": true,
                    "cols": 12,
                    "widget": {
                      "component": "MetaSwitch",
                      "props": {}
                    },
                    "description": {
                      "zh_CN": "是否显示清除按钮"
                    },
                    "labelPosition": "left"
                  },
                  {
                    "property": "readonly",
                    "label": {
                      "text": {
                        "zh_CN": "只读"
                      }
                    },
                    "required": false,
                    "readOnly": false,
                    "disabled": false,
                    "cols": 12,
                    "widget": {
                      "component": "MetaSwitch",
                      "props": {}
                    },
                    "description": {
                      "zh_CN": "是否只读"
                    },
                    "labelPosition": "left"
                  },
                  {
                    "property": "disabled",
                    "label": {
                      "text": {
                        "zh_CN": "禁用"
                      }
                    },
                    "required": false,
                    "readOnly": false,
                    "disabled": false,
                    "cols": 12,
                    "widget": {
                      "component": "MetaSwitch",
                      "props": {}
                    },
                    "description": {
                      "zh_CN": "是否被禁用"
                    },
                    "labelPosition": "left"
                  }
                ]
              }
            ],
            "events": {
              "onUpdate:modelValue": {
                "label": {
                  "zh_CN": "双向绑定的值改变时触发"
                },
                "description": {
                  "zh_CN": "在值改变时触发"
                },
                "type": "event",
                "functionInfo": {
                  "params": [
                    {
                      "name": "value",
                      "type": "string",
                      "defaultValue": "",
                      "description": {
                        "zh_CN": "双向绑定的值"
                      }
                    }
                  ],
                  "returns": {}
                },
                "defaultValue": ""
              }
            }
          },
          "configure": {
            "loop": true,
            "condition": true,
            "styles": true,
            "isContainer": false,
            "isModal": false,
            "nestingRule": {
              "childWhitelist": "",
              "parentWhitelist": "",
              "descendantBlacklist": "",
              "ancestorWhitelist": ""
            },
            "isNullNode": false,
            "isLayout": false,
            "rootSelector": "",
            "shortcuts": {
              "properties": ["size"]
            },
            "contextMenu": {
              "actions": ["create symbol"],
              "disable": ["copy", "remove"]
            }
          }
        }
      ]`

snippets代码如下
`{
      "name": {
        "zh_CN": "时间选择器"
      },
      "icon": "time-picker",
      "screenshot": "",
      "snippetName": "ElTimePicker",
      "schema": {
        "componentName": "ElTimePicker",
        "props": {
          "modelValue": 1702785160952
        }
      }
    }`

**Comment by youchen133** [comment]
> @youchen133 你好，麻烦提供一下这个组件的配置，即bundle.json里的组件配置
components的配置：
`{
          "name": {
            "zh_CN": "时间选择器"
          },
          "component": "ElTimePicker",
          "icon": "time-picker",
          "description": "时间选择器",
          "screenshot": "",
          "npm": {
            "package": "element-plus",
            "exportName": "ElTimePicker",
            "version": "2.3.8",
            "script": "https://unpkg.com/element-plus@2.3.8/dist/index.full.mjs",
            "css": "https://unpkg.com/element-plus@2.3.8/dist/index.css",
            "destructuring": true
          },
          "group": "component",
          "schema": {
            "properties": [
              {
                "label": {
                  "zh_CN": "基础信息"
                },
                "description": {
                  "zh_CN": "基础信息"
                },
                "collapse": {
                  "number": 8,
                  "text": {
                    "zh_CN": "显示更多"
                  }
                },
                "content": [
                  {
                    "property": "modelValue",
                    "label": {
                      "text": {
                        "zh_CN": "绑定值"
                      }
                    },
                    "required": false,
                    "readOnly": false,
                    "disabled": false,
                    "cols": 12,
                    "widget": {
                      "component": "MetaCodeEditor",
                      "props": {
                        "language": "json"
                      }
                    },
                    "description": {
                      "zh_CN": "双向绑定值"
                    },
                    "labelPosition": "left"
                  },
                  {
                    "property": "size",
                    "label": {
                      "text": {
                        "zh_CN": "大小"
                      }
                    },
                    "cols": 12,
                    "rules": [],
                    "required": false,
                    "readOnly": false,
                    "disabled": false,
                    "widget": {
                      "component": "MetaSelect",
                      "props": {
                        "options": [
                          {
                            "label": "large",
                            "value": "large"
                          },
                          {
                            "label": "small",
                            "value": "small"
                          },
                          {
                            "label": "default",
                            "value": "default"
                          }
                        ]
                      }
                    },
                    "description": {
                      "zh_CN": "设置不同大小"
                    }
                  },
                  {
                    "property": "placeholder",
                    "label": {
                      "text": {
                        "zh_CN": "非范围选择时的占位内容"
                      }
                    },
                    "required": false,
                    "readOnly": false,
                    "disabled": false,
                    "cols": 12,
                    "widget": {
                      "component": "MetaInput",
                      "props": {}
                    },
                    "description": {
                      "zh_CN": "非范围选择时的占位内容"
                    }
                  },
                  {
                    "property": "start-placeholder",
                    "label": {
                      "text": {
                        "zh_CN": "范围选择时开始日期的占位内容"
                      }
                    },
                    "required": false,
                    "readOnly": false,
                    "disabled": false,
                    "cols": 12,
                    "widget": {
                      "component": "MetaInput",
                      "props": {}
                    },
                    "description": {
                      "zh_CN": "范围选择时开始日期的占位内容"
                    }
                  },
                  {
                    "property": "end-placeholder",
                    "label": {
                      "text": {
                        "zh_CN": "范围选择时结束日期的占位内容"
                      }
                    },
                    "required": false,
                    "readOnly": false,
                    "disabled": false,
                    "cols": 12,
                    "widget": {
                      "component": "MetaInput",
                      "props": {}
                    },
                    "description": {
                      "zh_CN": "范围选择时结束日期的占位内容"
                    }
                  },
                  {
                    "property": "format",
                    "label": {
                      "text": {
                        "zh_CN": "显示在输入框中的格式"
                      }
                    },
                    "required": false,
                    "readOnly": false,
                    "disabled": false,
                    "cols": 12,
                    "widget": {
                      "component": "MetaInput",
                      "props": {}
                    },
                    "description": {
                      "zh_CN": "显示在输入框中的格式"
                    }
                  },
                  {
                    "property": "editable",
                    "label": {
                      "text": {
                        "zh_CN": "文本框可输入"
                      }
                    },
                    "required": false,
                    "readOnly": false,
                    "disabled": false,
                    "defaultValue": true,
                    "cols": 12,
                    "widget": {
                      "component": "MetaSwitch",
                      "props": {}
                    },
                    "description": {
                      "zh_CN": "文本框可输入"
                    },
                    "labelPosition": "left"
                  },
                  {
                    "property": "clearable",
                    "label": {
                      "text": {
                        "zh_CN": "显示清除按钮"
                      }
                    },
                    "required": false,
                    "readOnly": false,
                    "disabled": false,
                    "defaultValue": true,
                    "cols": 12,
                    "widget": {
                      "component": "MetaSwitch",
                      "props": {}
                    },
                    "description": {
                      "zh_CN": "是否显示清除按钮"
                    },
                    "labelPosition": "left"
                  },
                  {
                    "property": "readonly",
                    "label": {
                      "text": {
                        "zh_CN": "只读"
                      }
                    },
                    "required": false,
                    "readOnly": false,
                    "disabled": false,
                    "cols": 12,
                    "widget": {
                      "component": "MetaSwitch",
                      "props": {}
                    },
                    "description": {
                      "zh_CN": "是否只读"
                    },
                    "labelPosition": "left"
                  },
                  {
                    "property": "disabled",
                    "label": {
                      "text": {
                        "zh_CN": "禁用"
                      }
                    },
                    "required": false,
                    "readOnly": false,
                    "disabled": false,
                    "cols": 12,
                    "widget": {
                      "component": "MetaSwitch",
                      "props": {}
                    },
                    "description": {
                      "zh_CN": "是否被禁用"
                    },
                    "labelPosition": "left"
                  }
                ]
              }
            ],
            "events": {
              "onUpdate:modelValue": {
                "label": {
                  "zh_CN": "双向绑定的值改变时触发"
                },
                "description": {
                  "zh_CN": "在值改变时触发"
                },
                "type": "event",
                "functionInfo": {
                  "params": [
                    {
                      "name": "value",
                      "type": "string",
                      "defaultValue": "",
                      "description": {
                        "zh_CN": "双向绑定的值"
                      }
                    }
                  ],
                  "returns": {}
                },
                "defaultValue": ""
              }
            }
          },
          "configure": {
            "loop": true,
            "condition": true,
            "styles": true,
            "isContainer": false,
            "isModal": false,
            "nestingRule": {
              "childWhitelist": "",
              "parentWhitelist": "",
              "descendantBlacklist": "",
              "ancestorWhitelist": ""
            },
            "isNullNode": false,
            "isLayout": false,
            "rootSelector": "",
            "shortcuts": {
              "properties": ["size"]
            },
            "contextMenu": {
              "actions": ["create symbol"],
              "disable": ["copy", "remove"]
            }
          }
        }`

snippets:
`{
              "name": {
                "zh_CN": "时间选择器"
              },
              "icon": "time-picker",
              "screenshot": "",
              "snippetName": "ElTimePicker",
              "schema": {
                "componentName": "ElTimePicker",
                "props": {
                  "modelValue": 1702785160952
                }
              }
            }
`

**Comment by ghost** [comment]
@youchen133 设计器中是依赖给组件上添加的自定义data-uid属性来匹配选中的组件，画布在渲染schema中组件时会给每个组件添加上生成data-uid。ElTimePicker组件看上去是没有接收额外的属性，导致点击画布中组件时，无法匹配到组件。
在element-plus组件库的playground中试验如下。
![image](https://github.com/opentiny/tiny-engine/assets/142570291/a9909d0b-ffc4-4fba-b347-d286988f6423)
源代码如下
![image](https://github.com/opentiny/tiny-engine/assets/142570291/1e46ab4b-1ef9-4de0-aa1a-48c5309ece54)

**Comment by youchen133** [comment]
> @youchen133 设计器中是依赖给组件上添加的自定义data-uid属性来匹配选中的组件，画布在渲染schema中组件时会给每个组件添加上生成data-uid。ElTimePicker组件看上去是没有接收额外的属性，导致点击画布中组件时，无法匹配到组件。 在element-plus组件库的playground中试验如下。 ![image](https://private-user-images.githubusercontent.com/142570291/291591664-a9909d0b-ffc4-4fba-b347-d286988f6423.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMzYxNjEsIm5iZiI6MTcwMzAzNTg2MSwicGF0aCI6Ii8xNDI1NzAyOTEvMjkxNTkxNjY0LWE5OTA5ZDBiLWZmYzQtNGZiYS1iMzQ3LWQyODY5ODhmNjQyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQwMTMxMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNmRmNzQzZDUzMzkxMmI0MDJiZTBiZGNjM2MwNDEwMWZlODk4OTcyYmFjNGIwNzVhYWJjNGIwNWU4MTVhY2FjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ikDZpvTN41iVphv2ipiMzxjYCEDG0KYe37_NWjN-jT4) 源代码如下 ![image](https://private-user-images.githubusercontent.com/142570291/291592677-1e46ab4b-1ef9-4de0-aa1a-48c5309ece54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMzYxNjEsIm5iZiI6MTcwMzAzNTg2MSwicGF0aCI6Ii8xNDI1NzAyOTEvMjkxNTkyNjc3LTFlNDZhYjRiLTFlZjktNGRlMC1hYTFhLTQ4YzUzMDllY2U1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQwMTMxMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODEwMmE4YjFmZDAzYmM3ZDUyNzgxM2M5ODUwYTA5YjNhN2EzNjRmMTkwNThjYThkOWNkOGRkNDlkMzBlODI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n58YFzfbnwu5tlkTWTiqNcyJZelpi3LNzbmbC9mhhng)

那这个有什么好的解决方法吗，或者说低代码引擎是否可以针对这种情况进行处理，我现在的做法是自定义了一个组件，用一个div包住element plus的时间组件来解决的，属性进行透传

**Comment by ghost** [comment]
这个问题我们记录下来，找下解决方案。你的这个解决方案想法很好，我们也会借鉴。

**Comment by youchen133** [comment]
> 这个问题我们记录下来，找下解决方案。你的这个解决方案想法很好，我们也会借鉴。

好的，我后面也继续看看有没有其他方案
