### ISSUE TITLE
🐛 [Bug]: 复制静态文件时接口报错

### ISSUE THREAD

**Issue by zhangmingliang930309** [opentiny/tiny-engine#169]
### Environment

QQ浏览器11.1 (5155) Chromium94.0.4606.71  IE11.3636.19041.0

### Version

v16.20.0

### Version

tiny-engine@ D:\其他项目\tiny-engine  empty

### Link to minimal reproduction

https://github.com/opentiny/tiny-engine/

### Step to reproduce

![微信图片_20231218102232](https://github.com/opentiny/tiny-engine/assets/42395614/22b84311-b3f4-4e8f-813b-3bf616539041)
![微信图片_202312181022321](https://github.com/opentiny/tiny-engine/assets/42395614/73823c59-1f69-4fc8-b3f9-124f6d148b95)

**Comment by lizhijie429** [comment]
由于复制的静态文件的schema中包含了id及_id两个字段，因此在提交时由于数据库中已经存在所以报错导致提交失败。
