### ISSUE TITLE
希望官方大佬们帮出一个怎么写左侧组件以及右侧组件属性配置示例代码完整教程

### ISSUE THREAD

**Issue by bingge2008** [opentiny/tiny-engine#17]
通过组件扩展示例代码，一步一步代码的讲解，让我们可以跟着做下来，能在低代码平台上运行的，这样便于理解。谢谢了！

**Comment by xiaopenyoua** [comment]
文档相当于零，很多功能还没法使用，

**Comment by wenmine** [comment]
@xiaopenyoua @bingge2008 hi，我们更新了 [用户手册](https://opentiny.design/tiny-engine#/help-center/course/engine)  在官网，希望能够帮助到你~
