### ISSUE TITLE
🐛 [Bug]: 引入第三方插件elementplus报错，按照文档在bundle.json中配置了element-plus的相关组件，但是在渲染的时候报错“Failed to resolve module specifier "vue". Relative references must start with either "/", "./", or "../"

### ISSUE THREAD

**Issue by traveler-h** [opentiny/tiny-engine#179]
### Environment

window11

### Version

node20

### Version

lasted

### Link to minimal reproduction

{
          "id": 2,
          "version": "2.4.4",
          "name": {
            "zh_CN": "按钮"
          },
          "component": "ElButton",
          "icon": "button",
          "description": "常用的操作按钮",
          "doc_url": "",
          "screenshot": "",
          "tags": "",
          "keywords": "",
          "dev_mode": "proCode",
          "npm": {
            "package": "element-plus",
            "version": "2.4.4",
            "script": "https://unpkg.com/element-plus@2.4.4/dist/index.full.mjs",
            "css": "https://unpkg.com/element-plus@2.4.4/dist/index.css",
            "dependencies": null,
            "exportName": "ElButton"
          },
          "group": "基础组件",
          "category": "element-plus",
          "configure": {
            "loop": true,
            "condition": true,
            "styles": true,
            "isContainer": false,
            "isModal": false,
            "isPopper": false,
            "nestingRule": {
              "childWhitelist": "",
              "parentWhitelist": "",
              "descendantBlacklist": "",
              "ancestorWhitelist": ""
            },
            "isNullNode": false,
            "isLayout": false,
            "rootSelector": "",
            "shortcuts": {
              "properties": ["type", "size"]
            },
            "contextMenu": {
              "actions": ["copy", "remove", "insert", "updateAttr", "bindEevent", "createBlock"],
              "disable": []
            },
            "invalidity": [""],
            "clickCapture": true,
            "framework": "Vue"
          },
          "schema": {
            "properties": [
              {
                "name": "0",
                "label": {
                  "zh_CN": "基础属性"
                },
                "content": [
                  {
                    "property": "size",
                    "label": {
                      "text": {
                        "zh_CN": "size"
                      }
                    },
                    "description": {
                      "zh_CN": "尺寸"
                    },
                    "required": true,
                    "readOnly": false,
                    "disabled": false,
                    "cols": 12,
                    "labelPosition": "top",
                    "type": "string",
                    "defaultValue": "default",
                    "widget": {
                      "component": "MetaSelect",
                      "props": {
                        "options": [
                          {
                            "label": "large",
                            "value": "large"
                          },
                          {
                            "label": "default",
                            "value": "default"
                          },
                          {
                            "label": "small",
                            "value": "small"
                          }
                        ]
                      }
                    }
                  },
                  {
                    "property": "type",
                    "label": {
                      "text": {
                        "zh_CN": "type"
                      }
                    },
                    "description": {
                      "zh_CN": "类型"
                    },
                    "required": true,
                    "readOnly": false,
                    "disabled": false,
                    "cols": 12,
                    "labelPosition": "top",
                    "type": "string",
                    "widget": {
                      "component": "MetaInput",
                      "props": {}
                    }
                  }
                ],
                "description": {
                  "zh_CN": ""
                }
              }
            ],
            "events": {},
            "slots": {
              "default": {
                "label": {
                  "zh_CN": "default"
                },
                "description": {
                  "zh_CN": "自定义默认内容"
                }
              },
              "loading": {
                "label": {
                  "zh_CN": "loading"
                },
                "description": {
                  "zh_CN": "自定义加载中组件"
                }
              }
            }
          }
        },

### Step to reproduce

npm run dev
控制台报错：Uncaught (in promise) TypeError: Failed to resolve module specifier "vue". Relative references must start with either "/", "./", or "../".

**Comment by chilingling** [comment]
@traveler-h 无法复现，请提供更详细的复现步骤与细节

**Comment by traveler-h** [comment]
https://github.com/opentiny/tiny-engine/assets/56715535/ef3a3180-6058-414c-936b-1665edbf1715

**Comment by traveler-h** [comment]
视频是在拉取了develop最新代码之后的操作 未做任何的修改 @chilingling

**Comment by chilingling** [comment]
> 视频是在拉取了develop最新代码之后的操作 未做任何的修改 @chilingling

1. 方便提供一下终端的截图吗？有没有报错？启动命令在哪个目录执行的？
2. 可以试试使用 pnpm，看看会不会有报错，我们这边使用的是 pnpm 来管理依赖的

**Comment by traveler-h** [comment]
是使用pnpm安装依赖的
启动命令在tiny-engine下执行的
截图如下：
![1703233125943](https://github.com/opentiny/tiny-engine/assets/56715535/8725cf67-88d9-4e7f-a7f8-a375ef24cc57)
![1703233145013](https://github.com/opentiny/tiny-engine/assets/56715535/046fe514-c0ca-4ce2-b8c1-1997cdd8024a)
![1703233171646](https://github.com/opentiny/tiny-engine/assets/56715535/24550ebf-980f-45b9-acc5-af2b4f2228ea)
@chilingling

**Comment by chilingling** [comment]
复现了，感谢反馈 @traveler-h
