### ISSUE TITLE
🐛 [Bug]: Edit the code after saving, perform other operations, come back to edit the code, the previous code disappeared.

### ISSUE THREAD

**Issue by WangJueStar** [opentiny/tiny-engine#181]
### Environment

develop

### Version

latest

### Version

latest

### Link to minimal reproduction

none

### Step to reproduce

![1](https://github.com/opentiny/tiny-engine/assets/38129014/8edf7dbf-64d7-4c2c-8e6b-11f03dc5f1e8)
first: input code。
![2](https://github.com/opentiny/tiny-engine/assets/38129014/429c79b5-1fc7-4db2-a349-4c97f3178743)
seconde: close this dialog and do other thing.
![3](https://github.com/opentiny/tiny-engine/assets/38129014/16203be0-70e4-4935-85f0-b8777a09d08a)
third: return to the previous dialog, which is empty.

### What is expected

be solved

**Comment by ghost** [comment]
@WangJueStar After you enter a code in the code editing box, click "保存" to save the code. If you click  "取消" or close the dialog, the code will not be saved.
![image](https://github.com/opentiny/tiny-engine/assets/142570291/ed6051de-9ca4-44a6-9e41-816128f64c76)
