### ISSUE TITLE
🐛 [Bug]: 添加数据源时，如果接口参数值是动态的，即如果是个变量，应该怎么配置？

### ISSUE THREAD

**Issue by cnbin** [opentiny/tiny-engine#183]
### Environment

谷歌浏览器

### Version

17

### Version

3.10.11

### Link to minimal reproduction

 添加数据源时，如果接口参数值是个变量，即参数值是动态的，应该怎么配置？

### Step to reproduce

 添加数据源时，如果接口参数值是个变量，即参数值是动态的，应该怎么配置？

### What is expected

 添加数据源时，如果接口参数值是个变量，也能够在线配置绑定
![222](https://github.com/opentiny/tiny-engine/assets/8576832/b896263f-7977-45bd-ad09-47f5052cbc7e)

**Comment by ghost** [comment]
配置请求处理函数
![image](https://github.com/opentiny/tiny-engine/assets/142570291/7ff9534f-d689-4ca5-a56c-113ae6c55fe0)

**Comment by wenmine** [comment]
@cnbin

**Comment by cnbin** [comment]
我请教一下，这里willfetch参数除了用localStorage缓存方式将页面变量值传到数据源这里。还有其他走内存方式吗？我这里用不了this.state.xxx变量。就数据源跟页面是解耦的，但数据交互时，要怎么把页面变量值通过内存方式传到数据源？
![CASCLingXPC_17034930435706](https://github.com/opentiny/tiny-engine/assets/8576832/e3e1ba92-2bf0-49a8-9dbb-3a02b0759d91)

**Comment by Thea1211** [comment]
这个问题有解决吗  @yaoyun8

**Comment by ghost** [comment]
@cnbin @Thea1211 目前是不支持的。willFetch是应用级的配置，获取页面数据也不太合理。

**Comment by Thea1211** [comment]
但是参数是变量几乎是所有场景呢

**Comment by ghost** [comment]
好的，谢谢反馈。该问题会收纳到需求池里，根据优先级规划版本修改。
