### ISSUE TITLE
🐛 [Bug]: id is not binding

### ISSUE THREAD

**Issue by 350020527** [opentiny/tiny-engine#187]
### Environment

edge

### Version

latest

### Version

latest

### Link to minimal reproduction

id is not binding

### Step to reproduce

![image](https://github.com/opentiny/tiny-engine/assets/5964358/14147c52-de6c-447d-91ba-1450efa85127)

**Comment by wenmine** [comment]
非bug，这两个id是不同的含义。一个是设计器自己对每个shema设定的内部id，一个是前端含义上元素的id。不是同个东西
