### ISSUE TITLE
🐛 [Bug]: CanvasRowColContainer.vue组件 拖拽后预览时报找不到标签

### ISSUE THREAD

**Issue by ai4code** [opentiny/tiny-engine#19]
### Environment

nodejs v18.18.0 

### Version

latest

### Version

latest

### Link to minimal reproduction

about:srcdoc:160 [Vue warn]: Failed to resolve component: canvas-col
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <Main> 
  at <Repl>
console.<computed> @ about:srcdoc:160
about:srcdoc:160 [Vue warn]: Failed to resolve component: canvas-row
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <Main> 
  at <Repl>
console.<computed> @ about:srcdoc:160
about:srcdoc:160 [Vue warn]: Failed to resolve component: canvas-row-col-container
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <Main> 
  at <Repl>

### Step to reproduce

CanvasRowColContainer.vue component cannot find the label when previewing after dragging

**Comment by ai4code** [comment]
能不能拉下进群

**Comment by chilingling** [comment]
已知问题，修复中，感谢反馈。

Known issue, fix in progress, thanks for the feedback.
