### ISSUE TITLE
 🐛 [Bug]: 在插件面板是固定状态下关闭插件面板，再次打开插件面板，设计区域没有自适应

### ISSUE THREAD

**Issue by traveler-h** [opentiny/tiny-engine#191]
### Environment

window11

### Version

node20

### Version

lasted

### Link to minimal reproduction

在插件面板是固定状态下关闭插件面板，再次打开插件面板，设计区域没有自适应

### Step to reproduce

https://github.com/opentiny/tiny-engine/assets/56715535/9d540637-55a0-4c32-a9b8-a0be1ab56336

**Comment by ghost** [comment]
@traveler-h 未复现该问题，请更新最新代码后再尝试能否复现

**Comment by traveler-h** [comment]
@yaoyun8  拉取最新代码后未见修复（屏幕是1920px）

https://github.com/opentiny/tiny-engine/assets/56715535/7978a9b0-7390-41cf-a60c-3e40a439935e

**Comment by ghost** [comment]
@traveler-h 已修复
