### ISSUE TITLE
🐛 [Bug]: 树形组件在设计模式里不显示插槽中组件

### ISSUE THREAD

**Issue by coolphk** [opentiny/tiny-engine#192]
### Environment

chrome

### Version

16

### Version

latest

### Link to minimal reproduction

无

### Step to reproduce

页面schema:
`{
  "state": {},
  "methods": {},
  "componentName": "Page",
  "fileName": "DemoPage",
  "css": "",
  "props": {},
  "lifeCycles": {},
  "children": [
    {
      "componentName": "TinyTree",
      "props": {
        "data": [
          {
            "label": "一级 1",
            "children": [
              {
                "label": "二级 1",
                "children": [
                  {
                    "label": "三级 1"
                  },
                  {
                    "label": "三级 2"
                  }
                ]
              },
              {
                "label": "二级 2"
              }
            ]
          },
          {
            "label": "一级 2"
          }
        ]
      },
      "children": [
        {
          "componentName": "template",
          "props": {
            "slot": {
              "name": "default",
              "params": [
                "node"
              ]
            }
          },
          "children": [
            {
              "componentName": "TinyInput",
              "props": {
                "modelValue": {
                  "type": "JSExpression",
                  "value": "node.data.label",
                  "model": true
                }
              },
              "id": "123e4d24"
            }
          ],
          "id": "54642a46"
        }
      ],
      "id": "63562414"
    }
  ],
  "dataSource": {
    "list": []
  },
  "bridge": {
    "imports": []
  },
  "inputs": [],
  "outputs": []
}`
设计模式截图
![1703558188456](https://github.com/opentiny/tiny-engine/assets/16846896/9d43f02c-5f2c-4050-806c-6cdc084154af)
预览模式截图
![image](https://github.com/opentiny/tiny-engine/assets/16846896/75891e39-0528-45a1-8f36-b88eec95ea69)
另外在预览模式中树形组件的导航箭头缩进有问题。

### What is expected

期待修复

**Comment by ghost** [comment]
@coolphk 页面schema中插槽对应的componentName应该是"Template"
