### ISSUE TITLE
🐛 [Bug]: 右侧面板，选择背景图/渐变，这里滚动条点击没法拖动；背景图这里的选择图片按钮也是点了没反应

### ISSUE THREAD

**Issue by cnbin** [opentiny/tiny-engine#193]
### Environment

谷歌浏览器

### Version

17

### Version

3.11

### Link to minimal reproduction

右侧面板，选择背景图/渐变，这里滚动条没法拖动

### Step to reproduce

右侧面板，选择背景图/渐变，这里滚动条没法拖动

### What is expected

![CASCLingXPC_17035720418468](https://github.com/opentiny/tiny-engine/assets/8576832/b4b666e9-8c05-403b-82f3-15f1bea3c890)
![CASCLingXPC_17035720706335](https://github.com/opentiny/tiny-engine/assets/8576832/23afce2c-3171-4f7f-ab61-9d2cf67c86f4)
右侧面板，选择背景图/渐变，滚动条点击能正常拖动

**Comment by ghost** [comment]
谢谢反馈。该问题会收纳到需求池里，根据优先级规划版本修改。

**Comment by kedenLi** [comment]
滚动条点击没法拖动这个问题我们近期会处理修复，问题二涉及到了图片上传，需要自行实现文件上传服务相关哦。

**Comment by cnbin** [comment]
好的，谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 紫云蓝龙啊 ***@***.***&gt;
发送时间: 2024年2月6日 16:08
收件人: opentiny/tiny-engine ***@***.***&gt;
抄送: cnbin ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [opentiny/tiny-engine] �� [Bug]: 右侧面板，选择背景图/渐变，这里滚动条点击没法拖动；背景图这里的选择图片按钮也是点了没反应 (Issue #193)





 
滚动条点击没法拖动这个问题我们近期会处理修复，问题二涉及到了图片上传，需要自行实现文件上传服务相关哦。
