### ISSUE TITLE
✨ [Feature]: 帮忙看一下预览的时候，如何能够正常加载展示element plus的icon组件

### ISSUE THREAD

**Issue by youchen133** [opentiny/tiny-engine#199]
### What problem does this feature solve

<img width="1103" alt="image" src="https://github.com/opentiny/tiny-engine/assets/27907927/05650f99-fe9a-4ce3-874d-01a8bdb2c2f7">
预览的时候报错显示icon组件模块没找到，去官方演练场试了一下报了一样的错误
<img width="1368" alt="image" src="https://github.com/opentiny/tiny-engine/assets/27907927/348d8543-52bf-45f7-971c-ec713aedea98">
{
  "imports": {
    "vue": "https://play.vuejs.org/vue.runtime.esm-browser.prod.js",
    "vue/server-renderer": "https://play.vuejs.org/server-renderer.esm-browser.js",
    "element-plus": "https://unpkg.com/element-plus",
    "@element-plus/icons-vue": "https://unpkg.com/@element-plus/icons-vue"
  }
}
<img width="1009" alt="image" src="https://github.com/opentiny/tiny-engine/assets/27907927/4c79d153-c196-489b-b697-9242553bcbea">

### What does the proposed API look like

预览的时候能正常加载展示element plus icon组件

**Comment by ghost** [comment]
@youchen133 element-plus的icon组件需要全局注册，可以在App.vue增加注册处理。
![image](https://github.com/opentiny/tiny-engine/assets/142570291/b306d24e-7565-4de6-ac2f-b32055187482)

**Comment by youchen133** [comment]
> @youchen133 element-plus的icon组件需要全局注册，可以在App.vue增加注册处理。 ![image](https://private-user-images.githubusercontent.com/142570291/293327802-b306d24e-7565-4de6-ac2f-b32055187482.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MDE3NjEsIm5iZiI6MTcwNDgwMTQ2MSwicGF0aCI6Ii8xNDI1NzAyOTEvMjkzMzI3ODAyLWIzMDZkMjRlLTc1NjUtNGRlNi1hYzJmLWIzMjA1NTE4NzQ4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQxMTU3NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzNiZDAzMDI0NGVkMzgwNTU4NTllYzI0NzUyN2VlNGE0ZTczNDM3NTY2ZGMxNzNkMWI3MjQ4ZGUxYmM0MmI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uLCeJOOwSnygEiFfMPAHN2etCmhPDCck0lNwpnbH5-8)


我在preview/src/main.js文件里全局引入了'@element-plus/icons-vue'，但还是在预览的时候没有正常渲染
```
import { createApp } from 'vue'
import initSvgs from '@opentiny/tiny-engine-svgs'
import App from './App.vue'
import 'virtual:svg-icons-register'
import ElementPlus from 'element-plus'
import * as ElementPlusIconsVue from '@element-plus/icons-vue'

const app = createApp(App).use(ElementPlus)

initSvgs(app)
for (const [key, component] of Object.entries(ElementPlusIconsVue)) {
  app.component(key, component)
}
app.mount('#app')
```
<img width="1525" alt="image" src="https://github.com/opentiny/tiny-engine/assets/27907927/d20396d3-ea9b-4171-b1c4-7bf0fc88643e">

**Comment by ghost** [comment]
@youchen133  你的cdn地址拿到的不是esm格式的，换这个可用：https://unpkg.com/@element-plus/icons-vue@2.3.1/dist/index.js
可以把icon当做组件引入，和引入第三方组件一样
![image](https://github.com/opentiny/tiny-engine/assets/142570291/35a40a0e-f54e-4ace-922d-210f3c7dcce3)
