### ISSUE TITLE
lowcode-dsl-vue - Not found

### ISSUE THREAD

**Issue by locoy** [opentiny/tiny-engine#2]
tiny-engine\mockServer> npm install
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@opentiny%2flowcode-dsl-vue - Not found

**Comment by wenmine** [comment]
Hi, please update the develop code to the latest. We have fixed this issue.

**Comment by note520** [comment]
tiny-engine-dsl-vue 包会开源吗？
