### ISSUE TITLE
🐛 [Bug]: 示例中的选择框无法选中

### ISSUE THREAD

**Issue by bingge2008** [opentiny/tiny-engine#20]
### Environment

Google Chrome 117.0.5938.92, window 10

### Version

v16.18.0

### Version

1.0.0

### Link to minimal reproduction

示例中的选择框无法选中，设置此组件的右侧属性
![1](https://github.com/opentiny/tiny-engine/assets/40852276/88d675bb-ea75-46af-b1f8-055a00d67e71)

示例中的输入框可以选中，设置此组件的右侧属性
![2](https://github.com/opentiny/tiny-engine/assets/40852276/edfe4e83-ca46-4f7c-80ed-900e68a48e0d)

### Step to reproduce

刚初始化项目，打开官方提供的示例页面，左侧插件--》页面管理--》静态页面--》createVm

### What is expected

修正此bug

**Comment by ghost** [comment]
重新执行 pnpm i，可以看一下pnpm-lock.yaml下的@opentiny/vue-select版本是否为3.10.1及以上，若不是，可使用pnpm手动更新依赖@opentiny/vue@3.10.1
@bingge2008

**Comment by bingge2008** [comment]
OK
