### ISSUE TITLE
🐛 [Bug]: 新增工具类，选择Function类型后，关闭后，再继续点击新增，这里显示内容变成Npm的填写项

### ISSUE THREAD

**Issue by cnbin** [opentiny/tiny-engine#202]
### Environment

谷歌浏览器

### Version

17

### Version

3.11

### Link to minimal reproduction

新增工具类，选择Function类型后，关闭后，再继续点击新增，这里显示内容变成Npm的填写项

### Step to reproduce

新增工具类，选择Function类型后，关闭后，再继续点击新增，这里显示内容变成Npm的填写项
![123](https://github.com/opentiny/tiny-engine/assets/8576832/b5cd2be2-7c58-4c70-9c2b-fba12bf0bf2f)

### What is expected

新增工具类，选择Function类型后，关闭后，再继续点击新增，这里显示内容应显示function的填写项

**Comment by ghost** [comment]
修复中
