### ISSUE TITLE
✨ [Feature]: design core 添加element-plus 不支持importmap引入吗 

### ISSUE THREAD

**Issue by Thea1211** [opentiny/tiny-engine#203]
### What problem does this feature solve

design core 添加element-plus 不支持importmap引入吗 必须要npm安装使用吗

### What does the proposed API look like

design core 添加element-plus 不支持importmap引入吗 必须要npm安装使用吗

**Comment by ghost** [comment]
@Thea1211 请描述下具体需求，是要在画布中使用element-plus组件吗？可以参考：[如何引入第三方组件库](https://opentiny.design/tiny-engine#/help-center/course/engine/15)

**Comment by Thea1211** [comment]
![image](https://github.com/opentiny/tiny-engine/assets/24974566/429a6e26-84d4-405d-ada3-252ca9b18dfa)
dedesign-core package下 vite里面配了importmap 还是需要在package.json里面添加组件安装 才能用的吗

**Comment by ghost** [comment]
importmap只能解决依赖，要在画布中渲染组件还需要引入依赖，处理组件。要在画布中使用element-plus组件，可以参考：[如何引入第三方组件库](https://opentiny.design/tiny-engine#/help-center/course/engine/15)
