### ISSUE TITLE
🐛 [Bug]: 在设计器中新增的i18n配置，在预览和导出时都没有生效

### ISSUE THREAD

**Issue by traveler-h** [opentiny/tiny-engine#204]
### Environment

window11

### Version

node20

### Version

lasted

### Link to minimal reproduction

https://github.com/opentiny/tiny-engine/

### Step to reproduce

![微信图片_20231228172814](https://github.com/opentiny/tiny-engine/assets/56715535/861dbb55-7623-48a4-9c26-6cccbb3630cc)
![微信图片_20231228172820](https://github.com/opentiny/tiny-engine/assets/56715535/dca38666-44c3-4cd2-bbbf-537970d5c94e)
![微信图片_20231228172824](https://github.com/opentiny/tiny-engine/assets/56715535/435b3112-a9d8-4256-be00-45b5b4a0f24b)

**Comment by ghost** [comment]
@traveler-h 国际化词条属于应用级别的数据，mockServer目前没有对应用数据的修改做保存，所以添加的词条需要手动添加到json文件中：mockServer\src\services\appinfo.json
