### ISSUE TITLE
🐛 [Bug]: TinyButtonGroup中添加数据项后，渲染错乱

### ISSUE THREAD

**Issue by bingge2008** [opentiny/tiny-engine#21]
### Environment

Google Chrome 117.0.5938.92, window 10

### Version

v16.18.0

### Version

tiny-engine latest

### Link to minimal reproduction

TinyButtonGroup中添加数据项后，渲染错乱：

<img width="1455" alt="1" src="https://github.com/opentiny/tiny-engine/assets/40852276/da97a916-4bc9-4e33-a0be-44f127d50c1f">
<img width="1342" alt="2" src="https://github.com/opentiny/tiny-engine/assets/40852276/948993ed-1170-4250-8679-a273c42cb46c">
<img width="1466" alt="3" src="https://github.com/opentiny/tiny-engine/assets/40852276/01e3506a-ef4f-4769-94e2-4061f0edfee5">

### Step to reproduce

希望官方解决一下

**Comment by zhatongning** [comment]
看了一下，原因是编辑之后emit出了一个json，这个json没有parse直接传入了ButtonGroup。怎么改的话，代码太多了，没时间太仔细看。

**Comment by wenmine** [comment]
@
