### ISSUE TITLE
🐛 [Bug]: 表单组件的Type类型不全，Input组件无法绑定值

### ISSUE THREAD

**Issue by ChrisLo0751** [opentiny/tiny-engine#212]
### Environment

Edge, Windows11

### Version

v18.16.0

### Version

latest

### Link to minimal reproduction

暂无

### Step to reproduce

表单组件默认的Input类型只有三种，如下图所示：

![图片](https://github.com/opentiny/tiny-engine/assets/73991742/c545940d-5ae1-46ab-ae17-5ee13d823b9d)

单独拉拽Input组件，有以下几种类型：

![图片](https://github.com/opentiny/tiny-engine/assets/73991742/0e6d0ad4-a0f4-4646-8bd9-29cc3bb97987)

明明是通用的组件，表单组件做了一层封装，反而失去了这些类型，举个最常见的number类型，在表单提交的值类型中，也算是比较常见的，结果现在不能用

然后第二个非常奇怪的地方是，Input组件貌似没有绑定如 v-model 的地方，而表单的组件是有这个值的

表单组件中Input的值绑定，专门提供了modelValue

![图片](https://github.com/opentiny/tiny-engine/assets/73991742/fdc02575-9f9e-4525-8404-a4436c0ede38)

而 Input 组件貌似没有

![图片](https://github.com/opentiny/tiny-engine/assets/73991742/f5c985be-09cc-47c2-b74d-b8f3a251a9c5)

请问这算bug吗 

### What is expected

1、表单组件的Input支持多种类型
2、Input组件的值绑定应该默认存在

### What is actually happening

1、表单组件的input仅支持三类文本类型值：text , textarea, password
2、Input组件不能绑定值

**Comment by ghost** [comment]
@ChrisLo0751 组件的属性配置都在物料资产包中，扩展属性是完全开放的，遵循物料协议，可以添加任意组件支持的属性。
[物料资产包协议](https://opentiny.design/tiny-engine#/protocol)
[如何在设计器中引入第三方组件库](https://opentiny.design/tiny-engine#/help-center/course/engine/15)
