### ISSUE TITLE
🐛 [Bug]: 点击可选区块列表刚才发布的区块，移动到右侧已选区块列表，点击保存报错

### ISSUE THREAD

**Issue by Thea1211** [opentiny/tiny-engine#213]
### Environment

chrome

### Version

v16.14.0

### Version

latest

### Link to minimal reproduction

启动后端

### Step to reproduce

![image](https://github.com/opentiny/tiny-engine/assets/24974566/aba41e7d-d00a-4d0d-8c22-4f71b961dbf6)
![image](https://github.com/opentiny/tiny-engine/assets/24974566/acdd7d23-6e48-4de9-978f-40a1cfe60ccc)
![image](https://github.com/opentiny/tiny-engine/assets/24974566/c8b41e5e-e0f5-408a-99aa-1caec7b9bc0e)

**Comment by wenmine** [comment]
@Thea1211 可以检查一下你这个区块的version格式，是不是不满足我们的规范，规范内容具体在：webservice仓库里的common.ts。

**Comment by Thea1211** [comment]
![image](https://github.com/opentiny/tiny-engine/assets/24974566/dd5732b6-703c-4990-87cd-a45d940fc108)
走了两遍 第一次是空

**Comment by lu-yg** [comment]
是前端走了两次请求接口，还是后端走了两次校验，可以复现吗

**Comment by Thea1211** [comment]
就是在webservice仓库里的common.ts加的log 每次想把Block加载物料都有这个错

**Comment by Thea1211** [comment]
都走了一遍 就是validate了两次

**Comment by Thea1211** [comment]
是portalhome这个version是空的 把他删掉就可以添加成功了

**Comment by Thea1211** [comment]
区块的发布是不是只是可以被消费 没办法npm install使用的？

**Comment by Thea1211** [comment]
WARN 26304 [ClusterClient:Connection] socket is closed by other side while there were still unhandled data in the socket buffer
block发布还会有这个错 然后发布不了

**Comment by lu-yg** [comment]
portalhome这个区块是样板区块，无法使用，可以删除，区块发布报错，请看下是在那个环节报错，看下task任务走到哪里了，有没有具体报错信息，WARN 26304 [ClusterClient:Connection] socket is closed by other side while there were still unhandled data in the socket buffer这个报错非区块发布报错

**Comment by Thea1211** [comment]
deploy 会500是为什么的  Host 'DESKTOP-VA851AG' is not allowed to connect to this MySQL server 有个这个问题
