### ISSUE TITLE
🐛 [Bug]: 组件属性面板区不展示其对应的样式！

### ISSUE THREAD

**Issue by libinworks** [opentiny/tiny-engine#224]
### Environment

最新chrome浏览器

### Version

18.16.0

### Version

最新的

### Link to minimal reproduction

![9b831a56e29df5a3c137e795fe2dfd4](https://github.com/opentiny/tiny-engine/assets/32322189/3911c032-7095-4ebd-92a1-bacffbea1573)

### Step to reproduce

pull项目的最新代码，本地启动，界面默认展示的schema布局中，选中页面的第一个div，在组件属性面板区不展示其对应的样式！

**Comment by chilingling** [comment]
新特性导致，新特性中，样式面板不会展示行内样式，只会展示样式选择器中选中的样式。近期会补充文档，感谢反馈

**Comment by lizhijie429** [comment]
![image](https://github.com/opentiny/tiny-engine/assets/7768535/8c743902-b4a4-49ea-a71e-410b198854d3)
