### ISSUE TITLE
🐛 [Bug]: 缺少cdn地址

### ISSUE THREAD

**Issue by qian-chen97** [opentiny/tiny-engine#226]
### Environment

windwos11

### Version

16

### Version

最新

### Link to minimal reproduction

![image](https://github.com/opentiny/tiny-engine/assets/46392918/068ed33e-ed73-4294-9a72-f311bc05c202)

### Step to reproduce

-

**Comment by ghost** [comment]
@ArtisanQ 拉取最新develop分支代码，未复现

**Comment by chilingling** [comment]
@ArtisanQ 请问能提供详细复现步骤吗？当前没有复现
