### ISSUE TITLE
🐛 [Bug]: TinyTooltip组件拖入画板以后无法直接在画板中选中该组件，只能通过大纲树选中

### ISSUE THREAD

**Issue by youchen133** [opentiny/tiny-engine#232]
### Environment

mac

### Version

16

### Version

latest

### Link to minimal reproduction

无

### Step to reproduce

TinyTooltip组件拖入画板以后无法直接在画板中选中该组件，只能通过大纲树选中，其他反馈组件也一样

**Comment by ghost** [comment]
@youchen133 也可以在画布下方的面包屑中选中父节点或祖节点。是否能满足需求？
