### ISSUE TITLE
🐛 [Bug]: 函数出码之后放在wrap里面 就没办法使用nexttick()

### ISSUE THREAD

**Issue by Thea1211** [opentiny/tiny-engine#242]
### Environment

chrome

### Version

v16.14.0

### Version

latest

### Link to minimal reproduction

https://github.com/opentiny/tiny-engine

### Step to reproduce

![image](https://github.com/opentiny/tiny-engine/assets/24974566/6eb03c46-367c-44dd-9b9a-e371dd699cdb)
loading 是可以加载 但是会有这个报错
![image](https://github.com/opentiny/tiny-engine/assets/24974566/f66dcdf5-6897-42a6-b6d6-d4b749d91a71)

**Comment by ghost** [comment]
@Thea1211 this上可使用的属性/方法可以在lowcode.js中查看，如果要使用vue解构出来的一些属性/方法，可以直接使用vue.xxx。
![image](https://github.com/opentiny/tiny-engine/assets/142570291/5436bec7-a7f6-4693-9a8e-014cb0d433e1)

**Comment by Thea1211** [comment]
试了貌似都不行

**Comment by ghost** [comment]
@Thea1211 把页面schema贴一下看看

**Comment by Thea1211** [comment]
{
  "state": {},
  "methods": {
    "onClickNew": {
      "type": "JSFunction",
      "value": "function onClickNew(event) {\n  const loadingInstance = this.utils.loading.service({ fullscreen: true })\n  console.log('this', this, this.nextTick())\n  this.nextTick(() => {\n    // Loading should be closed asynchronously\n    loadingInstance.close()\n  })\n}"
    }
  },
  "componentName": "Page",
  "css": "",
  "props": {},
  "lifeCycles": {},
  "children": [
    {
      "componentName": "ElButton",
      "props": {
        "onClick": {
          "type": "JSExpression",
          "value": "this.onClickNew"
        }
      },
      "children": [
        {
          "componentName": "Text",
          "props": {
            "text": "按钮文本"
          },
          "id": "2d53695e"
        }
      ],
      "id": "ea234c25"
    }
  ],
  "dataSource": {
    "list": []
  },
  "utils": [],
  "bridge": [],
  "inputs": [],
  "outputs": [],
  "fileName": "Untitled"
}

![image](https://github.com/opentiny/tiny-engine/assets/24974566/b95d73c1-c78d-4a0b-b88c-c8266e732f4d)

在wrap里面返回了 nexttick也不行

**Comment by ghost** [comment]
@Thea1211 使用vue.nextTick

**Comment by Thea1211** [comment]
试过不行

**Comment by ghost** [comment]
![image](https://github.com/opentiny/tiny-engine/assets/142570291/fc80c2f0-008c-410a-b178-00837d7500f5)

{
  "state": {},
  "methods": {
    "onClickNew": {
      "type": "JSFunction",
      "value": "function onClickNew(event) {\n  const loadingInstance = this.utils.loading.service({ fullscreen: true })\n  console.log('this', this, this.nextTick())\n  vue.nextTick(() => {\n    // Loading should be closed asynchronously\n    loadingInstance.close()\n  })\n}"
    }
  },
  "componentName": "Page",
  "css": "",
  "props": {},
  "lifeCycles": {},
  "children": [
    {
      "componentName": "ElButton",
      "props": {
        "onClick": {
          "type": "JSExpression",
          "value": "this.onClickNew"
        }
      },
      "children": [
        {
          "componentName": "Text",
          "props": {
            "text": "按钮文本"
          },
          "id": "2d53695e"
        }
      ],
      "id": "ea234c25"
    }
  ],
  "dataSource": {
    "list": []
  },
  "utils": [],
  "bridge": [],
  "inputs": [],
  "outputs": [],
  "fileName": "Untitled"
}

**Comment by Thea1211** [comment]
![image](https://github.com/opentiny/tiny-engine/assets/24974566/d254a9fa-b8d1-4965-904f-4937ec248c43)
这个这个loading就出不来了

**Comment by ghost** [comment]
loading是utils里的，appinfo.json里是否有这个函数

**Comment by Thea1211** [comment]
现在是放在那个模板工程里面测得 也需要吗

**Comment by ghost** [comment]
nextTick的问题是否已解决？
请确认loading函数是否正常加载了，可以在预览的class="left"中查看（取消display：none属性）
![image](https://github.com/opentiny/tiny-engine/assets/142570291/605f0aba-a413-4957-9731-e1f28c884360)

**Comment by Thea1211** [comment]
并没有 你那边可以出来？

**Comment by ghost** [comment]
`{
  "state": {},
  "methods": {
    "onClickNew": {
      "type": "JSFunction",
      "value": "function onClickNew(event) {\n  vue.nextTick(() => {\n    console.log(123)\n  })\n}"
    }
  },
  "componentName": "Page",
  "fileName": "Untitled",
  "css": "",
  "props": {},
  "lifeCycles": {},
  "children": [
    {
      "componentName": "button",
      "props": {
        "onClick": {
          "type": "JSExpression",
          "value": "this.onClickNew"
        }
      },
      "children": [
        {
          "componentName": "Text",
          "props": {
            "text": "按钮文案"
          },
          "id": "16561243"
        }
      ],
      "id": "52622626"
    }
  ],
  "dataSource": {
    "list": []
  },
  "bridge": {
    "imports": []
  },
  "inputs": [],
  "outputs": []
}`

把代码这边打开，查看Main.vue，可以看到页面源代码
![image](https://github.com/opentiny/tiny-engine/assets/142570291/5e5ac8e3-3169-4bee-8455-92a157f377ef)

**Comment by Thea1211** [comment]
没有用element的loading吗 可以试下这个

**Comment by ghost** [comment]
这和loading无关，nextTick是从vue解构出来的方法，页面出码的时候会把vue导入，在setup中都可以使用。
loading函数的问题可以从utils中查看

**Comment by Thea1211** [comment]
我把nexttick换成 promise.then也会有一个error, promise.then is not afunction

**Comment by Thea1211** [comment]
{
  "state": {},
  "methods": {
    "onClickNew": {
      "type": "JSFunction",
      "value": "function onClickNew(event) {\n  this.loadingInstance = this.utils.loading.service({\n    text: '加载中',\n    target: document.getElementById('tiny-loading1')\n  })\n\n  Promise.then(() => {\n    this.loadingInstance.close()\n  }, 3000)\n}"
    }
  },
  "componentName": "Page",
  "css": "",
  "props": {},
  "lifeCycles": {},
  "children": [
    {
      "componentName": "ElButton",
      "props": {
        "onClick": {
          "type": "JSExpression",
          "value": "this.onClickNew"
        }
      },
      "children": [
        {
          "componentName": "Text",
          "props": {
            "text": "按钮文本"
          },
          "id": "12343321"
        }
      ],
      "id": "84222663"
    }
  ],
  "dataSource": {
    "list": []
  },
  "utils": [],
  "bridge": [],
  "inputs": [],
  "outputs": [],
  "fileName": "Loading"
}

tiny的这个loading也是的
![image](https://github.com/opentiny/tiny-engine/assets/24974566/51badba9-7e7f-4b8e-8d99-a255c309197f)

**Comment by ghost** [comment]
then方法是promise实例的，这里是想用Promise.resolve吧

**Comment by Thea1211** [comment]
嗯 Promise.resolve 没问题了

**Comment by Thea1211** [comment]
试下用 vue.nextTick loading就出不来的

**Comment by ghost** [comment]
loading的配置贴一下，这两个没有联系的

**Comment by Thea1211** [comment]
![image](https://github.com/opentiny/tiny-engine/assets/24974566/dc8e3d6d-4e79-45f9-be32-c3248236a719)

**Comment by ghost** [comment]
打开预览的代码，查看utils的引用是否正确，本地正常调用未发现问题
![image](https://github.com/opentiny/tiny-engine/assets/142570291/46e521b1-a391-4648-88a7-5b9776d9755f)

**Comment by Thea1211** [comment]
![image](https://github.com/opentiny/tiny-engine/assets/24974566/cc4e1e0a-be29-41a7-a56a-d6572a42479f)
预览的diamante是这么打开吗 貌似打不开

**Comment by ghost** [comment]
在预览页面打开F12，在Elements中搜索到class="left"的元素，把隐藏的样式取消
