### ISSUE TITLE
🐛 [Bug]: 画布编辑区域被左侧插件栏及右侧属性面板遮挡

### ISSUE THREAD

**Issue by lizhijie429** [opentiny/tiny-engine#248]
### Environment

chrome

### Version

18.16.0

### Version

latest

### Link to minimal reproduction

![image](https://github.com/opentiny/tiny-engine/assets/7768535/22ed59f5-c85a-4101-9ea3-82c41ea91d14)

### Step to reproduce

当画布编辑区域宽度设置大于屏幕区域时，会被左侧插件栏及右侧属性面板遮挡画布编辑区域，导致选中的组件部分功能不可用。

### What is expected

画布编辑区域可以全部展示或者左右拖动展示被遮挡的内容。

**Comment by ghost** [comment]
@lizhijie429 拉取下最新代码看看，还会有这种情况吗

**Comment by lizhijie429** [comment]
对的，最新版本的代码还是存在这个问题。

**Comment by ghost** [comment]
这边未复现，请描述一下复现步骤

**Comment by lizhijie429** [comment]
画布编辑区域的宽度设置为你电脑的分辨率就可以复现了。我的电脑实际分辨率1440，当画布编辑区域宽度为1200的时候就有问题了。
