### ISSUE TITLE
🐛 [Bug]: 预览时，input 显示成button

### ISSUE THREAD

**Issue by yehuagao** [opentiny/tiny-engine#249]
### Environment

windows11 chrome

### Version

18.16.0

### Version

3.11.0

### Link to minimal reproduction

{
  "state": {
    "formData": {
      "type": "JSExpression",
      "value": "{\r\n  userName: \"\",\r\n  password: \"\"\r\n}"
    }
  },
  "methods": {
    "onClickLogin": {
      "type": "JSFunction",
      "value": "function onClickLogin(event) {\n  console.log(this.state.formData)\n  console.log(this.state.loginFormRef)\n}"
    }
  },
  "componentName": "Page",
  "css": ".tinyform-hltop {\n  width: 300px;\n}\n.tinybutton-yrllv {\n  width: 300px;\n}\n.tinyinput-hfntj {\n  width: 300px;\n}\n.tinyinput-fuiap {\n  width: 300px;\n}\n.tinyinput-vklkk {\n  width: 300px;\n}\n.tinyinput-miwmw {\n  width: 300px;\n}\n.div-shurp {\n  display: flex;\n  justify-content: center;\n}\n.text-lxmuk {\n  font-weight: 700;\n  line-height: 40px;\n  text-align: left;\n}\n",
  "props": {},
  "lifeCycles": {},
  "children": [
    {
      "componentName": "div",
      "props": {
        "className": "div-shurp"
      },
      "id": "15a3454b",
      "children": [
        {
          "componentName": "Text",
          "props": {
            "text": "登录",
            "className": "text-lxmuk"
          },
          "id": "83451525"
        }
      ]
    },
    {
      "componentName": "TinyForm",
      "props": {
        "labelWidth": "80px",
        "labelPosition": "top",
        "className": "tinyform-hltop",
        "style": "margin: auto;\n"
      },
      "children": [
        {
          "componentName": "TinyFormItem",
          "props": {
            "label": "人员",
            "prop": "userName",
            "required": true
          },
          "children": [
            {
              "componentName": "TinyInput",
              "props": {
                "placeholder": "请输入",
                "autofocus": true,
                "className": "tinyinput-vklkk",
                "clearable": false
              },
              "id": "527c24e2"
            }
          ],
          "id": "563e54a9"
        },
        {
          "componentName": "TinyFormItem",
          "props": {
            "label": "密码",
            "prop": "password",
            "required": true
          },
          "children": [
            {
              "componentName": "TinyInput",
              "props": {
                "placeholder": "请输入",
                "modelValue": {
                  "type": "JSExpression",
                  "value": "this.state.formData.password",
                  "model": true
                },
                "type": "password",
                "className": "tinyinput-miwmw"
              },
              "id": "4e666347"
            }
          ],
          "id": "65f93956"
        },
        {
          "componentName": "TinyFormItem",
          "props": {
            "label": ""
          },
          "children": [
            {
              "componentName": "TinyButton",
              "props": {
                "type": "primary",
                "style": "margin-right: 10px",
                "className": "tinybutton-yrllv",
                "text": "登录",
                "onClick": {
                  "type": "JSExpression",
                  "value": "this.onClickLogin"
                }
              },
              "id": "35426262"
            }
          ],
          "id": "49335614"
        }
      ],
      "id": "21921123"
    }
  ],
  "dataSource": {
    "list": []
  },
  "utils": [],
  "bridge": [],
  "inputs": [],
  "outputs": [],
  "fileName": "Login"
}

### Step to reproduce

添加TinyForm 表单，然后预览

### What is actually happening

预览时：输入框 type 选择text 预览时不显示，input 渲染成button
![41fa8dde6830474fd8fa520709ccd66](https://github.com/opentiny/tiny-engine/assets/23260155/979ccaf4-ecef-4ec4-88e4-0be9738f13bd)
![ae05984581a80cb77cecc5447d52f70](https://github.com/opentiny/tiny-engine/assets/23260155/17c27315-850b-4b8f-b419-ce42a5b1b2f7)

**Comment by yehuagao** [comment]
import { Form as TinyForm, FormItem as TinyFormItem, Button as TinyButton, Button as TinyInput } from '@opentiny/vue';
Button as TinyInput 错了

**Comment by ghost** [comment]
@yehuagao 未能复现。请检查下数据库中TinyInput组件的npm字段中，exportName的值是否为"Input"。如果没有起后端服务，请查看appInfo.json中materialHistory.components中的TinyInput组件npm字段

**Comment by chilingling** [comment]
@yehuagao 您好，当前bug因无法再次复现，关闭 issue。后续如果能够再次复现该 bug，麻烦带上详细复现步骤再次打开该 issue，感谢对TinyEngine 的反馈与贡献。
