### ISSUE TITLE
🐛 [Bug]: 部署之后创建区块使用的时候报错

### ISSUE THREAD

**Issue by Thea1211** [opentiny/tiny-engine#255]
### Environment

chrome

### Version

v16.14.0

### Version

latest

### Link to minimal reproduction

https://github.com/opentiny/tiny-engine

### Step to reproduce

![image](https://github.com/opentiny/tiny-engine/assets/24974566/14bdac5e-527b-4233-84c5-ddb391e76c5c)
![image](https://github.com/opentiny/tiny-engine/assets/24974566/adf2d319-a6a8-4b5e-9abd-1ee0ac0ea381)
会是哪边的问题的

**Comment by Thea1211** [comment]
好像是inject的key的问题 
开发环境是对的
![image](https://github.com/opentiny/tiny-engine/assets/24974566/8dcfdb5b-f12b-474c-b8c3-88d296d25379)
生产的key 变成了 

![image](https://github.com/opentiny/tiny-engine/assets/24974566/5fe53a32-f2aa-4bee-bc92-0cfac1b92300)

**Comment by hexqi** [comment]
@Thea1211 能否详细描述下复现步骤呢？

**Comment by Thea1211** [comment]
就是区块发布之后 加到区块物料 把他拖进画布的时候报错
![image](https://github.com/opentiny/tiny-engine/assets/24974566/e21161de-eb9f-4787-8e0a-080f404d10d4)

![image](https://github.com/opentiny/tiny-engine/assets/24974566/722ccaad-ecff-4fd6-9728-03377890c916)

![image](https://github.com/opentiny/tiny-engine/assets/24974566/4494c4bc-f731-414c-b21c-85025ef8942d)
vue__namespace.inject(vueI18n.I18nInjectionKey) 是undefined


改成一个字符串 比如 ‘18nInjectionKey’ 而不是一个I18n暴露出来的symbol值就没问题

**Comment by chilingling** [comment]
@Thea1211 您好  #285  已经修复改错误

**Comment by Thea1211** [comment]
好的 测试ok了 感谢
