### ISSUE TITLE
🐛 [Bug]: 添加第三方组件库显示不了，如NutUI

### ISSUE THREAD

**Issue by yehuagao** [opentiny/tiny-engine#256]
### Environment

windows11 chrome

### Version

18.16.0

### Version

3.11.0

### Link to minimal reproduction

>  "npm": {
    "package": "@nutui/nutui",
    "version": "4.2.7",
    "script": "https://cdn.jsdelivr.net/npm/@nutui/nutui/dist/nutui.umd.js",
    "css": "https://cdn.jsdelivr.net/npm/@nutui/nutui/dist/style.css",
    "destructuring": true,
    "dependencies": null,
    "exportName": "Input"
  },

### Step to reproduce

1、配置bundle.json，component -> snippets

### What is actually happening

显示不了，一直加载中...

**Comment by ghost** [comment]
@yehuagao element-plus已正常导入使用，代码中有示例。个别组件库因为打包方式、CDN节点请求等问题导致动态导入出错或导入后在画布中无法正常显示。
下面可以提供一个替代方案

**Comment by yaoyun8** [comment]
1. 安装依赖：pnpm add @nutui/nutui
2. packages\canvas\src\components\render\runner.js中引入依赖
3. 将组件挂载到window.TinyLowcodeComponent，用于画布中读取组件
4. 预览

**Comment by ghost** [comment]
1. 在canvas目录（packages\canvas）下安装依赖：pnpm add @nutui/nutui
2. packages\canvas\src\components\render\runner.js中引入依赖
![image](https://github.com/opentiny/tiny-engine/assets/142570291/2ade1306-b9aa-4a74-beee-5997e2c48cc1)
```javascript
import * as NutUI from '@nutui/nutui'
import "@nutui/nutui/dist/style.css";
```
3. 将组件挂载到window.TinyLowcodeComponent，用于画布中读取组件
![image](https://github.com/opentiny/tiny-engine/assets/142570291/02147bff-0536-4a61-92ee-00f25357f7c0)
```javascript
Object.entries(NutUI).forEach(([_key, component]) => {
  const { name } = component
  if (name) {
    window.TinyLowcodeComponent[name] = component
  }
})
```

4. 预览importmap: packages\design-core\src\preview\src\preview\importMap.js
![image](https://github.com/opentiny/tiny-engine/assets/142570291/ad44069e-ba72-4930-ad59-9d2275d951d4)
```json
'@nutui/nutui/': `${VITE_CDN_DOMAIN}/@nutui/nutui@4.2.7/`,
'@nutui/nutui': `${VITE_CDN_DOMAIN}/@nutui/nutui@4.2.7/dist/nutui.es.js`,
'@nutui/icons-vue': `${VITE_CDN_DOMAIN}/@nutui/icons-vue@0.1.1/dist/lib/index.mjs`,
```

**Comment by yehuagao** [comment]
@yaoyun8 好的，谢谢，我试试
