### ISSUE TITLE
✨ [Feature]: 在左侧打开JS面板后，能直接切换tab查看变量值，类似阿里的低代码引擎，因为写JS的时候，很多时候需要查看变量。

### ISSUE THREAD

**Issue by cnbin** [opentiny/tiny-engine#257]
### What problem does this feature solve

在左侧打开JS面板后，能直接切换tab查看变量值，类似阿里的低代码引擎，因为写JS的时候，很多时候需要查看变量。
![1](https://github.com/opentiny/tiny-engine/assets/8576832/e5daee3f-e5ef-46d7-8c4d-0ab3dd34046f)
![22](https://github.com/opentiny/tiny-engine/assets/8576832/376ec8a5-b6ad-4fda-ba1e-0cb55686c619)

### What does the proposed API look like

在左侧打开JS面板后，能直接切换tab查看变量值

**Comment by hexqi** [comment]
@cnbin 主要是想查看当前的变量对吧，JS面板编写时会有代码提示提示state变量，当前是否可以满足需要呢？
