### ISSUE TITLE
🐛 [Bug]: 数据源添加时，获取远程的面板右侧没有滚动条，无法用鼠标拉出请求参数处理函数willFetch和请求完成回调函数，只能用鼠标滚轮。这里建议右侧加多个显示滚动条，不然很难滚动。

### ISSUE THREAD

**Issue by cnbin** [opentiny/tiny-engine#258]
### Environment

谷歌浏览器

### Version

17

### Version

3.11

### Link to minimal reproduction

数据源添加时，面板右侧没有滚动条，无法用鼠标拉出请求参数处理函数willFetch和请求完成回调函数，只能用鼠标滚轮。这里建议右侧加多个显示滚动条，不然很难滚动。
![CD6D7E14-42CE-4F81-8292-EBAACA91F4DA](https://github.com/opentiny/tiny-engine/assets/8576832/feb7d71c-6a89-49b7-a5cc-11c10e9a4cf3)

### Step to reproduce

数据源添加时，面板右侧没有滚动条，无法用鼠标拉出请求参数处理函数willFetch和请求完成回调函数，只能用鼠标滚轮。这里建议右侧加多个显示滚动条，不然很难滚动。

### What is expected

数据源添加时，建议右侧加多个显示滚动条，不然很难滚动。

**Comment by hexqi** [comment]
@cnbin 感谢反馈，已经记录，会尽快安排解决

**Comment by yxz1025** [comment]
添加数据源接口后，点击发起请求按钮，并没有执行接口请求事件

**Comment by zeyongTsai** [comment]
![image](https://github.com/opentiny/tiny-engine/assets/8591261/a225d2e6-ed1f-4655-bc16-2a34bbcb5f0d)

https://github.com/opentiny/tiny-engine/blob/99d0e47c29f0a2dc2bf1dcd2bd1ec49bde0c1b62/packages/plugins/robot/src/Main.vue#L440

这个 css 的影响范围太广了
