### ISSUE TITLE
🐛 [Bug]: 从数据源抓取数据函数有fetchData.api.apply is not a function

### ISSUE THREAD

**Issue by Cynwell** [opentiny/tiny-engine#263]
### Environment

win11, Command Prompt

### Version

v20.10.0

### Version

`-- (empty)

### Link to minimal reproduction

-

### Step to reproduce

1. 自建一个数据 server, 安装 `express` 包并且用 node.js 运行:
```
const express = require('express');
const app = express();

const data = [
    { data_id: '1', data_name: 'data1' },
];

app.get('/data', (req, res) => {
    res.json(data);
});

app.listen(8000, () => {
    console.log('Listening on port 8000');
});
```

2. 在终端机验证数据 server 正在运行
  ![image](https://github.com/opentiny/tiny-engine/assets/41886378/1714e080-7dda-4190-bbd3-784679833d66)
  - 输入：
  ```
  curl http://localhost:8000/data
  ```
  - 输出：
  ```
  [{"data_id":"1","data_name":"data1"}]
  ```

3. 在 tiny-engine 新增数据源，然后选获取远程字段，然后提供一个范本，`label_name` 与 `field name` 一样，完成后把两个保存按钮都按了
![image](https://github.com/opentiny/tiny-engine/assets/41886378/0472e420-f54f-43e4-bfa6-5adc657f0663)
![image](https://github.com/opentiny/tiny-engine/assets/41886378/3fc198b5-e79b-4c22-8e2c-3a6c86af32f3)

|名|值|
|---|---|
|数据源名称|FakeDataSource|
|描述|Fake Data Source|
|请求地址|http://localhost:8000/data|
|请求结果|{"data_id":"1","data_name":"data1"}|

4. 新增物料到版面，选取 content 里的表格并拖曳到版面里，然后把预填的表格列资料都删了，把 title 和 field 改成一样的
![image](https://github.com/opentiny/tiny-engine/assets/41886378/c388929d-4e37-45a7-aa57-e49040b0825d)

|title|field|
|---|---|
|data_id|data_id|
|data_name|data_name|

5. 从 fetchData 编辑代码旁边的**代码按钮**，出现变量绑定，然后在选单里选取**数据源**，选取刚刚新建的数据源，然后按确定
![image](https://github.com/opentiny/tiny-engine/assets/41886378/5288625b-fd36-43dd-b490-3116b71e3e94)

6. 完成后应该可以看到 fetchData 已绑定数据源
![image](https://github.com/opentiny/tiny-engine/assets/41886378/4451ccba-a56d-41ee-ba96-5d14f84682a3)

7. 保存，然后按预览，出现以下错误
![image](https://github.com/opentiny/tiny-engine/assets/41886378/1a158171-c5a1-48e2-8bda-365bac6996d8)
```
TypeError: fetchData.api.apply is not a function
    at Proxy.handleFetch (tiny-vue.mjs:37526:32)
    at Proxy.commitProxy (tiny-vue.mjs:37679:14)
    at Proxy.mounted13 (tiny-vue.mjs:37334:12)
    at callWithErrorHandling (vue.runtime.esm-browser.js:1651:22)
    at callWithAsyncErrorHandling (vue.runtime.esm-browser.js:1660:21)
    at hook.__weh.hook.__weh (vue.runtime.esm-browser.js:4145:29)
    at flushPostFlushCbs (vue.runtime.esm-browser.js:1848:47)
    at render (vue.runtime.esm-browser.js:7601:9)
    at mount (vue.runtime.esm-browser.js:5845:25)
    at app.mount (vue.runtime.esm-browser.js:10755:23)

about:srcdoc:168
```

### What is expected

预期在预览页面里，可以从数据源正常抓取数据，并且显示在表格里

**Comment by ghost** [comment]
@Cynwell 表格组件的fetchData要求是function，可以通过如下途径：
1. 拖入Collection组件，选择绑定的数据源；
![image](https://github.com/opentiny/tiny-engine/assets/142570291/397d0b4d-6ae0-4946-a45d-10c306e2dbf5)

2. 往Collection组件中拖入表格
3. 保存页面，预览

**Comment by Cynwell** [comment]
@yaoyun8 我按照官方教程尝试了：https://opentiny.design/tiny-engine#/help-center/course/engine/11

1. 首先拖了个 Collections，然后在 Collections 里面放一个 content 组件的表格组件。系统提示侦测到现有的数据源，我选择了预填充自动填进去。接着，我在空荡荡的表格里重新创建了两个表格列 data_id 和 data_name，每个列的 title 和 field 分别为：

  |title | field|
  |--|--|
  |data_id | data_id|
  |data_name | data_name|
  
  创建完成后，右边的属性栏看起来是这个样子的：
  <img width="172" alt="image" src="https://github.com/opentiny/tiny-engine/assets/41886378/861a920b-e572-4340-bd3e-c1c89fad0bfd">

2. 打开 JS，里面有一些自动产生的代码：
<img width="712" alt="image" src="https://github.com/opentiny/tiny-engine/assets/41886378/dccbf68f-9758-49a0-a0e2-0d6b4c9bfccf">

```
function getTableData25644f43({ page, sort, sortBy, filters }) {
  /**
   * @param {Object} sort 排序数据
   * @param {Array} sortBy 排序方式
   * @param {Object} page 分页数据
   * @param {Array} filters 筛选数据
   * @returns {Object} 返回一个promise对象，并且resolve格式为{ result: Array, page: { total: Number } }
   */
  return new Promise((resolve, reject) => {
    this.dataSourceMap.undefined.load().then((res) => {
      // 如果按照数据源面板的建议格式编写dataHandler
      // 那么dataSourceMap的res格式应该是：{ code: string, msg: string, data: {items: any[], total: number} }
      resolve({ result: res.data.items, page: { total: res.data.total } })
    })
  })
}
```

3. 保存后有一个错误信息弹出，估计是跟上面代码的 `this.dataSourceMap.undefined.load()` 有关：
<img width="333" alt="image" src="https://github.com/opentiny/tiny-engine/assets/41886378/6105e91f-d316-49cc-9760-7147c2593c48">

4. 所以我把 `this.dataSourceMap.undefined.load()` 换成 `this.dataSourceMap.FakeDataSource.load()`，其中 `FakeDataSource` 是编辑器自动建议弹出来的，所以应该不存在大小写的分别：
<img width="709" alt="image" src="https://github.com/opentiny/tiny-engine/assets/41886378/aeefe1cf-1efd-49f1-8bf5-6c32c5e07a38">

5. 再次保存后预览，没有报错，但也没有载入数据：
<img width="1368" alt="image" src="https://github.com/opentiny/tiny-engine/assets/41886378/0fe9c5e5-2e97-44d9-83d3-f619a870200d">

**Comment by yaoyun8** [comment]
@Cynwell 数据源可以编辑字段，这些字段会自动填充到表格的列中

**Comment by ghost** [comment]
@Cynwell 
1. 数据源可以编辑字段，这些字段会自动填充到表格的列中，绑定数据源就不需要手动添加列
![image](https://github.com/opentiny/tiny-engine/assets/142570291/bdbf5732-95b6-4b56-b720-d68c792ca22e)

2. this.dataSourceMap.undefined.load()这里推测是没有选择数据源，在拖入collection组件的时候在右侧属性面板选择数据源datasource

**Comment by Cynwell** [comment]
@yaoyun8 解决了 undefined 的问题了。发现是要先对 Collections 选取数据源，之后再拉表格，才会自动填入。
<img width="206" alt="image" src="https://github.com/opentiny/tiny-engine/assets/41886378/b8ab23ec-3c66-4647-9cb6-2c24ec8797a3">

目前的问题是数据没有在表格里显示。Console 显示预览状态下，应用有访问到 API 伺服器，也没有报错。以下是我的数据源的配置，是跟着这个教程配的 https://opentiny.design/tiny-engine#/help-center/course/engine/9：
<img width="1150" alt="image" src="https://github.com/opentiny/tiny-engine/assets/41886378/e7da3491-c464-4229-b2d5-33a3def339f2">

|名|值|
|---|---|
|数据源名称|FakeDataSource|
|描述|Fake Data Source|
|请求地址|GET; http://localhost:8000/fakeData|
|请求完成回调函数（dataHandler）|`function dataHandler(data) { return data.map(v => { return { name: v.aa.ss, status: v.status } }) }`|
请求结果|`{"data_id":"1","data_name":"data1"}`|

我使用的自建 API 伺服器是这样的：
```
const express = require('express');
const app = express();

const data = [{ data_id: '1', data_name: 'data1' }];

app.get('/fakeData', (req, res) => {
    res.json(data);
});

app.get('/fakeDataWellFormatted', (req, res) => {
    res.json({
        "code": "200",
        "msg": "OK",
        "data": {
            "items": data,
            "total": data.length
        }
    });
});

app.listen(8000, () => {
    console.log('Listening on port 8000');
});
```
访问结果是这样的：
<img width="637" alt="image" src="https://github.com/opentiny/tiny-engine/assets/41886378/251f6fe3-1879-4648-a2c2-4dee4218aced">

是 API 伺服器返回的结果有问题，导致表格无法读取数据吗？还是哪一步配置了呢？谢谢！

**Comment by ghost** [comment]
@Cynwell 在预览页面可以打开源代码查看和调试：找到class="left"的元素，默认是display：none的，将其显示出来。然后就是js代码的调用，可以在代码中输出或打断点
![image](https://github.com/opentiny/tiny-engine/assets/142570291/9f4b33c6-f115-4bc4-a9f6-3ae429052280)
