### ISSUE TITLE
🐛 [Bug]:  数据源中获取远程字段中的发送请求逻辑缺失，并且在发送过程中应该支持设置请求头，方便对于有权限校验等请求的支持

### ISSUE THREAD

**Issue by CareyYangyy** [opentiny/tiny-engine#267]
### Environment

Chrome120.0.6099.216（正式版本） (arm64)

### Version

v16.20.2

### Version

最新

### Link to minimal reproduction

- 新建数据源
- 点击获取远程字段
- 点击发送请求
   点击以后没有任何反应，查看源码，似乎缺少相关逻辑
![image](https://github.com/opentiny/tiny-engine/assets/23514644/56813041-2aad-4d67-99e8-d1a6e97190a5)
![image](https://github.com/opentiny/tiny-engine/assets/23514644/2c7c39c1-ebd5-4451-863e-50c86c012750)

### Step to reproduce

- 新建数据源
- 点击获取远程字段
- 点击发送请求
   点击以后没有任何反应，查看源码，似乎缺少相关逻辑
![image](https://github.com/opentiny/tiny-engine/assets/23514644/56813041-2aad-4d67-99e8-d1a6e97190a5)
![image](https://github.com/opentiny/tiny-engine/assets/23514644/2c7c39c1-ebd5-4451-863e-50c86c012750)

### What is expected

- 点击的时候能正常发送请求
- 能否支持对请求头的设置

**Comment by CareyYangyy** [comment]
![image](https://github.com/opentiny/tiny-engine/assets/23514644/cf3f0a9d-51e8-440e-8478-d18d0947ad62)

**Comment by ghost** [comment]
@CareyYangyy 请求头可以在willFetch函数中设置。
目前设置有问题，待PR合入后修复。
![image](https://github.com/opentiny/tiny-engine/assets/142570291/35dcf2ff-2a16-473f-8778-9281d5c72b41)
