### ISSUE TITLE
🐛 [Bug]: 组件中的content 分类下面的标签页组件预览报错

### ISSUE THREAD

**Issue by CareyYangyy** [opentiny/tiny-engine#268]
### Environment

Chrome120.0.6099.216（正式版本） (arm64)

### Version

v16.20.2

### Version

最新

### Link to minimal reproduction

- 先拖入一个标签页组件到page中：

![image](https://github.com/opentiny/tiny-engine/assets/23514644/ec3e47af-6e0b-436a-8333-f33d3efa1695)

- 预览：

![image](https://github.com/opentiny/tiny-engine/assets/23514644/27c9444a-4b8f-43f3-970c-213709e098a0)

### Step to reproduce

- 先拖入一个标签页组件到page中：

![image](https://github.com/opentiny/tiny-engine/assets/23514644/ec3e47af-6e0b-436a-8333-f33d3efa1695)

- 预览：

![image](https://github.com/opentiny/tiny-engine/assets/23514644/27c9444a-4b8f-43f3-970c-213709e098a0)

### What is expected

能够正常预览和发布，不要报错

**Comment by wenmine** [comment]
收到，已录入，会尽快排查问题

**Comment by ghost** [comment]
@CareyYangyy TinyTabItem组件的配置有误，exportName应该为TabItem
