### ISSUE TITLE
✨ [Feature]: 在当前的引擎当中，如何使用引入其他的UI组件

### ISSUE THREAD

**Issue by hao-gd** [opentiny/tiny-engine#27]
### What problem does this feature solve

在当前的引擎当中，如何使用引入其他的UI组件，
如果我想在当前的低代码平台添加 Element-ui 或者 Ant-desgin 或者自己封装的组件改如何添加到 低代码平台的。
恳请出一个示例详情，万分感谢

### What does the proposed API look like

在当前的引擎当中，如何使用引入其他的UI组件，
如果我想在当前的低代码平台添加 Element-ui 或者 Ant-desgin 或者自己封装的组件改如何添加到 低代码平台的。
恳请出一个示例详情，万分感谢

**Comment by wenmine** [comment]
@hao-gd hi，我们即将会推出相关更详细的文档，目前可以参考这篇文章进行探索：https://juejin.cn/post/7280926568854667299

**Comment by yaoyun8** [comment]
@hao-gd 可以先看看[使用手册](https://opentiny.design/tiny-engine#/help-center/course/engine/18)
