### ISSUE TITLE
✨ [Feature]: 目前是支持vue3的组件库物料引入吗？支持其他技术栈组件库吗？比如vue2和react

### ISSUE THREAD

**Issue by youchen133** [opentiny/tiny-engine#270]
### What problem does this feature solve

支持多种技术栈物料引入

### What does the proposed API look like

如何适配其他技术栈物料，比如vue2的element ui

**Comment by ghost** [comment]
@youchen133 当前只支持vue3组件，画布渲染依赖vue3的h函数，经过编辑打包的vue2或react组件无法渲染。
[如何在设计器中引入第三方组件库](https://opentiny.design/tiny-engine#/help-center/course/engine/15)
