### ISSUE TITLE
🐛 [Bug]: 接口 https://opentiny.design/tiny-engine/api/ai/chat 请求报错 报错信息: Access token expired

### ISSUE THREAD

**Issue by zhiwei55** [opentiny/tiny-engine#286]
### Environment

Chrome

### Version

latest

### Version

latest

### Link to minimal reproduction

https://opentiny.design/tiny-engine#/tiny-engine-editor

### Step to reproduce

https://opentiny.design/tiny-engine#/tiny-engine-editor
使用官方editor ai功能提示token 过期

**Comment by wenmine** [comment]
@zhiwei55 您可以使用我们开源项目，结合我们的后端配置自己的AI token，欢迎体验~~
