### ISSUE TITLE
麻烦官方大佬写文档时，帮我们多写些例子讲解，谢谢！

### ISSUE THREAD

**Issue by bingge2008** [opentiny/tiny-engine#29]
### What problem does this feature solve

官方大佬们好：
  能否写文档的时候把下面两个写进去，或者录制视频也行，谢谢！
（1）教会我们使用这个平台搭建一个完成的增删改查例子；
（2）怎样扩展左侧组件，比如用户选择组件、单位选择组件，然后form表单里面使用，拖入这2个控件，可以弹出dialog框选择用户和单位，点击确定后回填到表单上input框上。

### What does the proposed API look like

无

**Comment by wenmine** [comment]
您好，目前我们正在着手安排直播解答、演示您提供的问题，直播时间为本周五晚上8点，届时欢迎您来观看。

**Comment by wenmine** [comment]
@bingge2008 hi，请问一下第二点，是想咨询如何导入你们自身的组件到我们物料中，还是从0去搭一个组件，并且用在dialog里？

**Comment by wenmine** [comment]
@bingge2008 hi，我们更新了 [用户手册](https://opentiny.design/tiny-engine#/help-center/course/engine) 在官网，并且也针对之前的答疑梳理出了文字版，https://github.com/opentiny/tiny-engine/issues/78，希望能够帮助到你~
