### ISSUE TITLE
🐛 [Bug]: element-plus don‘t work，warning： Component is missing template or render function. 

### ISSUE THREAD

**Issue by DreamTear** [opentiny/tiny-engine#290]
### Environment

win10 chrome

### Version

node：20

### Version

latest

### Link to minimal reproduction

clone the rep then run  pnpm install  and pnpm dev

### Step to reproduce

1、change to Demopage;
2、 drag a element-plus element

### What is expected

hope the component render right

### What is actually happening

 [Vue warn]: Component is missing template or render function.

**Comment by ghost** [comment]
@DreamTear 已修复

**Comment by DreamTear** [comment]
thanks!
