### ISSUE TITLE
安装依赖后，项目运行后依然缺失很多依赖

### ISSUE THREAD

**Issue by leexiaozheng** [opentiny/tiny-engine#3]
node:18.0.0

安装依赖后，项目运行后依然缺失很多依赖

**Comment by wenmine** [comment]
@leexiaozheng 你好，麻烦提供一下详细一点的报错截图？

**Comment by charles4song** [comment]
[plugin:vite:import-analysis] Failed to resolve import "@opentiny/vue-theme/theme-tool" from "src/app/src/main.js". Does the file exist?

**Comment by taoyao-code** [comment]
<img width="927" alt="image" src="https://github.com/opentiny/tiny-engine/assets/38855041/005509c7-0988-48d7-9f72-7baba14e7b28">

**Comment by charles4song** [comment]
@wenmine 同样的问题，手动安装了以下依赖：
pnpm install @opentiny/vue-theme
pnpm install @opentiny/vue-renderless
pnpm install @vue/shared
pnpm install @opentiny/vue-locale
pnpm install css-tree
pnpm install axios  pinyin-pro
pnpm install axios-mock-adapter
![error-1](https://github.com/opentiny/tiny-engine/assets/131432377/f5aabe8b-009a-4e49-b648-635c899a344a)
![error-2](https://github.com/opentiny/tiny-engine/assets/131432377/d9eed340-71c0-4258-9bc6-13de97a5aebc)

**Comment by chilingling** [comment]
environment（环境）:
- node: 18.17.0
- pnpm 8.8.0

reproduce step（复现步骤）:
- pnpm install
- pnpm dev

can not reproduce 无法复现，可以正常启动。
please provide more detail to reproduce the error 麻烦提供更详细的复现步骤 @charles4song @taoyao-code @leexiaozheng
