### ISSUE TITLE
🐛 [Bug]: 下载代码时，提示错误 Cannot find module ... has a valid "main" entry

### ISSUE THREAD

**Issue by cyberkingkong** [opentiny/tiny-engine#30]
### Environment

ms-edge

### Version

v20.2.0

### Version

3.10.1

### Link to minimal reproduction

Cannot find module 'D:\opentiny\tiny-engine\mockServer\node_modules\@opentiny\tiny-engine-dsl-vue\dist\tiny-engine-dsl-vue.cjs.js'. Please verify that the package.json has a valid "main" entry

### Step to reproduce

pnpm dev 
运行后，生产代码，然后单击“下载”按钮，右侧出现弹窗，内容为： Cannot find module 'D:\wwwroot\opentiny\tiny-engine\mockServer\node_modules\@opentiny\tiny-engine-dsl-vue\dist\tiny-engine-dsl-vue.cjs.js'. Please verify that the package.json has a valid "main" entry

**Comment by wenmine** [comment]
@cyberkingkong hi，麻烦您进入到vue-generator的文件夹中，执行一下 npm run build，然后重新启动项目试试

**Comment by cyberkingkong** [comment]
成功了，谢谢。

**Comment by rongjx123** [comment]
> [@cyberkingkong](https://github.com/cyberkingkong) hi，麻烦您进入到vue-generator的文件夹中，执行一下 npm run build，然后重新启动项目试试

<img width="2193" height="573" alt="Image" src="https://github.com/user-attachments/assets/a534bd9d-57ee-48c9-a766-2f360d05a201" />执行npm run build报错了
