### ISSUE TITLE
✨ [Feature]: 能否提供一种区块的私有化部署使用方案，现有的是推到公有npm，每次发布都很慢，很影响效率，但是改造成私有化的npm，这个能否提供指导。

### ISSUE THREAD

**Issue by cnbin** [opentiny/tiny-engine#301]
### What problem does this feature solve

✨ [Feature]: 区块的私有化部署能否提供一种使用方案，现有的推到公有npm，每次发布都很慢，很影响效率，但是改造成私有化的npm，这块能否提供指导。本地有试了用Verdaccio方式来部署私有Npm，能够在终端用命令行推到私仓Npm，但是Verdaccio这种方式怎么改造成在代码里直接运行登录，像目前tiny-webservice的后端运行Npm一样，直接用代码来运行。还是说得用别的方式来部署私有的npm，这块能否提供指导。

### What does the proposed API look like

能否提供下具体的区块的私有化部署方案说明指南。

**Comment by wenmine** [comment]
@cnbin 可以暂时先考虑搭建一个内部的npm私仓来纳管这些内容

**Comment by cnbin** [comment]
好的，我这边用nexus和unpkg已初步实现区块私有化部署。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wenmine ***@***.***&gt;
发送时间: 2024年2月6日 16:35
收件人: opentiny/tiny-engine ***@***.***&gt;
抄送: cnbin ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [opentiny/tiny-engine] ✨ [Feature]: 能否提供一种区块的私有化部署使用方案，现有的是推到公有npm，每次发布都很慢，很影响效率，但是改造成私有化的npm，这个能否提供指导。 (Issue #301)





 
@cnbin 可以暂时先考虑搭建一个内部的npm私仓来纳管这些内容

**Comment by chilingling** [comment]
非 bug ，用户已初步实现私有化部署。该 issue 将被关闭
