### ISSUE TITLE
🐛 [Bug]: 添加自定义组件和第三方组件，出码后，工程中 package.json 未包含对应的安装包信息

### ISSUE THREAD

**Issue by zhengjg** [opentiny/tiny-engine#310]
### Environment

chrome

### Version

18.17.0

### Version

latest

### Link to minimal reproduction

// 出码的 vue 文件包含组件
import { ElInput } from 'element-plus'
import { Header as MuHeader } from 'mumu2-ui'
// package.json  未包含对于的安装包信息
  "dependencies": {
    "@opentiny/tiny-engine-i18n-host": "^1.0.0",
    "@opentiny/vue": "^3.10.0",
    "@opentiny/vue-icon": "^3.10.0",
    "axios": "^0.21.1",
    "axios-mock-adapter": "^1.19.0",
    "mumu2-ui": "^0.3.0",
    "pinia": "^2.1.7",
    "vue": "^3.2.25",
    "vue-i18n": "^9.2.0-beta.3",
    "vue-router": "^4.0.0"
  },

### Step to reproduce

step1:
组件面板拖拽第三方组件库，或者自己定义组件库到画布中
step2：
点击保存后-》应用发布
step3:
查看出码后的结果

### What is expected

1.源码使用的组件库信息应该和 package.json 的包一一对应
2.包含新建组件，和更新组件库版本等

### What is actually happening

源码使用的组件库信息应该和 package.json 的包一一对应

### Any additional comments (optional)

最新代码必现

**Comment by chilingling** [comment]
将在新版出码方案解决
