### ISSUE TITLE
🐛 [Bug]: 在删除区块构建文件的时候 有Error: EBUSY: resource busy or locked 报错

### ISSUE THREAD

**Issue by Thea1211** [opentiny/tiny-engine#314]
### Environment

chrome

### Version

v16.14.0

### Version

latest

### Link to minimal reproduction

https://github.com/opentiny/tiny-engine  windows

### Step to reproduce

发布区块 vueblockbuilder   // 清理构建目录  async clear() 的时候

**Comment by wenmine** [comment]
@Thea1211 您好，可以麻烦提供一下详细步骤吗

**Comment by Thea1211** [comment]
就是正常新建完区块之后 发布的 后端部署在这边的服务器的 就是async clear() 方法里的fs.remove() 去掉就没有问题的

**Comment by lu-yg** [comment]
检查下是否是文件被占用导致的，

**Comment by chilingling** [comment]
can not reproduce, close it.
