### ISSUE TITLE
🐛 [Bug]: tiny-grid 列启用插槽后无法预览

### ISSUE THREAD

**Issue by stwflyfox** [opentiny/tiny-engine#316]
### Environment

chrome

### Version

latest

### Version

latest

### Link to minimal reproduction

启用插槽后无法预览一片空白，而出码后的页面显示正常

### Step to reproduce

启用插槽后无法预览一片空白，而出码后的页面显示正常
![feee035606671c2fc315bb6b366d7f1](https://github.com/opentiny/tiny-engine/assets/3983204/3d132ea4-bff4-4e86-957f-e48a73b46206)
![6de89cd5765f5c68c56a06c9f464c0a](https://github.com/opentiny/tiny-engine/assets/3983204/d333281d-85f6-4a06-b30b-5e739629c3b5)
![c96b9fd72cde4f27c73007f90120ca9](https://github.com/opentiny/tiny-engine/assets/3983204/67d18c5d-2db4-4f12-915b-11adba26bfa8)

**Comment by stwflyfox** [comment]
预览时出错截屏
![e079f883821ddbd6e2f8290abe707c5](https://github.com/opentiny/tiny-engine/assets/3983204/a674b4fa-091e-4aad-9bfc-ff42c9f6aea9)

**Comment by zeyongTsai** [comment]
vue Repl 目前还不支持 jsx/tsx ，可以考虑代码生产逻辑改为使用 h 函数模式

**Comment by huiyuanz** [comment]
> vue Repl 目前还不支持 jsx/tsx ，可以考虑代码生产逻辑改为使用 h 函数模式

遇到同样的问题，能否给个示例

**Comment by zeyongTsai** [comment]
https://github.com/opentiny/tiny-engine/blob/68637db8dbf8342b6d3a18a0da85a30774a829c8/packages/vue-generator/src/parser/state-type.js#L48-L57

实现对等 `generateJSXTemplate` 的 h 函数调用形式的模板。

或者对 vue Repl 做二次开发，替换内部的编译工具以支持 jsx （官方有相关的 PR，但久久未合并）。个人更倾向这个选择，毕竟 h 函数模式不太好维护。
