### ISSUE TITLE
🐛 [Bug]: 区块用emit无法触发事件方法

### ISSUE THREAD

**Issue by stwflyfox** [opentiny/tiny-engine#322]
### Environment

chrome

### Version

latest

### Version

latest

### Link to minimal reproduction

区块中已设置事件，并在引用页面设置了事件绑定方法, 但无法用emit触发事件, 不会进入调用页面的事件方法，如用$emit则会报错

### Step to reproduce

区块中已设置事件，并在引用页面设置了事件绑定方法 
![d450492aa9080cc9e3b8ff8d93765ad](https://github.com/opentiny/tiny-engine/assets/3983204/340b9e36-b105-448c-b161-80f18e7c79f2)
![a97cc6ead9d82bede6fc46ec1d5aa54](https://github.com/opentiny/tiny-engine/assets/3983204/85a399e0-0d4f-4510-a558-912af02adced)
但无法用emit触发事件, 不会进入调用页面的事件方法，如用$emit则会报错
![0a8f20af8f5684e734c7ccf40da4cbc](https://github.com/opentiny/tiny-engine/assets/3983204/b1df6374-c9cc-49a9-8944-2503c7ff1515)
![b95c07a9db4a19594389b1900d69eca](https://github.com/opentiny/tiny-engine/assets/3983204/9f9bb277-1c1f-4b33-ae9a-b3eb097aee3a)

**Comment by Thea1211** [comment]
emit 不需要加this 区块的事件绑定名字要 on开头

**Comment by stwflyfox** [comment]
> emit 不需要加this 区块的事件绑定名字要 on开头

按此设置可以触发事件了。
