### ISSUE TITLE
🐛 [Bug]: 页面管理插件，返回了页面数据，但是在页面上面没有显示的问题

### ISSUE THREAD

**Issue by hao-gd** [opentiny/tiny-engine#342]
### Environment

5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

### Version

v18.11.0

### Version

`-- (empty)

### Link to minimal reproduction

问题原因在formatTreeData这个方法中，ROOT_ID 的类型是字符串0类型，item.parentId 却是数字类型，使用===进行判断，不相等问题

### Step to reproduce

点击侧边栏的页面管理插件，进行页面添加，如果添加完成后没有出现你新添加的页面，或者原本有的页面没有显示。

**Comment by chilingling** [comment]
can not reproduce, please provide more detail @hao-gd

**Comment by hao-gd** [comment]
在tiny-engine\packages\controller\src\usePage.js
的 第49行的 ROOT_ID ，原本的类型是 字符串
但是在 tiny-engine\packages\plugins\page\src\PageTree.vue 这个页面的 formatTreeData 方法的 88行，的判断中，item.parentId 返回的是一个 数字类型，和 ROOT_ID 进行判断，会出现判断不相等的情况数据无法插入到 originObj 中

**Comment by wenmine** [comment]
@hao-gd 麻烦再提供一下更详细的复现步骤，我们这边还是没有复现。

**Comment by chilingling** [comment]
官方无法复现，请提供相关信息以及复现步骤后再次打开该 issue @hao-gd
