### ISSUE TITLE
🐛 [Bug]: 画布设置为自由布局后组件无法拖动drag-resize改变宽高

### ISSUE THREAD

**Issue by UriChen** [opentiny/tiny-engine#350]
### Environment

Chrome 版本 122.0.6261.129（正式版本） （64 位）

### Version

v16.20.2

### Version

@opentiny/vue@3.10.0

### Link to minimal reproduction

https://opentiny.design/tiny-engine#/tiny-engine-editor

develop分支及官方playground页面均可复现 [2024-03-21]

### Step to reproduce

1. 点击页面正上方画布设置,切换为自由布局

2. 选中任意组件,拖拽调整组件宽高

**Comment by wenmine** [comment]
@gene9831 看一下是bug还是需要实现的功能，评估一下

**Comment by gene9831** [comment]
> @gene9831 看一下是bug还是需要实现的功能，评估一下

初步评估是bug。目前拖动drag-resize是有小概率可以改变宽高，导致bug的具体原因还待分析
