### ISSUE TITLE
🐛 [Bug]: 编辑器设置dark主题后预览页header文字颜色不正确

### ISSUE THREAD

**Issue by UriChen** [opentiny/tiny-engine#352]
### Environment

Chrome 版本 122.0.6261.129（正式版本） （64 位）

### Version

v16.20.2

### Version

@opentiny/vue@3.10.0

### Link to minimal reproduction

none

### Step to reproduce

![1711027878195](https://github.com/opentiny/tiny-engine/assets/44033360/b8e00d59-753f-4ac5-a8ef-42a82aabeb9b)

文字和背景一个颜色

**Comment by wenmine** [comment]
@lichunn 看一下这个问题

**Comment by chilingling** [comment]
fixed with #403
