### ISSUE TITLE
🐛 [Bug]: 工具类utils使用npm引入

### ISSUE THREAD

**Issue by pangweibao** [opentiny/tiny-engine#358]
### Environment

 '5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'

### Version

v16.14.0

### Version

最近

### Link to minimal reproduction

没有

### Step to reproduce

![1711462095483](https://github.com/opentiny/tiny-engine/assets/148454134/0b05f257-815e-415f-9400-67542c9b38c9)
![9H WQIBVNRQD)FV%OQ9HHGO](https://github.com/opentiny/tiny-engine/assets/148454134/2ddac27c-94df-4fe8-9720-9513dffa2e7b)
![32DSV7`4@8O@6X3 @RWBCOR](https://github.com/opentiny/tiny-engine/assets/148454134/87626d3c-9679-4e1d-bd22-849f262d5960)
npm包上传上传成功，按照文档上npm引入就报找不到模块。用vue的项目npm install 导入正常没有问题

### What is expected

在工具类中使用npm引入的方法

### What is actually happening

找不到模块

**Comment by stwflyfox** [comment]
导入npm包时要填写cdn, 你这个包必须要用cdn访问到。这样在预览时有能用cdn引用到你这个包。

**Comment by pangweibao** [comment]
![image](https://github.com/opentiny/tiny-engine/assets/148454134/e3eb0009-7aeb-4c39-93b7-d74b1119e5c2)
![image](https://github.com/opentiny/tiny-engine/assets/148454134/e15fdc55-466b-4db4-aebf-1da7ef5389a0)
![image](https://github.com/opentiny/tiny-engine/assets/148454134/ddc44813-04a5-45c4-8f4a-cda2183b7089)
还是不大行

**Comment by stwflyfox** [comment]
cdn可以不用加版本号， 启用解构， 导出名称为 request  再试看看

**Comment by pangweibao** [comment]
还是不行，一样的报错

**Comment by pangweibao** [comment]
已经解决了，加了个https的协议
