### ISSUE TITLE
🐛 [Bug]: 自定义物料，拖入编辑器后，无法选中

### ISSUE THREAD

**Issue by w990752800** [opentiny/tiny-engine#368]
### Environment

dev

### Version

20

### Version

latest

### Link to minimal reproduction

// json
`{
  "name": {
    "zh_CN": "iframe"
  },
  "component": "iframe",
  "icon": "iframe",
  "description": "iframe",
  "docUrl": "",
  "screenshot": "",
  "tags": "",
  "keywords": "",
  "devMode": "proCode",
  "npm": {},
  "group": "component",
  "category": "html",
  "priority": 40,
  "schema": {
    "properties": [
      {
        "label": {
          "zh_CN": "基础信息"
        },
        "description": {
          "zh_CN": "基础信息"
        },
        "content": [
          {
            "property": "src",
            "label": {
              "text": {
                "zh_CN": "src"
              }
            },
            "required": true,
            "readOnly": false,
            "disabled": false,
            "cols": 12,
            "widget": {
              "component": "MetaInput",
              "props": {}
            },
            "description": {
              "zh_CN": ""
            }
          }
        ]
      }
    ],
    "events": {
    }
  },
  "configure": {
    "loop": true,
    "condition": true,
    "styles": true,
    "isContainer": false,
    "isModal": false,
    "nestingRule": {
      "childWhitelist": [],
      "parentWhitelist": "",
      "descendantBlacklist": "",
      "ancestorWhitelist": ""
    },
    "isNullNode": false,
    "isLayout": false,
    "rootSelector": "",
    "shortcuts": {
      "properties": [
        "text", "columns"
      ]
    },
    "contextMenu": {
      "actions": [
        "create symbol"
      ],
      "disable": [
        "copy",
        "remove"
      ]
    }
  },
  "snippets": [
    {
      "name": {
        "zh_CN": "iframe"
      },
      "icon": "input",
      "screenshot": "",
      "snippetName": "iframe",
      "schema": {
        "componentName": "iframe",
        "props": {
          "src": ""
        }
      }
    }
  ]
}
`

// component

`<template>
    <iframe :src="props.src" frameborder="0" width="800" height="800"></iframe>
  </template>
  
  <script>
//   import { ref, watchEffect } from 'vue'
//   import { useProperties } from '@opentiny/tiny-engine-controller'
  
  export default {
    name: 'MetaIframe',
    components: {
    },
    props: {
      src: {
        type: String
      }
    },
    // emits: ['update:modelValue'],
    // setup(props, { emit }) {

    // }
  }
  </script>
  
  <style lang="less" scoped>

  </style>
  `

### Step to reproduce

编写后，拖入编辑器，无法在编辑器选中

### What is your project name

最新项目

**Comment by wenmine** [comment]
#372
