### ISSUE TITLE
🐛 [Bug]: 我使用 this.utils.Modal.alert({ message: () => <div>xxxx</div>, status: "" }); 在方法中使用携带DOM元素的这种，会报错 h方法不存在，能默认将 h 放到 import {h} from 'vue'中吗？

### ISSUE THREAD

**Issue by w990752800** [opentiny/tiny-engine#369]
### Environment

dev

### Version

20

### Version

latest

### Link to minimal reproduction

我使用 this.utils.Modal.alert({ message: () => <div>xxxx</div>, status: "" }); 在方法中使用携带DOM元素的这种，会报错 h方法不存在，能默认将 h 放到 import {h} from 'vue'中吗？

### Step to reproduce

我使用 this.utils.Modal.alert({ message: () => <div>xxxx</div>, status: "" }); 在方法中使用携带DOM元素的这种，会报错 h方法不存在，能默认将 h 放到 import {h} from 'vue'中吗？

### What is expected

可以正常运行

### What is your project name

最新项目

**Comment by gene9831** [comment]
你可以尝试下下面的代码，message为函数时，第一个参数是 `h` 函数
```js
this.utils.Modal.alert({ message: (h) => <div style="color: #fa9841">11111</div> })
```

**Comment by w990752800** [comment]
> 你可以尝试下下面的代码，message为函数时，第一个参数是 `h` 函数
> 
> ```js
> this.utils.Modal.alert({ message: (h) => <div style="color: #fa9841">11111</div> })
> ```

可以，感谢
