### ISSUE TITLE
🐛 [Bug]: 右侧绑定元素显示隐藏的变量操作按钮，当变量名字特别长，或者写了一个函数的时候，按钮就超出页面了

### ISSUE THREAD

**Issue by w990752800** [opentiny/tiny-engine#370]
### Environment

dev

### Version

20

### Version

latest

### Link to minimal reproduction

右侧绑定元素显示隐藏的变量操作按钮，当变量名字特别长，或者写了一个函数的时候，按钮就超出页面了

### Step to reproduce

右侧绑定元素显示隐藏的变量操作按钮，当变量名字特别长，或者写了一个函数的时候，按钮就超出页面了

### What is your project name

最新项目

**Comment by wenmine** [comment]
@w990752800 如果可以的话，麻烦提供一下图片

**Comment by w990752800** [comment]
![image](https://github.com/opentiny/tiny-engine/assets/23731304/23b3a74d-7123-41f5-b6c3-cb4ca13493f1)
