### ISSUE TITLE
🐛 [Bug]: 生成本地代码弹窗无勾选列表

### ISSUE THREAD

**Issue by leeron-obj** [opentiny/tiny-engine#375]
### Environment

chrome

### Version

v18.16.0

### Version

latest

### Link to minimal reproduction

![Snipaste_2024-04-02_17-09-40](https://github.com/opentiny/tiny-engine/assets/114710659/d148ba3c-fb6a-4a0b-95c2-0e9e5da45198)

### Step to reproduce

点击下载保存本地弹窗内无勾选项

### What is your project name

。

**Comment by wenmine** [comment]
您好，看一下console里有没有报错？请提供一下具体信息

**Comment by chilingling** [comment]
请提供最小复现步骤复现该错误，以及必要的基本环境信息、报错上下文
@leeron-obj
