### ISSUE TITLE
🐛 [Bug]: Drag into the TinyForm form, click to generate code, and the input box is displayed as a button

### ISSUE THREAD

**Issue by FairyShuai** [opentiny/tiny-engine#376]
### Environment

Chrome

### Version

18

### Version

@opentiny/vue@3.13.0

### Link to minimal reproduction

无

### Step to reproduce

拖入TinyForm表单，点击生成代码，input框显示为button

### What is expected

应该显示为input输入框

### What is actually happening

查找代码发现，引入生成的别名有误，生成的代码为Button as TinyInput，实际应该为Input as TinyInput

### What is your project name

无

### Any additional comments (optional)

使用时遇到

**Comment by wenmine** [comment]
@FairyShuai 您好，请问是用的develop最新代码吗

**Comment by FairyShuai** [comment]
> @FairyShuai 您好，请问是用的develop最新代码吗
@wenmine 2024/2/21下载的代码

**Comment by chilingling** [comment]
@FairyShuai 请基于最新代码提供更多信息，包括运行环境、链接的后端环境。

**Comment by FairyShuai** [comment]
新版本中已经不复现，感谢~
