### ISSUE TITLE
✨ [Feature]: 路由跳转之类的的出码

### ISSUE THREAD

**Issue by Thea1211** [opentiny/tiny-engine#378]
### What problem does this feature solve

路由跳转之类的的出码好像没有 后面会加上吗

### What does the proposed API look like

路由跳转之类的的出码好像没有 后面会加上吗

### What is your project name

tiny-engine

**Comment by wenmine** [comment]
@Thea1211 hi，这块当前正在版本规划里了，预计近两个月会推出
