### ISSUE TITLE
🐛 [Bug]: 执行 npm run build:prod 报错

### ISSUE THREAD

**Issue by w990752800** [opentiny/tiny-engine#382]
### Environment

dev

### Version

20

### Version

latest

### Link to minimal reproduction

![image](https://github.com/opentiny/tiny-engine/assets/23731304/d5abae23-c5b9-425a-8379-69ce1fa77dd0)

### Step to reproduce

![image](https://github.com/opentiny/tiny-engine/assets/23731304/84f06a44-6e78-4393-b2d2-693adf937f7b)

### What is your project name

最新项目

**Comment by chilingling** [comment]
@w990752800 请确保已经构建完 plugin，先执行 `pnpm build:plugin`

**Comment by w990752800** [comment]
> @w990752800 请确保已经构建完 plugin，先执行 `pnpm build:plugin`

可以，感谢
