### ISSUE TITLE
🐛 [Bug]: Tap Full Screen No Response

### ISSUE THREAD

**Issue by CatsAndMice** [opentiny/tiny-engine#396]
### Environment

Microsoft Edge

### Version

latest

### Version

3.6.1

### Link to minimal reproduction

https://opentiny.design/tiny-engine#/tiny-engine-editor
![](https://files.mdnice.com/user/38618/950bb1e8-26ed-477a-9f17-fd0938befb36.png)
点击全屏无反应

### Step to reproduce

访问官方链接: https://opentiny.design/tiny-engine#/tiny-engine-editor

### What is your project name

官方网站

**Comment by chilingling** [comment]
官网 demo 需要更新，最新代码 develop 已修复该 bug。
@CatsAndMice
