### ISSUE TITLE
🐛 [Bug]: Button hierarchy issues

### ISSUE THREAD

**Issue by CatsAndMice** [opentiny/tiny-engine#397]
### Environment

Microsoft Edge

### Version

latest

### Version

3.6.1

### Link to minimal reproduction
![](https://files.mdnice.com/user/38618/d964beef-345a-4b3c-9b68-d1393f4495be.png)

### Step to reproduce

访问官网：https://opentiny.design/tiny-engine#/tiny-engine-editor

然后切换到移动端
![](https://files.mdnice.com/user/38618/d964beef-345a-4b3c-9b68-d1393f4495be.png)

### What is your project name

官方网站

**Comment by CatsAndMice** [comment]
我晚点PR

**Comment by chilingling** [comment]
图裂了，麻烦补充一下
@CatsAndMice

**Comment by CatsAndMice** [comment]
> 图裂了，麻烦补充一下 @CatsAndMice

已补充
