### ISSUE TITLE
🐛 [Bug]: 区块编辑内容时，如果点击右上角清除画板内容，右侧属性面板不再展示添加属性按钮

### ISSUE THREAD

**Issue by youchen133** [opentiny/tiny-engine#410]
### Environment

mac

### Version

16

### Version

latest

### Link to minimal reproduction

暂无

### Step to reproduce

编辑区块详情时，直接点击清除按钮
<img width="1649" alt="image" src="https://github.com/opentiny/tiny-engine/assets/27907927/2f29ca00-a265-4e25-98e0-1a581e823fd2">

### What is your project name

无

**Comment by chilingling** [comment]
点击工具栏清空按钮之后，画布内容全部被清空，意味着当前选中内容也被清空，故无绑定属性按钮
@youchen133
