### ISSUE TITLE
✨ [Feature]: 通过iframe将tinyEngine嵌入到项目中，项目配置组件的json用postMessage传给tinyEngine，如何正确渲染至画布

### ISSUE THREAD

**Issue by leeron-obj** [opentiny/tiny-engine#427]
### What problem does this feature solve

通过iframe将tinyEngine嵌入到项目中，项目配置组件的json用postMessage传给tinyEngine，如何正确渲染至画布

### What does the proposed API look like

 无

### What is your project name

无

**Comment by chilingling** [comment]
not issue, transfer to discussion.
@leeron-obj
