### ISSUE TITLE
🐛 [Bug]: 多个区块分类时 区块分类的显示 修改有问题

### ISSUE THREAD

**Issue by Thea1211** [opentiny/tiny-engine#432]
### Environment

chrome

### Version

v16.14.0

### Version

latest

### Link to minimal reproduction

https://github.com/opentiny/tiny-engine

### Step to reproduce

多个区块分类时 区块分类的显示 修改有问题

### What is your project name

tiny-engine

**Comment by chilingling** [comment]
无法根据描述信息得知问题。
请详细描述问题场景，如何复现，然后再打开该 issue
@Thea1211

**Comment by Thea1211** [comment]
新建两个区块分类 detail ， other 建一个block 选择 detail分来 保存之后 在打开这个区块的设置 分类是other 分类筛选也有问题
