### ISSUE TITLE
🐛 [Bug]: preview一直处于“页面加载中...”的提示，console提示文件未找到

### ISSUE THREAD

**Issue by kenekai** [opentiny/tiny-engine#440]
### Environment

chrome

### Version

v16.20.2

### Version

latest

### Link to minimal reproduction

暂无

### Step to reproduce

在官方demo的直接preview时，preview一直处于“页面加载中...”的提示，console提示文件未找到
![image](https://github.com/opentiny/tiny-engine/assets/103375558/43a6eaf6-850c-4bc1-82a6-f5f18525a3f9)
项目中实际也不存在该文件
![image](https://github.com/opentiny/tiny-engine/assets/103375558/f95cf363-4c31-47d7-b030-6379abbce2eb)

### What is expected

预览页面正常展示

### What is actually happening

预览页面未正常展示

### What is your project name

无

**Comment by chilingling** [comment]
使用 mockServer 体验服务端能力预览时，需要提前构建 vue-dsl package。执行命令：`pnpm -F @opentiny/tiny-engine-dsl-vue build`。再启动服务
@kenekai

**Comment by kenekai** [comment]
执行`pnpm -F @opentiny/tiny-engine-dsl-vue build`后报错。已拉取develop分支最新代码。
![image](https://github.com/opentiny/tiny-engine/assets/103375558/61b2544f-e545-4cd8-be3d-c486bea0be60)

**Comment by kenekai** [comment]
@chilingling

**Comment by chilingling** [comment]
> 执行`pnpm -F @opentiny/tiny-engine-dsl-vue build`后报错。已拉取develop分支最新代码。 ![image](https://private-user-images.githubusercontent.com/103375558/324658313-61b2544f-e545-4cd8-be3d-c486bea0be60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MzgyMDQsIm5iZiI6MTcxMzgzNzkwNCwicGF0aCI6Ii8xMDMzNzU1NTgvMzI0NjU4MzEzLTYxYjI1NDRmLWU1NDUtNGNkOC1iZTNkLWM0ODZiZWEwYmU2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QwMjA1MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODQ5N2VmYjYyYTRiMTI3YzlhNzE5MDBjNzllYjRmNjgyNWQ2Nzc3ODRmZTYyZWNhNTdhNmE4N2IwYzI5NGQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kfEcfQfjnZ7eziGCWLtY85caClARO4KXLpsBTABvv9w)

先执行 `pnpm install` 安装依赖
@kenekai

**Comment by LKCheng** [comment]
pnpm install 已经执行，还是报上面错误

**Comment by kenekai** [comment]
已经执行了`pnpm install`，再执行 `pnpm -F @opentiny/tiny-engine-dsl-vue build` 仍然报错。
为避免操作失误，删除项目，重新clone了develop分支，执行`pnpm install`，`pnpm -F @opentiny/tiny-engine-dsl-vue build`仍然报错。
@chilingling

**Comment by chilingling** [comment]
如果是新项目，依次执行：
```bash
pnpm install
pnpm build:plugin
```

@kenekai @kenekai

**Comment by chilingling** [comment]
该问题的具体原因是：
- 新合入代码中， vue-generator 的 prettier 代码格式化依赖了 @opentiny/tiny-engine-controller 中的配置。
![image](https://github.com/opentiny/tiny-engine/assets/26962197/0da46e79-e9a9-48ac-8ce6-042527f786b7)

- 如果 controller 没有进行编译，就执行 `pnpm -F @opentiny/tiny-engine-dsl-vue build` 编译 vue-generator，会导致报错。
