### ISSUE TITLE
🐛 [Bug]: 无法添加loading

### ISSUE THREAD

**Issue by FairyShuai** [opentiny/tiny-engine#443]
### Environment

官网demo

### Version

最新版本

### Version

最新版本

### Link to minimal reproduction

无

### Step to reproduce

在低代码编辑器的function中，无法使用Loading，出码后无法自动引入Loading组件
![image](https://github.com/opentiny/tiny-engine/assets/71536307/150e62b0-d877-4136-a235-79a5d34a64bf)

### What is expected

请提供类似Loading这种直接在function中调用方法的组件的使用方法
如下是官网给出的Loading使用方法
<template>
  <div>
    <tiny-button @click="closeLoading">close Loading</tiny-button>
    <div id="tiny-basic-loading1"></div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { Loading, Button as TinyButton } from '@opentiny/vue'

const loadingInstance = ref(null)

const closeLoading = () => {
  loadingInstance.value.close()
}

onMounted(() => {
  loadingInstance.value = Loading.service({
    target: document.getElementById('tiny-basic-loading1')
  })
})
</script>

<style scoped>
#tiny-basic-loading1 {
  width: 100%;
  height: 120px;
  border: 1px solid beige;
  margin-top: 10px;
}
</style>

### What is actually happening

出码后没有自动引入Loading

### What is your project name

无

**Comment by chilingling** [comment]
当前可以借助 utils 工具类实现类似效果。
![image](https://github.com/opentiny/tiny-engine/assets/26962197/738c425f-1c3d-43e7-bac6-f290faf9bc50)

在自定义 function 中使用：

```javascript
function foo() {
  this.state.loadingInstance = this.utils.Loading.service(...)
}
```

@FairyShuai
