### ISSUE TITLE
请问具体怎么开发物料?

### ISSUE THREAD

**Issue by appleqzw** [opentiny/tiny-engine#45]
看了下学院课程中的物料文档，是基于[在线平台](https://opentiny.design/tiny-engine#/ecosystem/material)的，并不是自己开发一个物料的教程，其他的也就只有个介绍、提纲，希望官方能有更详细的使用文档
比如：
- 如何从0开始，开发一个物料，并接入低代码平台
- 如果要用第三方组件库作为物料，应该怎么做
- 如果物料的数据要支持调用接口动态获取，应该怎么开发这个物料，能给个简单的demo么

**Comment by wenmine** [comment]
@appleqzw 参考官网-[使用手册](https://opentiny.design/tiny-engine#/help-center/course/engine/18)。

**Comment by appleqzw** [comment]
@wenmine 刚看了下，文档是把第三方组件库改成物料
那自己开发一个物料呢？也得以组件库得形式发npm包然后这么做么？

**Comment by wenmine** [comment]
@appleqzw 意思是自己开发一个组件（区块）吗？如果是的话这个需要拥有组件构建，发布能力，会在我们后端开源时提供解决方案给到您

**Comment by appleqzw** [comment]
> @appleqzw 意思是自己开发一个组件（区块）吗？如果是的话这个需要拥有组件构建，发布能力，会在我们后端开源时提供解决方案给到您

是这个意思，请问有个大概时间么？

**Comment by wenmine** [comment]
@appleqzw 目前正在流程中，预计在12月底之前会将后端进行开源

**Comment by qiangwai** [comment]
请问现在后端开源后有具体的例子吗 我看还是第三方组件引入呢
