### ISSUE TITLE
自定义一个类似@opentiny/vue里面的组件并引入tiny-engine平台，编辑时显示，预览和导出代码到tiny-engine-generate-preview时不显示，tiny-engine-generate-preview的项目暂时是可以手动Install解决🐛 [Bug]: 

### ISSUE THREAD

**Issue by sunyuehhh** [opentiny/tiny-engine#451]
### Environment

v18.20.2

### Version

v18.20.2

### Version

3.10.0

### Link to minimal reproduction

https://www.npmjs.com/package/opentiny-vue-sy?activeTab=code

### Step to reproduce

引入组件，拖到画布中，点击预览

### What is your project name

tiny-engine

**Comment by sunyuehhh** [comment]
解决了，需要在importMap文件中添加一下
const tinyVue3Imports = {
  // 推荐之后统一使用@opentiny/vue去引入依赖，兼容后续录入的组件来源于tiny-vue
  '@opentiny/vue': `${VITE_CDN_DOMAIN}/@opentiny/vue@${opentinyVueVersion}/runtime/tiny-vue.mjs`,
  '@opentiny/vue-icon': `${VITE_CDN_DOMAIN}/@opentiny/vue@${opentinyVueVersion}/runtime/tiny-vue-icon.mjs`,
  '@opentiny/vue-common': `${VITE_CDN_DOMAIN}/@opentiny/vue@${opentinyVueVersion}/runtime/tiny-vue-common.mjs`,
  '@opentiny/vue-locale': `${VITE_CDN_DOMAIN}/@opentiny/vue@${opentinyVueVersion}/runtime/tiny-vue-locale.mjs`,
  '@opentiny/vue-renderless/': `${VITE_CDN_DOMAIN}/@opentiny/vue-renderless@${opentinyVueVersion}/`,
}

**Comment by chilingling** [comment]
issue resolved
