### ISSUE TITLE
🐛 [Bug]: @opentiny/tiny-engine-controller 打包报错

### ISSUE THREAD

**Issue by qian-chen97** [opentiny/tiny-engine#465]
### Environment

windwos11

### Version

16

### Version

最新

### Link to minimal reproduction

![image](https://github.com/opentiny/tiny-engine/assets/46392918/09cdded2-425e-4a1d-8abf-b6108ce6fa1f)

### Step to reproduce

RollupError: Invalid pattern "./js/completion.js" for "output.entryFileNames", patterns can be neither absolute nor relative paths. If you want your files to be stored in a subdirectory, write its name without a leading slash like this: subdirectory/pattern.

### What is your project name

1

**Comment by chilingling** [comment]
develop 分支代码无法复现，麻烦提供详细复现步骤 
@ArtisanQ

**Comment by qian-chen97** [comment]
执行pnpm build:plugin（controller 打包）就会报错， 目前的解决方案：
const jsEntries = glob.sync('./js/**/*.js').map((file) => {
  return [file.slice(5, file.length - path.extname(file).length), fileURLToPath(new URL(file, import.meta.url))]
})

      fileName: (format, entryName) => {
        if (entryName in Object.fromEntries(jsEntries)) {
          return `js/${entryName}.js`;  // 动态入口放在 js/ 子目录
        }
        return `${entryName}.js`;  // 静态入口放在根目录
      },

应该是./js/xxx.js   无法识别路径

**Comment by chilingling** [comment]
![image](https://github.com/opentiny/tiny-engine/assets/26962197/9736568a-2004-478c-a714-f0ecc86c295e)

我这边还是没法复现 @ArtisanQ

**Comment by chilingling** [comment]
close issue due to lack of response.
