### ISSUE TITLE
🐛 [Bug]: develop环境点击预览无法预览，v1.0.0-alpha.1版本提示 Uncaught ReferenceError: ref is not defined     at PageSetting.vue:70:16

### ISSUE THREAD

**Issue by yao521521** [opentiny/tiny-engine#466]
### Environment

google与edge都无法预览

### Version

v16.20.2

### Version

不知道如何查看最新稳定版

### Link to minimal reproduction

https://github.com/opentiny/tiny-engine

### Step to reproduce

项目下载依赖后直接运行，然后点击预览，v1.0.0-alpha.1版本直接运行

### What is expected

可以预览，v1.0.0-alpha.1可以显示物料

### What is actually happening

无法预览
![image](https://github.com/opentiny/tiny-engine/assets/90167238/97f2b166-a21d-4d6b-9752-36331960c779)
![image](https://github.com/opentiny/tiny-engine/assets/90167238/481c3015-8dd7-4eb6-a7cb-ac2160978ec1)

### What is your project name

tiny-engine tiny-engine-1.0.0-alpha.1

**Comment by chilingling** [comment]
1. 同步官方最新 develop  代码
2. 参考官方PR升级依赖。
	- #347 
	- #445
