### ISSUE TITLE
✨ [Feature]: 部署

### ISSUE THREAD

**Issue by alvin0804** [opentiny/tiny-engine#47]
### What problem does this feature solve

请问下在生产是怎么设计器的输出结果呢？

### What does the proposed API look like

看了下preview的逻辑但是发现渲染太慢，应该达不到产品所需的渲染要求

**Comment by alvin0804** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wenmine** [comment]
@alvin0804 您好，使用TinyEngine开发平台，可以使用右上角保存源代码到本地，将您页面的vue源码直接保存在您自己的项目中使用。
