### ISSUE TITLE
🐛 [Bug]: 数据源添加成功但是左侧没有更新

### ISSUE THREAD

**Issue by yao521521** [opentiny/tiny-engine#475]
### Environment

google与edge

### Version

v16.20.2

### Version

不知道如何查看最新稳定版

### Link to minimal reproduction

https://github.com/opentiny/tiny-engine

### Step to reproduce

https://github.com/opentiny/tiny-engine/assets/90167238/b7f3ce8e-eea3-4f08-9eaf-7d1876e21712

### What is expected

预期内容左侧已经添加数据源

### What is actually happening

https://github.com/opentiny/tiny-engine/assets/90167238/3e394b75-913b-48ad-8a09-b30e00555802

### What is your project name

tiny-engine

**Comment by wenmine** [comment]
数据源功能，需要结合后端使用，如果只启动前端的话， 因为前端用的是mock能力，当前不好进行相应的mock处理。
@yao521521

**Comment by yao521521** [comment]
有没有这个问题对应的相关文档呀
