### ISSUE TITLE
🐛 [Bug]: standalone.mjs报错

### ISSUE THREAD

**Issue by qian-chen97** [opentiny/tiny-engine#477]
### Environment

win11

### Version

16

### Version

最新

### Link to minimal reproduction

![image](https://github.com/opentiny/tiny-engine/assets/46392918/9d6169a3-9858-46a6-8837-bb2bf9fdcd5d)

### Step to reproduce

![image](https://github.com/opentiny/tiny-engine/assets/46392918/3951e763-db32-478b-bbc6-024a1e0d0a63)

### What is your project name

1

**Comment by chilingling** [comment]
默认的 CDN 有问题，建议切换成  htps://unpkg.com。

**Comment by wenmine** [comment]
> 默认的 CDN 有问题，建议切换成 htps://unpkg.com。

@ArtisanQ
