### ISSUE TITLE
🐛 [Bug]: 联网状态下，下载好依赖，并运行成功后！拷贝项目目录和依赖到内网（或其它目录）后，项目无法正常

### ISSUE THREAD

**Issue by houmenglong** [opentiny/tiny-engine#485]
### Environment

Window

### Version

latest

### Version

latest

### Link to minimal reproduction

![2024-05-16_120757](https://github.com/opentiny/tiny-engine/assets/15070410/36a8f29e-994d-430c-9a78-51462f7cb234)

### Step to reproduce

node:internal/modules/cjs/loader:1137
  throw err;
  ^

Error: Cannot find module 'F:\项目\tiny-engine-develop\node_modules\concurrently\dist\bin\concurrently.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.19.0

### What is your project name

tiny-engine-develop

**Comment by kenekai** [comment]
可以看下这个PR：https://github.com/opentiny/tiny-engine/pull/360

**Comment by chilingling** [comment]
联网状态下能够安装并启动成功，但是在手动拷贝代码以及依赖到另一个目录重新运行的场景太少了。官方精力有限，恕无法提供帮助。

建议通过内网搭建私有 npm registry 的方式来完成依赖的安装以及同步。
参考：
- https://github.com/cnpm/cnpm
- https://github.com/verdaccio/verdaccio
@houmenglong
