### ISSUE TITLE
🐛 [Bug]: 配置数据源后通过button按钮请求数据源，数据源没有被请求出来

### ISSUE THREAD

**Issue by yao521521** [opentiny/tiny-engine#486]
### Environment

google与edge

### Version

v16.20.2

### Version

不知道如何查看最新稳定版

### Link to minimal reproduction

https://github.com/opentiny/tiny-engine

### Step to reproduce

[20240516_142853.zip](https://github.com/opentiny/tiny-engine/files/15330592/20240516_142853.zip)
上述zip文件里面有视频，是复现过程
https://[geo.datav.aliyun.com/areas_v3/bound/100000_full.json](https://geo.datav.aliyun.com/areas_v3/bound/100000_full.json)请求地址

### What is expected

请求出数据

### What is actually happening

没有请求出数据

### What is your project name

tiny-engine

**Comment by chilingling** [comment]
当前页面预览没有发起数据源的请求。只是返回了一层假数据。
