### ISSUE TITLE
🐛 [Bug]: 预览时element-plus组件不展示，el组件未import

### ISSUE THREAD

**Issue by kenekai** [opentiny/tiny-engine#498]
### Environment

124.0.6367.208

### Version

v16.20.2

### Version

latest

### Link to minimal reproduction

无

### Step to reproduce

1、画布拖入element-plus组件，画布有展示
![image](https://github.com/opentiny/tiny-engine/assets/103375558/8b026dd3-516c-491a-bf18-b9156f1f81aa)

2、保存-预览后element-plus组件未展示，查看调试element-plus组件未import
![image](https://github.com/opentiny/tiny-engine/assets/103375558/54b95baa-be60-4002-9405-cc53f37c20e6)

### What is expected

预览时element-plus组件正常展示

### What is actually happening

预览时element-plus组件未展示

### What is your project name

无

**Comment by chilingling** [comment]
@kenekai 感谢反馈。
将在 #503  进行修复
