### ISSUE TITLE
🐛 [Bug]: 生成代码到本地文件后，代码运行报错

### ISSUE THREAD

**Issue by yao521521** [opentiny/tiny-engine#507]
### Environment

google与edge

### Version

v16.20.2

### Version

不知道如何查看最新稳定版

### Link to minimal reproduction

https://github.com/opentiny/tiny-engine

### Step to reproduce

https://github.com/opentiny/tiny-engine/assets/90167238/49bf90a3-5162-45dc-ac3e-48bcdd680441

### What is expected

下载项目可以直接运行

### What is actually happening

下载项目无法运行

### What is your project name

tiny-engine

**Comment by chilingling** [comment]
@yao521521 你好，从报错信息来看，是 test2 在声明之前被调用了。请问是否方便做一个最小化的可复现 demo。方便我们帮助进一步的问题排查？

感谢反馈。

**Comment by chilingling** [comment]
与 #533  应该是一样的错误，重复了，关闭该重复的 issue。
