### ISSUE TITLE
✨ [Feature]: 增加element-plus 物料后，点击预览，组件显示不正确

### ISSUE THREAD

**Issue by godkun** [opentiny/tiny-engine#51]
### What problem does this feature solve

<img width="1601" alt="image" src="https://github.com/opentiny/tiny-engine/assets/26134303/b0289ea9-fecb-424c-8296-29e2efb92933">

如图所示，预览页面的组件显示不正确，schema2code接口生成的代码如下：

<img width="985" alt="image" src="https://github.com/opentiny/tiny-engine/assets/26134303/7f4de2b7-5d83-4cb5-aa6b-62f9f77170da">

问下官方开发者，需要做什么改动，才能让预览页面的组件显示正确

### What does the proposed API look like

预览页面的组件显示正确

**Comment by ghost** [comment]
@godkun 参考官网-[使用手册](https://opentiny.design/tiny-engine#/help-center/course/engine/18)。将物料中组件（packages\design-core\public\mock\bundle.json中的data.material.components）拷贝到应用数据（mockServer\src\services\appinfo.json）的materialHistory.components。

**Comment by godkun** [comment]
@yaoyun8 好，感谢，我来试试
