### ISSUE TITLE
🐛 [Bug]: TinyDivider分隔线出现可拖动区域，实际上又没法拖动元素到该区域。

### ISSUE THREAD

**Issue by stwflyfox** [opentiny/tiny-engine#518]
### Environment

chrome

### Version

latest

### Version

latest

### Link to minimal reproduction

TinyDivider出现可拖动区域，实际上又没法拖动元素到该区域。

### Step to reproduce

![image](https://github.com/opentiny/tiny-engine/assets/3983204/b48054a2-9677-4615-8d3f-94af514fc03d)
[TinyDivider.json](https://github.com/opentiny/tiny-engine/files/15479018/TinyDivider.json)
如裁图所示，developer分支更新到最新版本，TinyDivider出现可拖动区域，实际上又没法拖动元素到该区域。

### What is your project name

TinyEngine

**Comment by chilingling** [comment]
问题原因：物料配置问题。
新版当物料配置为 `isContainer: true`  且 children 为空时，会默认渲染辅助拖拽的 placeholder。
解决方案：配置  `isContainer: false`。

PS：如果需要配置 TinyDivider 分割线文字。应该增加 default 插槽。

```json
{
  "schema": {
    "slots": {
      "default": {
        "label": {
          "zh_CN": "default"
        },
        "description": {
          "zh_CN": "自定义默认内容"
        }
      }
    }
  }
}
```

![image](https://github.com/opentiny/tiny-engine/assets/26962197/cebd311c-c2c3-4c9a-915a-670e4d57b639)

**Comment by stwflyfox** [comment]
OK,修改物料配置，问题已解决。

**Comment by chilingling** [comment]
resolved.
