### ISSUE TITLE
🐛 [Bug]: TinyGrid中列中设置样式时预览出错

### ISSUE THREAD

**Issue by stwflyfox** [opentiny/tiny-engine#519]
### Environment

chrome

### Version

latest

### Version

latest

### Link to minimal reproduction

TinyGrid中列中设置样式时预览出错

### Step to reproduce

![image](https://github.com/opentiny/tiny-engine/assets/3983204/a9d16480-75c9-4b14-8a32-943f5683c3eb)
![image](https://github.com/opentiny/tiny-engine/assets/3983204/70f4f752-574f-4714-b307-01829a30a659)
如图所示，列中设置图标样式，预览出错。

### What is your project name

TinyEngine

**Comment by chilingling** [comment]
初步定位原因：行内样式换行，出码后换行导致 vue 解析出错。
