### ISSUE TITLE
🐛 [Bug]: 出码时store出码有问题导致项目依赖无法启动=

### ISSUE THREAD

**Issue by yao521521** [opentiny/tiny-engine#533]
### Environment

google与edge

### Version

v16.20.2

### Version

不知道如何查看最新稳定版

### Link to minimal reproduction

https://github.com/opentiny/tiny-engine

### Step to reproduce

![96aa69b2119c2c69696f4bb74cd8b20](https://github.com/opentiny/tiny-engine/assets/90167238/ce570abb-a292-4bbf-a0e1-1e3916569bf2)

### What is expected

项目启动

### What is actually happening

报错，导致项目无法启动

### What is your project name

tiny-engine

**Comment by chilingling** [comment]
感谢反馈
@yao521521
