### ISSUE TITLE
🐛 [Bug]: el组件在canva可以显示，预览无法显示，查看代码貌似为import导入的问题

### ISSUE THREAD

**Issue by yao521521** [opentiny/tiny-engine#541]
### Environment

google与edge

### Version

v16.20.2

### Version

不知道如何查看最新稳定版

### Link to minimal reproduction

https://github.com/opentiny/tiny-engine

### Step to reproduce

在canvas添加按钮组件
![image](https://github.com/opentiny/tiny-engine/assets/90167238/d73635d9-05e6-49ef-995b-7460aadfe756)
在预览中查看
![image](https://github.com/opentiny/tiny-engine/assets/90167238/a88ecb26-17c4-4dc5-93af-ea6f3c132420)
样式丢失，且import没有导入的内容

### What is expected

预览与canva画布样式一致

### What is actually happening

样式丢失且没导入

### What is your project name

tiny-engine

**Comment by chilingling** [comment]
问题判定：物料配置问题
请确保物料配置正确。
从出码结果来看主要有几个问题：
1. ElHeader 的npm 物料配置 destructuring 没有配置为 true

```json
{
  "npm": {
      "package": "element-plus",
      // ...
     "exportName": "ElButton",
     "destructuring": true
   }
}
```

生成源码：`import { ElButton } from 'element-plus'`
假如 `destructuring` 配置为 false 或者不配置，则生成源码为：`import ElButton from 'element-plus'`，即为不正确的出码。

2. componentsMap 配置不正确。

如果是在 mockServer 中进行测试，请检查  `mockServer/src/mock/get/app-center/v1/apps/schema/918.json` 文件中的 `componentsMap` 配置是否包含了需要出码的组件。参考：#527   #503 

@yao521521
