### ISSUE TITLE
✨ [Feature]: TinyGrid要如何设置为v-bind

### ISSUE THREAD

**Issue by stwflyfox** [opentiny/tiny-engine#553]
### What problem does this feature solve

![682d1149cd516cb6c4c11f2cba08889](https://github.com/opentiny/tiny-engine/assets/3983204/3fceadfc-ef25-4fb8-8114-7b9360845ff0)
![13239f0029114c5bc4c46bd4756fbb3](https://github.com/opentiny/tiny-engine/assets/3983204/03aa75f5-daeb-4572-ab40-c564128513f2)
整个gird绑定 op 变量, 在json中要如何设置才能在设计器中能将grid绑定到变量， 会用到TinyGrid的配置式是因为 columns 不是固定的，需要由后台接口取到再绑到grid上.

### What does the proposed API look like

none

### What is your project name

TinyEngine

**Comment by chilingling** [comment]
当前还不支持 `v-bind` 模糊绑定，欢迎给我们提PR实现。

不过当前可以分属性进行绑定：

比如当前存储状态变量为  `op`，可以绑定  `column` 属性为 `op.column`；
`editConfig` 可以绑定为 `op.editConfig`

**Comment by stwflyfox** [comment]
在 data 和 columns 分别绑定变量即可
