### ISSUE TITLE
🐛 [Bug]: 数据请求部分在出码后可以请求，在预览中没法请求

### ISSUE THREAD

**Issue by yao521521** [opentiny/tiny-engine#570]
### Environment

google与edge

### Version

v16.20.2

### Version

不知道如何查看最新稳定版

### Link to minimal reproduction

https://github.com/opentiny/tiny-engine

### Step to reproduce

1.创建接口
![image](https://github.com/opentiny/tiny-engine/assets/90167238/0d5aa957-7291-4f75-bd4c-02d347cf2741)
接口地址
https://geo.datav.aliyun.com/areas_v3/bound/100000_full.json
2.添加点击事件
![image](https://github.com/opentiny/tiny-engine/assets/90167238/b597abb8-bf47-4fae-b9d6-96b18a00e006)
![image](https://github.com/opentiny/tiny-engine/assets/90167238/cecdd19d-6037-4b9c-ba7e-59cc5ed9b878)
3.预览（可以看到数据没有被请求）
![image](https://github.com/opentiny/tiny-engine/assets/90167238/0fce54ac-b766-4293-87d6-ebe46381dce2)
4.下载代码运行
![image](https://github.com/opentiny/tiny-engine/assets/90167238/6ea62b35-1f16-4e79-9b50-b30a3397e8aa)
5.下载代码的运行结果（数据被请求）
![image](https://github.com/opentiny/tiny-engine/assets/90167238/aca52a27-1ec5-4791-b90c-e591cbebbf4f)
![image](https://github.com/opentiny/tiny-engine/assets/90167238/0beabcc1-a007-4093-9588-e9f5820ae8c3)

### What is your project name

tiny-engine

**Comment by chilingling** [comment]
当前在预览页面为仅 mock，并没有真正发出请求。有兴趣可以给我们提PR进行相关实现 @yao521521
