### ISSUE TITLE
🐛 [Bug]:  自己写的组件用到了echarts，导入到tiny engine控制台报"process is not defined"

### ISSUE THREAD

**Issue by kalvinhu** [opentiny/tiny-engine#595]
### Environment

chrome

### Version

latest

### Version

latest

### Link to minimal reproduction

none

### Step to reproduce

组件地址：https://unpkg.com/hrj-custom-components@1.0.6/components/barChart/index.js
物料json：
[KvnBarchart.json](https://github.com/user-attachments/files/15965501/KvnBarchart.json)

### What is your project name

TinyEngine

**Comment by qiangwai** [comment]
打包文件有问题，这是node的语法内容 调整打包方式
