### ISSUE TITLE
🐛 [Bug]:  生成代码报错

### ISSUE THREAD

**Issue by qian-chen97** [opentiny/tiny-engine#61]
### Environment

windwos11

### Version

16

### Version

最新

### Link to minimal reproduction

Cannot find module 'C:\Users\cq\Desktop\12\tiny-engine-develop\tiny-engine-develop\mockServer\node_modules\@opentiny\tiny-engine-dsl-vue\dist\tiny-engine-dsl-vue.cjs.js'. Please verify that the package.json has a valid "main" entry

### Step to reproduce

点击生成

**Comment by chilingling** [comment]
当前需要先在 `packages/vue-generator` 目录下面先构建一遍 `pnpm run build`
