### ISSUE TITLE
🐛 [Bug]: 画布区域拖入tinyVue图表组件后，导致页面样式混乱

### ISSUE THREAD

**Issue by yao521521** [opentiny/tiny-engine#618]
### Environment

google与edge

### Version

v16.20.2

### Version

不知道如何查看最新稳定版

### Link to minimal reproduction

https://github.com/opentiny/tiny-engine

### Step to reproduce

1.在页面中拖入3个div
![image](https://github.com/opentiny/tiny-engine/assets/90167238/b4abb422-5fec-4ce8-b3b4-5b12f1d668fa)
2.div进行grid布局排列
![image](https://github.com/opentiny/tiny-engine/assets/90167238/b778a77b-feb7-4d12-a773-a6c0ff3e7fba)
3.进行grid布局之后的样式
![image](https://github.com/opentiny/tiny-engine/assets/90167238/90ecb2c1-7b52-4772-bb85-de861e9e3227)
4.拖入tinyVue图表组件
![image](https://github.com/opentiny/tiny-engine/assets/90167238/fce80f03-fead-4307-9159-7d6c0ec24aa6)
可以发现样式已然混乱
5.更改组件高度适应grid布局中div的高度
![image](https://github.com/opentiny/tiny-engine/assets/90167238/281031de-5e44-42b3-b71a-7c2679844e1a)
可以看到样式仍旧混乱
6.对canvas布局进行预览，可以看到达到预期的效果
![image](https://github.com/opentiny/tiny-engine/assets/90167238/1b2a6ac9-d5bf-40df-8cfc-2ae8b9a9f19c)
7.查看canvas 代码，可以看到canvas的高度是319
![image](https://github.com/opentiny/tiny-engine/assets/90167238/7f05c242-71fa-4d05-a9bd-769befeca0b5)

### What is expected

![image](https://github.com/opentiny/tiny-engine/assets/90167238/f65106bd-765c-4550-a72f-d586a2f008cd)

### What is actually happening

![image](https://github.com/opentiny/tiny-engine/assets/90167238/aa9b1ae6-88a0-4db4-a6d3-d36d7db2894b)

### What is your project name

tiny-engine

**Comment by yao521521** [comment]
这个问题貌似是tinyVue的原因奥，我自定义组件是没问题的
![image](https://github.com/opentiny/tiny-engine/assets/90167238/0b791dc2-7796-429a-86bf-f6f6b357e968)
![image](https://github.com/opentiny/tiny-engine/assets/90167238/fd5cc9f9-8bb0-4102-90ec-18d218ca00e8)

**Comment by yao521521** [comment]
自定义包名"ymq-material": "0.1.6"

**Comment by chilingling** [comment]
你好，请问能提供复现的相关 schema 以及组件物料的 json 代码吗？ @yao521521
