### ISSUE TITLE
🐛 [Bug]: 设置了默认值给组件但没有生效

### ISSUE THREAD

**Issue by kalvinhu** [opentiny/tiny-engine#636]
### Environment

chrome

### Version

latest

### Version

latest

### Link to minimal reproduction

[组件源代码.zip](https://github.com/user-attachments/files/16122619/default.zip)
导入信息：
[KvnBarchart.json](https://github.com/user-attachments/files/16122635/KvnBarchart.json)

### Step to reproduce

将组件拖入画布，在kvnBarchart里配的默认宽高为600，但是实际显示的还是组件里默认的300

### What is your project name

TinyEngine

**Comment by chilingling** [comment]
@kalvinhu  当前可以使用 snippts 中的代码片段设置默认值：

```json
{
  "snippets": [
    "name": {
        "zh_CN": "Kvn 的柱状图"
      },
      "icon": "button",
      "screenshot": "",
      "snippetName": "KvnBarchart",
      "schema": {
        "props": {
          "width": "600",
          "height": "600"
        }
      }
  ]
}
```
