### ISSUE TITLE
🐛 [Bug]: 自己写的组件在出码后只有一个标签，package.json里没有该组件的信息

### ISSUE THREAD

**Issue by kalvinhu** [opentiny/tiny-engine#642]
### Environment

chrome

### Version

latest

### Version

latest

### Link to minimal reproduction

以下是materials/components里的json文件
[KvnBarchart.json](https://github.com/user-attachments/files/16140348/KvnBarchart.json)

### Step to reproduce

把KvnBarchart放入materials/components文件夹里，然后执行build materials，然后从左边栏里将组件拖入画布，保存然后点击出码

### What is expected

出码后能正常显示组件

### What is actually happening

出码后不能显示组件

### What is your project name

TinyEngine

**Comment by chilingling** [comment]
![image](https://github.com/opentiny/tiny-engine/assets/26962197/6fc5cae2-dbad-4bb0-862c-c2ec448f1e77)
最新 develop，mockServer 模式下启动不复现。
麻烦确认下有没有 同步 #527 PR的代码
操作步骤：

- `pnpm splitMaterials` 拆分物料
- 往 `materials/components` 文件夹下添加链接文件
- `pnpm buildMaterials` 构建物料
- `pnpm dev ` 启动 mockServe 以及设计器
- 拖入目标组件
- 出码，package.json 中正常出现   `"hrj-custom-components": "1.1.6"`  的依赖声明

**Comment by chilingling** [comment]
PS: 画布不显示柱状图的问题。需要修改 `isContainer` 的配置为 false。
```json
{
  "configure": {
    "isContainer": false
  }
}
```

![image](https://github.com/opentiny/tiny-engine/assets/26962197/8d623435-1e73-4a09-a678-2b624b832cb0)
