### ISSUE TITLE
✨ [Feature]: 打包后的vue安装本地后出现404

### ISSUE THREAD

**Issue by jsntgmh** [opentiny/tiny-engine#643]
### What problem does this feature solve

打包后的vue安装本地后出现404，哪位大神看下问下有没有解决办法

![QQ图片20240710091210](https://github.com/opentiny/tiny-engine/assets/175170941/99efa65c-fb6b-4d6e-af40-3d03031ba190)
![QQ图片20240710091249](https://github.com/opentiny/tiny-engine/assets/175170941/4fb1a841-2680-4256-9bbd-18e02f5504ec)

### What does the proposed API look like

none

### What is your project name

vue login

**Comment by chilingling** [comment]
`/auth/captcha/captcha` 与 `/sass/0`  这两个接口应该不是 TinyEngine 这边的接口。如果是您这边业务方的接口，麻烦自行查看一下如何对接业务接口 @jsntgmh

**Comment by wenmine** [comment]
因用户长时间未有新的反馈，关闭此issue
