### ISSUE TITLE
🐛 [Bug]: el-rate 组件 max prop 设置无效

### ISSUE THREAD

**Issue by MarkoLING** [opentiny/tiny-engine#669]
### Environment

windows Google

### Version

v18.17.0

### Version

latest

### Link to minimal reproduction

这是组件的部分schema
![image](https://github.com/user-attachments/assets/752f144b-f1fa-43bf-8798-c58c94b4ab34)

这是设置max后显示异常
![image](https://github.com/user-attachments/assets/03f68297-71e5-4215-8235-15ec4d50dc40)

### Step to reproduce

拖入el-rate后，设置max属性，组件显示异常

### What is your project name

tiny-engine

**Comment by chilingling** [comment]
![image](https://github.com/user-attachments/assets/e26bf037-4291-43fe-bf9f-45680145c60c)
element-plus 中， max 属性应该是 number 类型。
物料配置里面，如果用 `MetaInput` ，得到的则会是 string 类型。所以改成  `MetaNumber` 即可。

@MarkoLING
