### ISSUE TITLE
🐛 [Bug]: 预览和导出代码时，在生成的代码中（出码时），第三方组件和部分内置组件无法被正常导入

### ISSUE THREAD

**Issue by 25he** [opentiny/tiny-engine#670]
### Environment

chrome

### Version

18.17.1

### Version

latest

### Link to minimal reproduction

无

### Step to reproduce

取消CDN引用，和以数据库的方式部署区块情况下，第三方组件和部分内置组件，在出码的时候无法被正常引用
![1](https://github.com/user-attachments/assets/24db728d-3704-4699-8a4c-b1e63f63df9d)
![2](https://github.com/user-attachments/assets/e170a1db-5142-4551-b8f4-cc49cb281dbd)
![3](https://github.com/user-attachments/assets/4a76a86e-a045-4078-8b05-b83085170fb0)
![4](https://github.com/user-attachments/assets/73f117ea-54b4-4e05-8ef8-a4589cf13ad5)
![5](https://github.com/user-attachments/assets/fd82689a-027a-44f8-b518-4ca6c6febe84)

### What is expected

希望能正常渲染出编辑的内容

### What is your project name

tiny-engine

**Comment by 25he** [comment]
补充：导出代码和发布应用的时候，生成的package.json中，也缺少对应的包: element-plus
![6](https://github.com/user-attachments/assets/72b1d014-5d65-47ee-ac1d-37ab7e4216c9)

**Comment by chilingling** [comment]
链接数据库的情况，需要检测数据库中 `componentsMap` 数据是否正确，出码生成 `import` 相关声明语句强依赖 `componentsMap`。
![image](https://github.com/user-attachments/assets/267bf70d-0e9e-4ca8-9a53-a86860cfee02)
@25he

**Comment by 25he** [comment]
![image](https://github.com/user-attachments/assets/0b7744be-8776-4ecc-91b7-96b0a2209eef)
将值打印发现这部分数据确实是有问题，可以告知一下这部分数据是存在哪个表里面的吗

**Comment by lu-yg** [comment]
你可以检查下，你在后端数据库中组件表user_components里有没有你需要导入的组件数据，以及该组件是否和物料历史有关联关系，关联关系表material_histories_components__user_components_mhs，前端导入新组件，应该通过脚本同步数据到后端数据库，在组件表user_components及物料历史和组件的关联关系表material_histories_components__user_components_mhs中都应插入该组件相关数据，看你的问题应该是后端未查到新组件数据导致的

**Comment by chilingling** [comment]
用户反馈问题已解决，有疑问欢迎再次打开 issue 或者另提 issue  @25he
