### ISSUE TITLE
✨ [Feature]: 首次打开编辑器的demo，elementplus首次无法渲染

### ISSUE THREAD

**Issue by leeron-obj** [opentiny/tiny-engine#675]
### What problem does this feature solve

demo改为elementplus的，部署到线上首次无法渲染对应组件，打开页面schema点击下保存，或者重新拖动个组件才能正常渲染，如图
![微信图片_20240722160155](https://github.com/user-attachments/assets/c06118ae-1148-4973-b8e1-44cb05fe7087)
![Snipaste_2024-07-22_16-02-53](https://github.com/user-attachments/assets/ee3dfdef-6153-4938-81bd-deb474c33c59)

### What does the proposed API look like

.

### What is your project name

。

**Comment by chilingling** [comment]
@leeron-obj 
无法复现，请提供详细可复现步骤，帮助我们复现定位问题。

**Comment by leeron-obj** [comment]
@chilingling iframe嵌套的编辑器，tinyVue的组件首次能正常渲染，elementplus的需要手动保存才可以。

**Comment by leeron-obj** [comment]
Uploading 20240726_160106.mp4…

**Comment by leeron-obj** [comment]
https://github.com/user-attachments/assets/a39506e7-1db2-43d9-9dec-62f12c32269b

**Comment by chilingling** [comment]
请问是否方便提供复现的页面 schema ？ @leeron-obj

**Comment by leeron-obj** [comment]
@chilingling 已经解决了 谢谢

**Comment by chilingling** [comment]
用户反馈已解决。
