### ISSUE TITLE
✨ [Feature]: 预览功能

### ISSUE THREAD

**Issue by qian-chen97** [opentiny/tiny-engine#68]
### What problem does this feature solve

现在的预览好像是根据源码在线编译，这样速度太慢了，请问下有更好的方式嘛？
有这样一种场景，将页面的json存储，前端直接解析json渲染出来

### What does the proposed API look like

更好的方式？

**Comment by wenmine** [comment]
@ArtisanQ 您好，目前我们提倡的方式是将我们设计的页面生成为源码在您的项目中使用
