### ISSUE TITLE
🐛 [Bug]: 工具类添加npm包(vue-router)、预览打印this.utils不存在router

### ISSUE THREAD

**Issue by Manson596** [opentiny/tiny-engine#71]
### Environment

谷歌 119.0.6045.105

### Version

18.18.2

### Version

~3.10.0

### Link to minimal reproduction

123

### Step to reproduce

1、pnpm run dev
2、点击资源管理
2.1、新建工具类
2.2、名称：vue-router
2.3、包名：vue-router
2.4、导出名称：useRouter
2.5、是否解构：是
2.6、保存（保存的时候列表返回没有我创建的工具类）
3、进入页面管理（当前页面）
3.1、添加生命周期（function onMounted() {console.log(this.utils)} ）
3.2、保存
4、 预览

### What is expected

能按逻辑正常添加、运行

### What is actually happening

工具类没有添加成功

**Comment by chilingling** [comment]
当前 mockServer 没有保存添加的 utils，导致预览态无法拿到添加的 utils

**Comment by wenmine** [comment]
@Manson596 hi，当前我们mockServer的能力只适用于基本的操作，保存添加的utils需要调用接口来支持，欢迎您等12月份我们后端开源时，结合后端代码进行适配，当然您也可以根据我们官方api文档开发自己匹配此套引擎的后端~
