### ISSUE TITLE
🐛 [Bug]: 升级tinyVue 3.17.2以后，绑定事件功能不能用了

### ISSUE THREAD

**Issue by dapeng123** [opentiny/tiny-engine#714]
### Environment

chrome 122

### Version

20.5

### Version

3.17.2

### Link to minimal reproduction

![1722003120094](https://github.com/user-attachments/assets/9a923a09-bdfc-4d53-ab6b-ab473445978d)
这里点了没反应，没有弹框了，没法加绑定事件

### Step to reproduce

所有opentiny的依赖更新到3.17.2后，出现了该bug

### What is your project name

所有opentiny的依赖更新到3.17.2后，绑定事件无法使用

**Comment by chilingling** [comment]
感谢反馈
