### ISSUE TITLE
🐛 [Bug]: 打包部署之后预览页面缺少组件

### ISSUE THREAD

**Issue by w990752800** [opentiny/tiny-engine#726]
### Environment

dev

### Version

20

### Version

latest

### Link to minimal reproduction

![image](https://github.com/user-attachments/assets/2a89b1da-f193-4878-bcc8-cdbd00dc757f)

### Step to reproduce

![image](https://github.com/user-attachments/assets/5be10bb9-f79a-4f02-9780-489d77305fbf)

### What is your project name

最新项目

**Comment by w990752800** [comment]
有些组件 没有引用进来

**Comment by w990752800** [comment]
`{
  "id": 1,
  "version": "0.6.7",
  "name": {
    "zh_CN": "Enable"
  },
  "component": "EnableControl",
  "icon": "switch",
  "description": "Enable",
  "doc_url": "",
  "screenshot": "",
  "tags": "",
  "keywords": "",
  "dev_mode": "proCode",
  "npm": {
    "package": "jaka-tiny-engine-block",
    "version": "0.6.7",
    "script": "https://npm.onmicrosoft.cn/jaka-tiny-engine-block@0.6.7/dist/jaka-tiny-engine-block.js",
    "css": "https://npm.onmicrosoft.cn/jaka-tiny-engine-block@0.6.7/dist/style.css",
    "dependencies": null,
    "destructuring": true,
    "exportName": "EnableControl"
  },
  "group": "基础组件",
  "category": "JAKA Robot",
  "configure": {
    "loop": true,
    "condition": true,
    "styles": true,
    "isContainer": false,
    "isModal": false,
    "isPopper": false,
    "nestingRule": {
      "childWhitelist": "",
      "parentWhitelist": "",
      "descendantBlacklist": "",
      "ancestorWhitelist": ""
    },
    "isNullNode": false,
    "isLayout": false,
    "rootSelector": "",
    "shortcuts": {
      "properties": [
        "type",
        "size"
      ]
    },
    "contextMenu": {
      "actions": [
        "copy",
        "remove",
        "insert",
        "updateAttr",
        "bindEevent",
        "createBlock"
      ],
      "disable": []
    },
    "invalidity": [
      ""
    ],
    "clickCapture": true,
    "framework": "Vue"
  },
  "schema": {
    "properties": [],
    "events": {},
    "slots": {}
  },
  "snippets": [
    {
      "name": {
        "zh_CN": "Enable"
      },
      "icon": "switch",
      "screenshot": "",
      "snippetName": "EnableControl",
      "schema": {
        "children": [],
        "props": {}
      }
    }
  ]
}`

**Comment by w990752800** [comment]
这个是组件的 sechma

**Comment by w990752800** [comment]
`import { CustomTag,ImgSelectView,WsBlock as JakaWsBlock,CustomTag,ImgSelectView,WsBlock as JakaWsBlock,CustomTag,ImgSelectView,WsBlock as JakaWsBlock,RobotControl,EnableControl } from "jaka-tiny-engine-block";` 又同步了最新代码，组件导入 重复

**Comment by chilingling** [comment]
你好，出码依赖构建物料时候写入的 componentsMap。出码中 `importt` 语句的生成跟这个强相关。

![image](https://github.com/user-attachments/assets/7f911bd4-a19f-41bd-9cb4-a3373b5545e8)

麻烦确认一下，componentsMap 中，是否存在对应的组件的声明。（如果是对接数据库，则查看对应[数据库](https://github.com/opentiny/tiny-engine/issues/670#issuecomment-2242404574)，如果对接 mockServer，则查看 `mockServer/src/mock/get/app-center/v1/apps/schema/918.json`）

相关联 issue：#670  #659 

@w990752800

**Comment by w990752800** [comment]
👌， 感谢

**Comment by chilingling** [comment]
用户反馈已解决，故关闭当前 issue。
