### ISSUE TITLE
本地启动后，下载的代码应该如何使用呢

### ISSUE THREAD

**Issue by LiHan2207** [opentiny/tiny-engine#73]
![image](https://github.com/opentiny/tiny-engine/assets/43174509/eb326bdf-3a26-4a4b-80a6-d49092b57cbf)
下载后的这个vue文件，里面涉及的一些方法像wrap啥的要怎么初始化？
怎么让这些文件跑在别的vue项目里面？

**Comment by Manson596** [comment]
同问

**Comment by wenmine** [comment]
@LiHan2207 @Manson596 你好，这个是通过我们低代码生成再下载到本地的吗？如果是的话，这个不是下载到tiny-engine项目里启动的，是下载到一个独立的vue项目里启动。可以参考这篇文章的QA部分第三个回答：https://mp.weixin.qq.com/s/Zt1illIgil9IGdfB6Fh7SA

**Comment by wenmine** [comment]
第一步：下载 https://github.com/opentiny/tiny-engine-generate-preview 工程，解压

第二步：将代码下载到解压好的文件夹中（提示选择文件夹的时候，选择我们解压出来的文件夹）

第三步：用代码编辑器打开文件夹，确认出码结果，安装依赖并运行 npm run dev 启动服务，查看效果

后续相关的规划：

支持开发插件，自定义出码结果

支持自定义工程模板，结合自定义出码结果，可以无缝在自身项目中运行

**Comment by LiHan2207** [comment]
> 第一步：下载 https://github.com/opentiny/tiny-engine-generate-preview 工程，解压
> 
> 第二步：将代码下载到解压好的文件夹中（提示选择文件夹的时候，选择我们解压出来的文件夹）
> 
> 第三步：用代码编辑器打开文件夹，确认出码结果，安装依赖并运行 npm run dev 启动服务，查看效果
> 
> 后续相关的规划：
> 
> 支持开发插件，自定义出码结果
> 
> 支持自定义工程模板，结合自定义出码结果，可以无缝在自身项目中运行

感谢大佬讲解，非常感谢，我尝试一下
