### ISSUE TITLE
🐛 [Bug]: 绑定参数传参，生成的vue目标字符串参数直接变成了变量

### ISSUE THREAD

**Issue by HelloCPL** [opentiny/tiny-engine#733]
### Environment

develop

### Version

latest

### Version

latest

### Link to minimal reproduction

![image](https://github.com/user-attachments/assets/cd3cb2a0-e760-4950-b791-fb1798ca21f2)

### Step to reproduce

生成的模板，参数如果是数字，恰好不会影响，如果是字符串就变成了变量
![image](https://github.com/user-attachments/assets/c4fa529c-4dc0-4c42-9ac2-9060c89bd1ce)
![image](https://github.com/user-attachments/assets/564c7cdc-fa9f-4c32-a48d-086968eb71c9)

### What is expected

应修改：
![image](https://github.com/user-attachments/assets/e6da9849-1eee-43fa-9e36-43b531100b7c)
修改后：
![image](https://github.com/user-attachments/assets/753a8c9b-9af8-4de3-96c9-8e1fcd821ae2)

### What is your project name

none

**Comment by HelloCPL** [comment]
非bug，原来默认就是变量，字符串需要再加 '' 包裹
![image](https://github.com/user-attachments/assets/152689ba-0602-4932-b8bf-c1d2f16ca61e)

**Comment by chilingling** [comment]
@HelloCPL 
感谢使用 TinyEngine，如果有其他问题或者 bug，欢迎反馈。现在将该 issue 关闭。
