### ISSUE TITLE
🐛 [Bug]: 画布切换组件后绑定事件列表依然还是原组件的绑定事件列表

### ISSUE THREAD

**Issue by langyjn** [opentiny/tiny-engine#747]
### Environment

chrome

### Version

latest

### Version

latest

### Link to minimal reproduction

none

### Step to reproduce

重现步骤：
1.  点击box组件，查看绑定事件列表
2.  点击table组件，查看绑定事件列表
3.  切换回box组件，查看绑定事件列表，事件列表依然时table组件的事件列表
![IMG_2400](https://github.com/user-attachments/assets/a18803a6-ae68-4325-929e-d752e3ae83df)
![IMG_2401](https://github.com/user-attachments/assets/b8164d2f-9770-4eab-ad7a-7650abbca333)
![IMG_2402](https://github.com/user-attachments/assets/bc9f2c58-6561-4d2e-bf3e-b00b698ffab6)

 

### What is your project name

tiny-engine branch：develop

**Comment by kikoshoung** [comment]
same issue +1

**Comment by jxxl998** [comment]
same 🙌
