### ISSUE TITLE
🐛 [Bug]: 数据源批量删除后，按钮状态没有更新问题

### ISSUE THREAD

**Issue by langyjn** [opentiny/tiny-engine#784]
### Environment

chrome

### Version

latest

### Version

latest

### Link to minimal reproduction

none

### Step to reproduce

如图所示，删除静态数据后，"批量删除"按钮没有置灰
![1](https://github.com/user-attachments/assets/d8f7cdd7-061f-402b-8b8e-e384b707b5c1)
![2](https://github.com/user-attachments/assets/47166f6d-04e5-4156-8d30-1419d22717df)
![3](https://github.com/user-attachments/assets/a71b6906-0445-4ccd-a50b-87cf69802571)

### What is your project name

tiny-engine develop

**Comment by chilingling** [comment]
感谢反馈 @langyjn
