### ISSUE TITLE
🐛 [Bug]: 页面切选后，点击区块管理无反应

### ISSUE THREAD

**Issue by xiejay97** [opentiny/tiny-engine#786]
### Environment

128.0.6613.113

### Version

20.12.2

### Version

latest

### Link to minimal reproduction

 null

### Step to reproduce

 null

### What is actually happening

https://github.com/user-attachments/assets/3a9b31ec-5d3f-403a-be5d-622dc2e02eb0

### What is your project name

null

**Comment by chilingling** [comment]
感谢反馈 @xiejay97
