### ISSUE TITLE
🐛 [Bug]: TinyTabs物料组件拖入到画板后，拖拽右侧属性面板调整tab标签顺序，画板中顺序改变了，但属性面板tab标签顺序没有改变

### ISSUE THREAD

**Issue by youchen133** [opentiny/tiny-engine#79]
### Environment

mac

### Version

16

### Version

latest

### Link to minimal reproduction

<img width="2062" alt="image" src="https://github.com/opentiny/tiny-engine/assets/27907927/1e79b168-da07-430e-9a4a-949218da46ed">

### Step to reproduce

无

**Comment by wenmine** [comment]
@chilingling 帮忙看一下这个问题
