### ISSUE TITLE
🐛 [Bug]: tiny-engine-ui里bundle.json配置popeditor错了一个小小的地方

### ISSUE THREAD

**Issue by sunny-Fung** [opentiny/tiny-engine#875]
### Environment

local

### Version

node -v 18.20.3

### Version

"@opentiny/vue": "~3.14.0"

### Link to minimal reproduction

![企业微信截图_17296552451399](https://github.com/user-attachments/assets/6095d666-f56f-43dd-b3b0-2799d83a96ed)

![企业微信截图_17296554149182](https://github.com/user-attachments/assets/b3194a37-7a06-4edd-84fe-a094e70d777a)

![企业微信截图_17296554341046](https://github.com/user-attachments/assets/121d7bc7-d222-48f7-aa8a-2379bd213c3a)

### Step to reproduce

预览页会提醒报错原因，打开js一看发现命名不一致，需要改一下

### What is your project name

any

**Comment by chilingling** [comment]
可以直接给我们提 PR @sunny-Fung
