### ISSUE TITLE
🐛 [Bug]: 表单设计中使用ref, 但出码没有ref定义，导致异常

### ISSUE THREAD

**Issue by stwflyfox** [opentiny/tiny-engine#89]
### Environment

chorme

### Version

latest

### Version

latest

### Link to minimal reproduction

如题

### Step to reproduce

![image](https://github.com/opentiny/tiny-engine/assets/3983204/ea9b6744-fa22-469e-9064-d57838d4d929)
![image](https://github.com/opentiny/tiny-engine/assets/3983204/c8344046-676a-4a84-9595-a2417ae1f046)

**Comment by wenmine** [comment]
@stwflyfox 已收录，我们会尽快解决这个问题的，感谢反馈

**Comment by wenmine** [comment]
@stwflyfox 您好，我们看了一下这部分的内容，应该是是 ref API 使用有误引起的（低代码引擎的 ref 和 Vue3 原生的 ref，用法有区别）。

低代码引擎的 ref，正确用法：this.$('form')
文档：https://opentiny.design/tiny-engine#/protocol/demos:~:text=ref-,%E5%A6%82%E4%B8%8B%E4%BE%8B%E5%AD%90%EF%BC%8C%E4%BD%BF%E7%94%A8%20ref%20%E6%97%B6%EF%BC%8C,-%E9%A6%96%E5%85%88%E5%AF%B9%20ref

**Comment by stwflyfox** [comment]
好的，我再试一下，谢谢。
