### ISSUE TITLE
✨ [Feature]: 如何添加自定义组件、区块？

### ISSUE THREAD

**Issue by Manson596** [opentiny/tiny-engine#91]
### What problem does this feature solve

在物料区添加组件是否都要手动在packages/settings/design/src/schemas添加属性配置，能否自动生成？
目前基于Img组件添加了一个简单的自定义组件 我要在bundle.json复制一份img的属性来拓展，这份组件属性配置每次都要手写？

### What does the proposed API look like

是否项目中有api可以生成组建的配置属性？

**Comment by wenmine** [comment]
@Manson596 您好，当前使用bundle.json的形式支持的是我们引入第三方组件，而我们自定义区块在tinyengine中因为依赖构建和发布，以及相对应的api。这部分内容需要等到12月份后端开源后，将tiny-engine前后端进行配套后，才能真正的开放。

**Comment by Manson596** [comment]
目前我仿造内置img组件在packages/canvas/src/components/builtin.json等文件添加了自定义组件 设计器中显示正常，但是预览的时候看到接口schemas2code只返回了我自定义的组件名称，并没有返回template结构

**Comment by ghost** [comment]
@Manson596 内置组件在画布中正常渲染是简单的组件引用，预览经DSL出码时对这些组件做了转换处理，如Text组件转换为span标签（见vue-generator下的text2Span函数）。
如要添加自定义组件，可参考Text组件转换方式在DSL中进行特殊处理。
