### ISSUE TITLE
🐛 [Bug]: 官网demo页面，预览时，下拉框内容选择不生效。控制台有JS报错

### ISSUE THREAD

**Issue by chenyl1982** [opentiny/tiny-engine#913]
### Environment

edge

### Version

latest

### Version

latest

### Link to minimal reproduction

https://opentiny.design/tiny-engine#/tiny-engine-editor

### Step to reproduce

![image](https://github.com/user-attachments/assets/a2b10773-ba2c-47cf-befd-4074c51c7fd8)

### What is expected

选择后，下拉框显示选择的项目。

### What is actually happening

选择后，下拉框里面还是空的。

### What is your project name

暂无

### Any additional comments (optional)

无

**Comment by LKCheng** [comment]
需绑定变量，可正常选择
