### ISSUE TITLE
🐛 [Bug]: 引入的第三方组件，设计器中可以显示，但预览异常

### ISSUE THREAD

**Issue by stwflyfox** [opentiny/tiny-engine#95]
### Environment

chrome

### Version

latest

### Version

latest

### Link to minimal reproduction

按照文档引入ElInput，在设计器中可以显示，点预览时无法显示并有异常信息

### Step to reproduce

![image](https://github.com/opentiny/tiny-engine/assets/3983204/68290a27-c236-4c6a-a767-ba8ff4b60cd0)
![image](https://github.com/opentiny/tiny-engine/assets/3983204/b652c8e8-f502-4134-9266-da5a870b86c1)

**Comment by wenmine** [comment]
@yaoyun8 帮忙看看~

**Comment by ghost** [comment]
@stwflyfox 请检查下是否按照文档中步骤，新增组件在预览时需要修改mockServer数据。
打开应用数据文件：mockServer\src\services\appinfo.json
将组件数据（bundle.json中的data.material.components）拷贝到appinfo.materialHistory.components
刷新页面，点击预览

**Comment by stwflyfox** [comment]
把components复制到appinfo.json后还是一样，不知道复制的位置是否正确。
![image](https://github.com/opentiny/tiny-engine/assets/3983204/84dfa149-43ee-430a-ad61-3e0a62ae2d66)
![image](https://github.com/opentiny/tiny-engine/assets/3983204/1cfad181-bba4-4f9c-a4da-e29c61a2144f)

**Comment by ghost** [comment]
@stwflyfox  数据路径是mockServer\src\services\appinfo.json 中 appinfo.materialHistory.components
